### ISSUE TITLE
Hint that using `data` is wrong

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#1000]
From time to time i see ppl using `data` instead of `body` which is wrong.
happened just recently in https://github.com/node-fetch/node-fetch/issues/481#issuecomment-717864624

how do you feel about adding a little warning message that can only appear once. (kinda like node reports that you are using experimental apis)

```js
if ('data' in bodyInit && notWarned) {
  console.warn('use body instead')
}
class Response {
  get data () {
    notWarned && console.warn('you want to use .json(), .text(), .arrayBuffer() or just .body')
  }
}
```

I don't think it is uncommon to see those mistake happening when switching from different request libraries `axios` use data instead of body for example. I can admit that i have used data as well and wasted minutes trying to figure out what's wrong

**Comment by jimmywarting** [comment]
Yay, i claimed issue 1000 🎉

**Comment by dork1** [comment]
I am still learning all the ins and outs of various libraries and indeed my code was adapted from an `axios` example so an error like stated above would help loads in pinpointing the problem. Thank you! @jimmywarting

**Comment by tekwiz** [comment]
@jimmywarting I think this makes sense, but I would throw an Error because they're probably going to get one anyway when they try to use the undefined return value

**Comment by jimmywarting** [comment]
I don't think an error should be thrown... it's not what is happening in (mostly) any method where you are allowed to pass in a object, other options are just ignored. it has the risk to break things as it wouldn't be backwards compatible.

You can get a request option from an arbitrary place that could include both `body` and `data` option and dosen't fully looks like a Request init option.

We try to align us self with how the whatwg fetch works in the browser and the spec. we never know the true intention if the developer really meant to post the `data` option or if it's just a extra arbitrary option that comes from somewhere else

**Comment by tekwiz** [comment]
@jimmywarting And oops for me, too... I was only thinking about `Response.data`. I agree with this, and I also agree now with what you were saying about warning only once:

> when i think about it `response.data` could potentially throw a `TypeError` but `new Request(x, { method: 'post', data })` should warn

**Comment by Richienb** [comment]
It's a good idea, but I'm not sure how far we should deviate from the original fetch spec.

**Comment by jimmywarting** [comment]
> It's a good idea, but I'm not sure how far we should deviate from the original fetch spec.

it's not like we are adding any new feature/method into fetch, it's just a way of helping/notifying that what you might be doing is wrong. such feature could easily be removed if we ever decide to ditch it again
