### ISSUE TITLE
Response.json() doesn't allow for a reviver to be passed

### ISSUE THREAD

**Issue by pmkevans** [node-fetch/node-fetch#1010]
The JavaScript API for JSON parsing allows for a reviver to be passed.  There's no scope in node-fetch to use that functionality.

Revivers are particularly handy when using concrete types and it'd be great to have them supported by node-fetch as well.  An optional reviver parameter on Body.json() would be spectacular.

**Comment by jimmywarting** [comment]
Won't happen.
We follow the spec, so if the spec don't change then we won't do it. our philosophy is that it should work the same in browser, deno and node-fetch 

you would have to do it on your own for now. `res.text().then(str => JSON.parse(str, reviver))`

---

You should present your idea to https://github.com/whatwg/fetch
