### ISSUE TITLE
Error: Cannot find module 'node-fetch' after runing 'npm install node-fetch'

### ISSUE THREAD

**Issue by TheDaekLord1989** [node-fetch/node-fetch#1027]
I got the error: Cannot find module 'node-fetch' after runing 'npm install node-fetch', I have already tried to reinstall node-ferch and reinstall Node.js. Everything didnt work. Please help.

Error down here
===================================================================================
Require stack:
- /home/watchandytw/Cute_Lemon's BOT :D/Discord.JS-Leveling-Bot/node_modules/discord.js/src/util/Util.js
- /home/watchandytw/Cute_Lemon's BOT :D/Discord.JS-Leveling-Bot/node_modules/discord.js/src/index.js
- /home/watchandytw/Cute_Lemon's BOT :D/Discord.JS-Leveling-Bot/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/watchandytw/Cute_Lemon's BOT :D/Discord.JS-Leveling-Bot/node_modules/discord.js/src/util/Util.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    "/home/watchandytw/Cute_Lemon's BOT :D/Discord.JS-Leveling-Bot/node_modules/discord.js/src/util/Util.js",
    "/home/watchandytw/Cute_Lemon's BOT :D/Discord.JS-Leveling-Bot/node_modules/discord.js/src/index.js",
    "/home/watchandytw/Cute_Lemon's BOT :D/Discord.JS-Leveling-Bot/index.js"
  ]
}
===================================================================================

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.1
| node             | 15.2.1
| npm              | 7.0.8
| Operating System | Ubuntu 20.04.1 LTS

**Comment by Richienb** [comment]
Before running `npm install node-fetch`, try this:

```sh
npm install -g npm
npm cache clean
npm update
```

**Comment by tekwiz** [comment]
@TheDaekLord1989 If you are still having trouble, please post your index.js and package.json files.

**Comment by mihanizm56** [comment]
the same troble with linting - goes to error in console
![image](https://user-images.githubusercontent.com/37120827/107133199-be5de480-68f6-11eb-8f1d-3f250ff3ea4c.png)

**Comment by mihanizm56** [comment]
source code here
but with eslint ignore because of this issue
https://github.com/mihanizm56/fetch-api

**Comment by k3n** [comment]
I had this problem as well. Followed all of the steps given above, no change.

Node.js v14.16.0
node-fetch@2.6.1
MacOS Catalina

I fixed it by installing locally (vs. globally).

Fails to find module:

```sh
npm i -g node-fetch
```

Finds module:

```sh
npm i node-fetch
```

**Comment by mug896** [comment]
k3n : I think you need setting NODE_PATH environment variable

**Comment by Richienb** [comment]
`node-fetch` is not made to be installed globally. https://stackoverflow.com/questions/7970793/how-do-i-import-global-modules-in-node-i-get-error-cannot-find-module-module

If you are not installing it globally and it still fails, try [these steps](https://github.com/node-fetch/node-fetch/issues/1027#issuecomment-738401483).

**Comment by mihanizm56** [comment]
> `node-fetch` is not made to be installed globally. https://stackoverflow.com/questions/7970793/how-do-i-import-global-modules-in-node-i-get-error-cannot-find-module-module
> 
> If you are not installing it globally and it still fails, try [these steps](https://github.com/node-fetch/node-fetch/issues/1027#issuecomment-738401483).

No, I did not try to install it globally - only in my dir with repo.
The situation is not change, your steps dont help.

Why do you close this issue?

**Comment by mihanizm56** [comment]
> k3n : I think you need setting NODE_PATH environment variable something like this
> 
> bash$ export NODE_PATH=/home/james/nodejs/lib/node_modules

Oh, this may help only if global install...

**Comment by CarsonSlovoka** [comment]
```js
// source
(async() => {
  const data = await (await fetch('https://api.github.com/gists/66db7c87873b63918e5451b06df8e0f0')).json()
  console.log(data.files.SAS.content)
})()
```
Cannot find module 'node-fetch'

```json5
// tsconfig.json
{
  "compilerOptions": {
    "target": "ES2021",
    "lib": [
      "ES2021",
      "dom",
      "dom.iterable"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "rootDir": ".",
    "outDir": "../out",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "allowJs": true
  }
}
```


```json5
// package.json
  // ...
  "dependencies": {
    "node-fetch": "^3.2.10"
  }
```

I try

```
// ✅ Do this if using TYPESCRIPT
import { RequestInfo, RequestInit } from 'node-fetch';

const fetch = (url: RequestInfo, init?: RequestInit) =>
  import('node-fetch').then(({ default: fetch }) => fetch(url, init));

// ...
```
↑ from this article: https://bobbyhadz.com/blog/javascript-error-err-require-esm-of-es-module-node-fetch

Unfortunately, it still doesn't work.

**Comment by Richienb** [comment]
> Unfortunately, it still doesn't work.

Can't you just:

```js
import fetch from 'node-fetch';
```

**Comment by CarsonSlovoka** [comment]
> Can't you just:
> 
> ```js
> import fetch from 'node-fetch';
> ```

I got 
```
const node_fetch_1 = __importDefault(require("node-fetch"));
                                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\...\node_modules\node-fetch\src\index.js
from C:\...\main.js not supported.
Instead change the require of index.js in C:\...\main.js to a dynamic import() which is a
vailable in all CommonJS modules.
    at Object.<anonymous> (C:\...\main.js:10:38) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by jimmywarting** [comment]
take a look in https://github.com/node-fetch/node-fetch/issues/1279

one solution to load esm in cjs is via: 
```js
const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));
```

**Comment by CarsonSlovoka** [comment]
I want to write a github action, but it seems to work only with commonjs, not entirely with ECMAScript.

I'm using typescript.

"module" must be "commonjs", otherwise there will be other problems. I can't adjust it to ES2020 like your article.
["modules": "ES2020"](https://github.com/node-fetch/node-fetch/issues/1279#issuecomment-915062146)

This is a very difficult problem. I have given up and used the "http**s**.request" instead; although I have to write more things than `fetch`

**Comment by rotcivegaf** [comment]
> take a look at #1279
> 
> one solution to load esm in cjs is via:
> 
> ```js
> const fetch = (...args) => import('node-fetch').then(({default: fetch}) => fetch(...args));
> ```

Thanks, MAGIC!

**Comment by Beyondo** [comment]
I had the same problem, but just needed to install its types through: `npm install --save-dev @types/node-fetch`.

I thought the types already came with it, but apparently not.

**Comment by jacob30** [comment]
> I had the same problem, but just needed to install its types through: `npm install --save-dev @types/node-fetch`.
> 
> I thought the types already came with it, but apparently not.

Since 3.x types are bundled with node-fetch, so you don't need to install any additional packages.
https://www.npmjs.com/package/node-fetch#typescript
