### ISSUE TITLE
{signal: undefined} crashes node-fetch

### ISSUE THREAD

**Issue by jeysal** [node-fetch/node-fetch#1029]
**Reproduction**

```js
require('node-fetch')('http://example.com', { signal: undefined })
// TypeError: Expected signal to be an instanceof AbortSignal
```

**Expected behavior**

Same as
```js
require('node-fetch')('http://example.com', {})
```

---

Now, technically there is nothing in the fetch spec that says this is wrong:
```
28. If init["signal"] exists, then set signal to it.
30. If signal is not null, then make this’s signal follow signal.
```
where the [infra spec says](https://infra.spec.whatwg.org/#nulls)
```
The value null is used to indicate the lack of a value. It can be used interchangeably with the JavaScript null value. [ECMA-262]
```
`node-fetch` has implemented the `exists` using the `in` operator, which finds that `signal` exists even if it is `undefined`, and then uses it because it is not (`!==`) `null`. However, bearing in mind that the Fetch and Infra specs almost never mention the `undefined` value, I don't think it should be read this pedantically and `{signal: undefined}` as an `init` is intended to break the `fetch` call.
Also, with Firefox, Chromium, and https://github.com/github/fetch all implementations that I've checked handle this gracefully.

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.0.0-beta.8
| node             | 12.18.3
| npm              |
| Operating System |

**Comment by tekwiz** [comment]
@jeysal Thanks for pointing this out.  I've put in pull-request #1050 to allow any falsey value for `signal` to be ignored.
