### ISSUE TITLE
require('node-fetch').default works but global.fetch = require('node-fetch') does not

### ISSUE THREAD

**Issue by s1mrankaur** [node-fetch/node-fetch#1037]
In my node-js app, I installed node-fetch and required it in a file with lambda function(ran it using sls invoke)  :

`global.fetch = require('node-fetch');`

This did not work and I was still getting an error `Fetch is not a function`.

I instead changed it to:

`global.fetch = require('node-fetch').default;`

and this worked. Why is that?

 In a separate .js file (but not a lambda function) that I was running using node command,  It did work fine with

` global.fetch = require('node-fetch');
`
what's the difference?

**Comment by tekwiz** [comment]
@s1mrankaur What version of node are you using outside of Lambda?

**Comment by robofearth** [comment]
Also having this issue.

Also confirmed using the .default import fixes the issue, as mentioned by @s1mrankaur.

Noticed it when compiling this package running a debug launch process in VS Code, that builds a webpack task.

**Looked into packed file output using a debugger step-through. Noticed it loads the whole module directly and not the default function "fetch".**

E.g. No .default, references module:

![Screen Shot 2021-06-03 at 3 53 58 pm](https://user-images.githubusercontent.com/8605335/120594268-0dbab880-c484-11eb-9dd5-eabc059a426e.jpg)

With default, references default fetch function:

![Screen Shot 2021-06-03 at 3 56 27 pm](https://user-images.githubusercontent.com/8605335/120594424-465a9200-c484-11eb-8c40-567cf0bcacac.jpg)



Versions of platform noticed on:

Node.JS: 16.2.0
Webpack used in project: 5.3.2
Webpack configs: target: node, mode: development, and devtool: source-map. No specific libraryLarget for output
OS: MacOS 11.4 (Big Sur)
VS Code (stable): 1.56.2

**Comment by bflemi3** [comment]
Was there a resolution for this issue? I've run into the same problem.
