### ISSUE TITLE
Question about comparing Node version

### ISSUE THREAD

**Issue by imzcy** [node-fetch/node-fetch#1038]
I might be missing something, but this does not seem correct:

https://github.com/node-fetch/node-fetch/blob/17b6c10052dc790f63ebe5b5d18db7f8fbda6068/src/index.js#L190

From https://nodejs.org/api/process.html#process_process_version, it seems the `process.version` is a string and should be compared in `semver` format. Or is this intended?

```javascript
'v12.2.0' < 'v12.10' // false
```

**Comment by tekwiz** [comment]
Great catch @imzcy!  I was working on fixing tests for node 12 in #1023 and determined the test case that hits this branch in Node 12.3-12.9 just couldn't be simulated.  Now, I know why.  I've fixed this in that PR: 122614b
