### ISSUE TITLE
Mutual TLS?

### ISSUE THREAD

**Issue by ianpogi5** [node-fetch/node-fetch#1039]
Is it possible to do mutual TLS in node-fetch?

**Comment by tekwiz** [comment]
@ianpogi5 Use an [`https.Agent`](https://nodejs.org/api/https.html#https_class_https_agent).  Options passed to its constructor will be passed on to [`tls.connect()`](https://nodejs.org/api/tls.html#tls_tls_connect_options_callback) (which also takes options for [`tls.createSecureContext()`](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options)).

```js
const key = fs.readFileSync('client-key.pem');
const cert = fs.readFileSync('client-cert.pem');
const agent = https.Agent({ key, cert });
const res = await fetch(uri, { agent });
```

**Comment by ianpogi5** [comment]
Thanks @tekwiz I will try this out.
