### ISSUE TITLE
multiple fetch not working 

### ISSUE THREAD

**Issue by Galaxy-Coding** [node-fetch/node-fetch#1040]
my code in node.js is not working
i am using discord.js, so treat message.channel.send like console.log
`
const fetch = require('node-fetch');
const settings = { method: 'Get' };

fetch('https://official-joke-api.appspot.com/random_joke', settings)
			.then(res => res.json())
			.then(json => {
				message.channel.send(`${json.setup}\n${json.punchline}`);
			});

`
This doesn’t seem to work for me
please help 😄 thank you so much

**Comment by tekwiz** [comment]
@Galaxy-Coding Lots more information is needed to help you with this.  Please include all the requested information in the template.

**Comment by Galaxy-Coding** [comment]
@tekwiz seems like my IP was blocked from the API
