### ISSUE TITLE
SyntaxError in index.js:1

### ISSUE THREAD

**Issue by OfficialMarzYT** [node-fetch/node-fetch#1046]
I'm trying to run my discord bot but i get this error

Uncaught <insert path here>\node_modules\node-fetch\lib\index.js:1

SyntaxError: Invalid or Unexpected token

`const Discord = require('discord.js');

const client = new Discord.Client();

const prefix = '^';
    
client.on("ready", function() {
    client.user.setActivity('Version 1.1.1');
    console.log("ITS ALIVE!!")
})

const helpMessage = new Discord.MessageEmbed()
    .setColor('#8af5ff')
    .setTitle('i am bingus i do things')
    .setAuthor('Help')
    .setThumbnail('https://i.imgur.com/2RST8cy.gif')
    .addFields(
        { name: 'Fun Commands', value: '^bingus, ^marz, ^duck, ^angry, ^dead, ^whoasked.' },
        { name: 'Other commands', value: '^help, ^version, ^invite'},
    );

client.on('message', message =>{
    if(message.author.bot) return;
    const args = message.content.slice(prefix.length).split(/ +/);
    const command = args.shift().toLowerCase(); 

    if(command === 'bingus'){
        message.channel.send('https://tenor.com/view/bingus-cat-sphinx-gif-18474227');
    }
    else if(command === 'marz'){
        message.channel.send('https://yt3.ggpht.com/a/AATXAJwIVVg02Qz8sfdFkOIj8kAu6k6ooHCDSAgG9uMjQA=s88-c-k-c0x00ffffff-no-rj');
    }
    else if(command === 'duck'){
        message.channel.send('https://media.discordapp.net/attachments/696975977636429876/748969759273386045/image0.gif');
    }
    else if(command === 'help'){
        message.channel.send(helpMessage);
    }
    else if(command === 'whoasked'){
        message.channel.send('https://cdn.discordapp.com/attachments/705237224882569246/766485320380055552/image0.png');
    }
    else if(command === 'angry'){
        message.channel.send('https://i.imgur.com/VrHZMOn.png');
    }
    else if(command === 'dead'){
        message.channel.send('https://i.imgur.com/1TUu8X6.png');
    }
    else if(command === 'version'){
        message.channel.send('BingusBot is on version 1.1.1');
    }
    else if(command === "invite" || command === "links") {
        message.channel.send({embed: {
        title: "Invite",
        url: "https://discord.com/oauth2/authorize?client_id=764181305541525576&permissions=8&scope=bot",
        description: "You can invite me [here](https://discord.com/oauth2/authorize?client_id=764181305541525576&permissions=8&scope=bot)"}})
    }
    else {
    message.channel.send("`" + command + "` is not a command, please do ^help for help.")
    }
});

client.login('--------------------------------------')`

| ---------------- | -------
| node-fetch v2.6.1 |
| node 15.2.0 |
| npm 7.0.8 |
| Windows 10 |

**Comment by tekwiz** [comment]
@OfficialMarzYT Please include all the information noted in the issue template.  We can't help you without that context.

**Comment by OfficialMarzYT** [comment]
sorry, edited.

**Comment by tekwiz** [comment]
@OfficialMarzYT We still need a code snippet to see what you're doing.

**Comment by Dragonizedpizza** [comment]
> SyntaxError: Invalid or Unexpected token
@OfficialMarzYT, 'SyntaxError: Invalid or Unexpected token' means its an error with your code, not the package.

**Comment by OfficialMarzYT** [comment]
> > SyntaxError: Invalid or Unexpected token
> > @OfficialMarzYT, 'SyntaxError: Invalid or Unexpected token' means its an error with your code, not the package.

No its definitely a problem with Node-Fetch beause i deleted all of the code that did something and is still doesnt work

**Comment by OfficialMarzYT** [comment]
`const Discord = require('discord.js');

const client = new Discord.Client();

const prefix = '^';
    
client.on("ready", function() {
    client.user.setActivity('Version 1.1.1');
    console.log("ITS ALIVE!!")
})

const helpMessage = new Discord.MessageEmbed()
    .setColor('#8af5ff')
    .setTitle('i am bingus i do things')
    .setAuthor('Help')
    .setThumbnail('https://i.imgur.com/2RST8cy.gif')
    .addFields(
        { name: 'Fun Commands', value: '^bingus, ^marz, ^duck, ^angry, ^dead, ^whoasked.' },
        { name: 'Other commands', value: '^help, ^version, ^invite'},
    );

client.on('message', message =>{
    if(message.author.bot) return;
    const args = message.content.slice(prefix.length).split(/ +/);
    const command = args.shift().toLowerCase(); 

    if(command === 'bingus'){
        message.channel.send('https://tenor.com/view/bingus-cat-sphinx-gif-18474227');
    }
    else if(command === 'marz'){
        message.channel.send('https://yt3.ggpht.com/a/AATXAJwIVVg02Qz8sfdFkOIj8kAu6k6ooHCDSAgG9uMjQA=s88-c-k-c0x00ffffff-no-rj');
    }
    else if(command === 'duck'){
        message.channel.send('https://media.discordapp.net/attachments/696975977636429876/748969759273386045/image0.gif');
    }
    else if(command === 'help'){
        message.channel.send(helpMessage);
    }
    else if(command === 'whoasked'){
        message.channel.send('https://cdn.discordapp.com/attachments/705237224882569246/766485320380055552/image0.png');
    }
    else if(command === 'angry'){
        message.channel.send('https://i.imgur.com/VrHZMOn.png');
    }
    else if(command === 'dead'){
        message.channel.send('https://i.imgur.com/1TUu8X6.png');
    }
    else if(command === 'version'){
        message.channel.send('BingusBot is on version 1.1.1');
    }
    else if(command === "invite" || command === "links") {
        message.channel.send({embed: {
        title: "Invite",
        url: "https://discord.com/oauth2/authorize?client_id=764181305541525576&permissions=8&scope=bot",
        description: "You can invite me [here](https://discord.com/oauth2/authorize?client_id=764181305541525576&permissions=8&scope=bot)"}})
    }
    else {
    message.channel.send("`" + command + "` is not a command, please do ^help for help.")
    }
});

client.login('NzY0MTgxMzA1NTQxNTI1NTc2.X4ChTQ.Z-kf3sb4JlsZIRE97WM1TsCkJgQ')`

**Comment by tekwiz** [comment]
@OfficialMarzYT I don't see any usage of node-fetch in your code.

**Comment by tekwiz** [comment]
@OfficialMarzYT 

> it wouldn't fully go in the code thing for some reason

This points to your code's syntax error. Please search for backticks (`)

**Comment by Dragonizedpizza** [comment]
> No its definitely a problem with Node-Fetch beause i deleted all of the code that did something and is still doesnt work
< Do you mean you deleted all the code that used node-fetch or all the code itself?
