### ISSUE TITLE
How to read file from disk using node-fetch

### ISSUE THREAD

**Issue by RezaRahmati** [node-fetch/node-fetch#1047]
**Example Code**

I want to read a file located in `path.join(__dirname,'models')` and have the result as http response (it's required by another library to be like that)

But right now I get `Only absolute URLs are supported`

**Expected behavior, if applicable**

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.1
| node             | 14
| npm              | 6.4
| Operating System | windows

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by tekwiz** [comment]
@RezaRahmati Is your objective just to have the contents of the file wrapped in the `Response` object?

**Comment by RezaRahmati** [comment]
@tekwiz yes exactly

**Comment by jimmywarting** [comment]
Maybe this will work for you? `new Response(fs.createReadStream(path))`

alternativt method if using `fetch-blob`
```js
const from = require('fetch-blob/from.js')

const blob = from(path)
const res = new Response(blob) // this way you also get content-length header
```
