### ISSUE TITLE
npm install node-fetch does NOT install 3.x

### ISSUE THREAD

**Issue by simonh1000** [node-fetch/node-fetch#1049]
**Reproduction**

1. npm install node-fetch
2. look in package.json - 2.6.1
3. 
4. 

**Expected behaviour**

3.x

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       |
| node             |. 12
| npm              | 6.4.18
| Operating System | Macos

**Additional context**

**Comment by tekwiz** [comment]
@simonh1000 Version 3 is currently in beta. You can install it with `npm install node-fetch@3.0.0-beta.9`

**Comment by simonh1000** [comment]
Thanks - might be worth adding that to the README as it certainly tripped me up
