### ISSUE TITLE
response.body should fail if server terminates connection before response is fully transmitted

### ISSUE THREAD

**Issue by Gozala** [node-fetch/node-fetch#1055]
If server terminates connection before response is fully transmitted that should cause an error. In fact that seems to be the case when consuming the response e.g. via `response.text()` API. However if `response.body` is used directly via for await loop no errors are reported.

**Reproduction**

Test case is provided by #1056

**Expected behavior**

Following code should log error if connection is terminated before transmission is complete, instead loop is complete without any errors

```js
try {
  for await (const chuck of response.body) {
    // ...
  }
} catch(error) {
  console.error(error)
}
```

**Screenshots**

Same code in browsers produces error as expected here is an example (querying same server) as the attached test:

<img width="1022" alt="Screen Shot 2020-12-31 at 5 27 15 PM" src="https://user-images.githubusercontent.com/21236/103432198-20a52600-4b90-11eb-8c5f-2cfb3a3e78f2.png">

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | master
| node             | v12.18.2
| npm              |6.14.5
| Operating System | Mac

**Comment by tekwiz** [comment]
@Gozala Please take a look at #1064 and see if it solves this problem.  You should be able to try it in your project with:

```sh
npm install 'github:tekwiz/node-fetch#fix-chunked-transfer-premature-close-2'
```
