### ISSUE TITLE
Response statusText must be empty string

### ISSUE THREAD

**Issue by 11ume** [node-fetch/node-fetch#1066]
[Fetch API statusText](https://developer.mozilla.org/en-US/docs/Web/API/Response/statusText)

#### Diference
Fetch API browser the default value is **""**.

Node-fetch the default value **'unknown'**.

This maybe can generate inconsistencies in test environments.

**Comment by MSE99** [comment]
I just checked, the default value is in fact an empty string '', could you provide a repo that reproduces the bug ?.

**Comment by tekwiz** [comment]
@11ume I believe this is fixed in v3 beta. Would you try installing that and checking your test case?

**Comment by 11ume** [comment]
By default the node.js defines and send status messages, if it does not recognize one, it defines it as 'unknown'.

HTTP/1.1 200 ok

### For example

Make a custom status code like one used by Twitter:

res.statusCode = 420

Node reply: HTTP/1.1 420 unknown

#### In browser
(await fetch ('http: // localhost: 3000')) .statusText // ""

Anyway, how its a 4xx, the browser issues an error net::ERR_ABORTED 420 (unknown).

#### In Node
(await fetch ('http: // localhost: 3000')) .statusText // "unknown"

**Comment by 11ume** [comment]
@tekwiz
I try in 
"node-fetch": "^3.0.0-beta.9". 
Anyway, it's an inconsistency with the Fetch API but, really I don't know if it's wrong.
I just wanted to report this, it doesn't really bother me, because it is the correct behavior of the node.

**Comment by tekwiz** [comment]
@11ume I think what's happening is that the status text `unknown` is actually being put into the HTTP response. If that is the case, `response.statusText` should return `"unknown"`. If is is missing or HTTP 2 (which doesn't have a status text), it should be the empty string. I'll verify that node-fetch is doing this correctly or put in a pull request to fix.

**Comment by tekwiz** [comment]
@11ume I've verified that `statusText` is operating according to the specification when it's missing in the response and submitted a pull-request with a test case..
