### ISSUE TITLE
Memory leak when using get inside setInterval()

### ISSUE THREAD

**Issue by sayantan300** [node-fetch/node-fetch#1067]
This bug was encountered when I was pinging my site on glitch 😅. I made an interval to "get" the glitch project url to keep it alive. However, since my home  page was like 1mb, after some time, the memory usage shown on glitch project status clearly showed that every mins. Then I decreased the time to per sec, and the memory usage increased 1mb per sec, which clearly showed it was caching the site every time.. so this clearly shows its a memory leak 😳.

**Comment by tekwiz** [comment]
@sayantan300 Please follow the bug report template. We need version information and code to properly diagnose this issue.

**Comment by sayantan300** [comment]
I use the latest version always. That is `2.6.1`.

I don't get any error except glitch stops my project and restarts it

**Comment by sayantan300** [comment]
@tekwiz

**Comment by tekwiz** [comment]
@sayantan300 We still need your code.

**Comment by sayantan300** [comment]
Ok, I am giving a more faster code (big file to fetch ~ 1mb, and the interval is 1ms)
```js
let i = 0;
const fetch = require("node-fetch");
setInterval(function(){
i=i+1;
fetch("https://registry.npmjs.com/rovel.js/-/rovel.js-1.1.1").then(r=>r.text()).then(d=>console.log("Downloaded "+ i + "times"));
}, 1);
```

**Comment by sayantan300** [comment]
Make sure to try it on glitch, because they will show u memory usage, and their network is free and fast.

**Comment by LinusU** [comment]
V8 uses garbage collection and only cleans up when it has to, are you sure this isn't why you are seeing increased memory usage? I can't reproduce an actual memory leak locally:

```js
import fetch from 'node-fetch'

let i = 0

setInterval(() => {
  fetch('https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js')
    .then(response => response.text())
    .then(() => { i += 1 })
    .catch(err => console.log(`err ${err}`))
}, 100)

setInterval(() => {
  console.log(`Heaped used after ${i} requests: ${process.memoryUsage().heapUsed}`)
}, 5000)
```

```text
Heaped used after   47 requests:  6161944
Heaped used after   95 requests:  9570688
Heaped used after  144 requests: 10761752
Heaped used after  192 requests:  7110296
Heaped used after  241 requests:  7947176
Heaped used after  289 requests:  7942296
Heaped used after  338 requests:  4902784
Heaped used after  386 requests:  6871256
Heaped used after  435 requests:  8029432
Heaped used after  483 requests:  8134072
Heaped used after  531 requests: 12165720
Heaped used after  580 requests: 10308856
Heaped used after  628 requests:  9515576
Heaped used after  677 requests:  8949320
Heaped used after  725 requests:  8685224
Heaped used after  773 requests: 14439008
Heaped used after  821 requests: 15321840
Heaped used after  870 requests:  9420176
Heaped used after  918 requests: 15322448
Heaped used after  967 requests:  9109112
Heaped used after 1015 requests: 14640024
Heaped used after 1064 requests: 16022576
Heaped used after 1112 requests:  9405712
Heaped used after 1160 requests: 15948184
Heaped used after 1210 requests:  8936984
```

(change to jQuery because my ip got banned by Npm 😂 😭)

**Comment by tekwiz** [comment]
@sayantan300 The most likely explanation for what you're experiencing is stalled connections. Your code does not require a request to complete, so it is possible to essentially wait forever at the call to `Response.text()`. Please see the README.me for examples of how to create a timeout signal.

In addition, the code you provided essentially tries to create 1000 requests/second, download 1 GB/second, and allocate at least 1 GB in heap memory in the first second. This is surely to cause Glitch to terminate the application.

**Comment by sayantan300** [comment]
Btw my download size was 1kbps, therefore it's not a problem. It installs 4M+ times before glitch restarts my project. Also, I'm going to read what u told about that timeout signal. Thanks.
