### ISSUE TITLE
FetchError: request to URL failed, reason: Parse Error

### ISSUE THREAD

**Issue by Kreader-app** [node-fetch/node-fetch#1076]
When attempting to fetch the below URL I get a rejected Promise:

UnhandledPromiseRejectionWarning: FetchError: request to https://cloudblogs.microsoft.com/industry-blog/uploads/industry/2020/09/Microsoft-HC-Cloud_07_with-data-added-002.png failed, reason: Parse Error

URL:
https://cloudblogs.microsoft.com/industry-blog/uploads/industry/2020/09/Microsoft-HC-Cloud_07_with-data-added-002.png

Newest Node.js and node-fetch installed with apt get and npm install
- Node.js v10.23.1
- node-fetch@2.6.1

Minimal code to replicate

```
const fetch = require('node-fetch');

  const downloadFile = (async (url) => {
      const response = await fetch(url);
      });

var url ='https://cloudblogs.microsoft.com/industry-blog/uploads/industry/2020/09/Microsoft-HC-Cloud_07_with-data-added-002.png'


 downloadFile(url);
```

I can fetch the PNG file without problem with curl, wget or any browser. For some reason node-fetch fails.

**Comment by tekwiz** [comment]
@Kreader-app This is an issue for the node.js core team. The "Parse Error" you're seeing comes from the HTTP parser in node.js.  It looks like the server providing that URL is breaking a `Set-Cookie` header, thereby breaking the response:

```
Set-Cookie: ___utmvbFvuEXSFB=MZr
    XREOlalT: dtB; path=/; Max-Age=900
```
