### ISSUE TITLE
Body parameter in GET req doesn't accept null value in JSON format except that everything accepts in JSON

### ISSUE THREAD

**Issue by albert197** [node-fetch/node-fetch#1094]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jimmywarting** [comment]
- Don't put everything in the title
- Show code example of what works and don't work in comparison to window.fetch and node fetch
- GET requests can't have a body

I'm going to threat this as I do with other bad SO question, write a new/better issue... it's unclear why you saying
