### ISSUE TITLE
Add a global handler function

### ISSUE THREAD

**Issue by thernstig** [node-fetch/node-fetch#1104]
**Is your feature request related to a problem? Please describe.**

We supply a REST API. We are using `await fetch()` extensively in our code when calling external services. If an external service has a response where `res.ok` is falsy, we have to add a custom handler to every place we call `fetch`. I would like to simplify this logic for users that develop our REST API by adding a global handler.

**Describe the solution you'd like**

https://www.npmjs.com/package/node-fetch#handling-client-and-server-errors recommends this:

```js
function checkStatus(res) {
    if (res.ok) { // res.status >= 200 && res.status < 300
        return res;
    } else {
        throw MyCustomError(res.statusText);
    }
}
 
fetch('https://httpbin.org/status/400')
    .then(checkStatus)
    .then(res => console.log('will not get here...'))
```

I would rather want to to be able to add a custom handler, like:

```js
fetch.responseHandler(checkStatus()); // this should be globally set on fetch
fetch('https://httpbin.org/status/400');

// alternative to avoid using the default handler
fetch('https://httpbin.org/status/400', { handler: null });
// OR
fetch('https://httpbin.org/status/400', { handler: someOtherFunc() })
```

This way, I can create a sane approach where I can throw errors upstream in all API routes to be handled in a generic way when peer services fail. It would also be cool if the handler actually got access to more things, like the URL that was called and other options.

**Describe alternatives you've considered**

To use the handler at every invocation, but this is easy to miss for users.

**Comment by jakobrosenberg** [comment]
@thernstig did you find any workarounds for this?

**Comment by jimmywarting** [comment]
this will not happen, we follow the fetch specification. and we don't want to adda any extra non-spec'ed methods to this.

what you could do is adding a custom fetch method that dose it for you 

```js
async function request (...args) {
  const res = await fetch(...args) 
  if (res.ok) {
    return res
  } else {
    throw MyCustomError(res.statusText)
  }
}
```

and then you can always use `request` to make all the request
