### ISSUE TITLE
Fetching subdomains with special characters

### ISSUE THREAD

**Issue by discodamone** [node-fetch/node-fetch#1127]
**Reproduction**

1. fetch('otherdomain[.example.com') will fetch otherdomain/[.example.com

**Expected behavior**

I believe the request should fail, as is the case with the normal fetch api and location header within browsers.
https://tools.ietf.org/html/rfc1035

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.1
| node             | 12.18.4
| npm              | 6.14.8
| Operating System | ubuntu

**Additional context**

This has security implicatons, there are circumstances where any subdomains of a specific root domain are allowed to be fetched (and are user-supplied) but node-fetch adds a forward slash and allows other domains to be fetched

**Comment by ziv** [comment]
Reproduction:
```typescript
import {parse} from 'url';

console.log(parse('otherdomain[.example.com'));
```

Output:
```
Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  search: null,
  query: null,
  pathname: 'otherdomain[.example.com',
  path: 'otherdomain[.example.com',
  href: 'otherdomain[.example.com'
}
```

**Comment by ziv** [comment]
Opened a bug for NodeJS.
https://github.com/nodejs/node/issues/39467

**Comment by jimmywarting** [comment]
In fetch v3 we switched out the legacy url parser and switched it to use `new URL(url)` instead. 
Can you try out the latest version 3.0.0-beta.10 ?

it's going to be stable soon (within a month) if no more bugs/hotfixes or other breaking changes _really_ needs to be made. We currently do not plan to add/accept more features/PR's that could halt the release of the long awaited v3

**Comment by ziv** [comment]
@jimmywarting The v3 version is working well and raise the proper error.
NodeJS. closed my bug with link to the reference to ditch the using of Node url impl and prefer the WHATWG API.

BUT! we are using `node-fetch` as core HTTP client in our applications and v3 drop the cjs support and I can't use the esm without doing huge refactoring of millions lines of code... so I prefer bugs to solved in this version or keep the cjs support for legacy.

Maybe its for another issue :)

**Comment by jimmywarting** [comment]
We do not want to duplicate our codebase to work with both cjs and ems, and we do not want to compile with babel or anything anymore, that why we ditched cjs. You should also do it. Beside we have a other ESM only dependency right now that do not support cjs maybe soon two. 

So we are not going to support cjs anymore.
I think this will push the development of more standard modules forwards and benefit the hole ecosystem if more ppl just started using ESM so we can import them in browser and deno also without using something like NPM.

if you really want to use fetch in a cjs package then you can load it using the async `import()`
```js
function fetch(...args) {
  return import('node-fetch').then(m => m.default(...args))
}
```

I also belive you can mix cjs and esm if you do not want to refactor everything. Just have to change type to module and import a cjs file in the esm file
https://nodejs.org/api/packages.html#packages_approach_1_use_an_es_module_wrapper

**Comment by jimmywarting** [comment]
we use `new URL()` in both v2 and v3 now...
