### ISSUE TITLE
readme on npmjs outdated

### ISSUE THREAD

**Issue by ccdd13** [node-fetch/node-fetch#1128]
on npmjs section
 [#difference-from-client-side-fetch](https://www.npmjs.com/package/node-fetch#difference-from-client-side-fetch) different from
 [HEAD](https://github.com/node-fetch/node-fetch/blob/HEAD/README.md#difference-from-client-side-fetch)
 version.

old version point to [https://github.com/node-fetch/node-fetch/blob/HEAD/LIMITS.md (Page not found) ](https://github.com/node-fetch/node-fetch/blob/HEAD/LIMITS.md)

**Comment by xxczaki** [comment]
You are probably looking at the README for the v2 version.

**Comment by ccdd13** [comment]
i see from npm https://www.npmjs.com/package/node-fetch/v/3.0.0-beta.9 
that v2 is latest stable , and v3 is beta
