### ISSUE TITLE
Can't get content-type of the final request after redirect

### ISSUE THREAD

**Issue by ADrejta** [node-fetch/node-fetch#1140]
**Reproduction**

Use this url: https://cite.case.law/pdf/5713742/Blanks%20v.%20West%20Point%20Wholesale%20Grocery%20Co.,%20225%20Ala.%2074,%20142%20So.%2049%20(1932).pdf

Exctract headers with `response.headers.get('content-type')`

The result returns 'text/html; charset=utf-8'

**Expected behavior**
The result should be 'application/pdf'

I tried setting the redirect option since request is being redirected to both "follow" or "manual" but none of them gave the expected result. 
The url is being redirected as far as i can tell because the status code of the response is 302, but i need the actual final response that gives me the content-type of the link (application/pdf in this case)

Is there a different way to get the content-type of the final request?
**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.1
| node             | 14.0.0
| npm              | 6.14.4
| Operating System | Ubuntu 20.04

**Comment by TimothyGu** [comment]
If you try to fetch the document with curl, such as through
```sh
curl -L -v 'https://cite.case.law/pdf/5713742/Blanks%20v.%20West%20Point%20Wholesale%20Grocery%20Co.,%20225%20Ala.%2074,%20142%20So.%2049%20(1932).pdf'
```
you see that the result is an actual HTML page containing some JavaScript code that appears to redirect the user, as well as a `<meta http-equiv=Refresh>` redirect. Node-fetch only handles traditional HTTP 3XX redirects and does not attempt to interpret HTTP responses in any way, so it will not pick up these refreshes. It's up to you to handle these type of redirects yourself.

**Comment by ADrejta** [comment]
Sorry about that.

I thought it was a normal 3xx redirect since i got a status code of 302 from node-fetch when doing the request.
