### ISSUE TITLE
Drop support for Form-Data?

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#1167]
[form-data](https://www.npmjs.com/package/form-data) isn't really spec compatible and it dose some abnormal stuff. I know many other libraries support it. But it increases the complexity to anyone who is building a http library if they decide to support it. They (we) need to learn how it works internally of how it can be read & streamed

I would like to emphasize that it's better to follow the standards instead. Any spec'ed FormData impl shouldn't need any documentation.

There are two other spec compatible FormData packages on npm that works grate on NodeJS
1. There is my own [formdata-polyfill](https://www.npmjs.com/package/formdata-polyfill)
2. And also [formdata-node](https://www.npmjs.com/package/formdata-node)

Both of wish can support appending Blob/Files backed up by the FileSystem (and also blob-like items). Unlike form-data that can only append a one-time readable streams. A FormData should be re-useable if you want to clone the body for whatever reason. (our tests cases could use the same FormData instances - but this dose not work with form-data)

This means that all other http libraries out there needs to serialize the body themself, But fear not, there are packages out there also that can convert them

- My formdata-polyfill have a utility function to convert any spec compatible FormData into a Blob so that can be posted instead `formDataToBlob(formdata)`
- octet-stream have built a [FormData Encoder](https://github.com/octet-stream/form-data-encoder) 
- And we also have a encoder built in now into node-fetch itself to convert any spec compatible FormData.

form-data have had a long time to address the read/modify parts but never got around to implement any those methods. That's b/c it's based on appending all entries directly into a readable stream, so they can't iterated over or modified them.

So my proposal really is to:
1. Stop supporting form-data
2. Throw a error or warning message that form-data is no longer supported and also mention alternative packages
3. Remove all hacks where we utilize  `form.getHeaders(), getBoundary(), getLength(), hasKnownLength()` - A FormData size should always be known/calculated. 

---

So what do you think? I would rather want this to be moved into a discussion but this repo haven't enabled it (and i can't do that)

**Comment by octet-stream** [comment]
By the way, I can send a PR to add support of my encoder instead of current implementation, if you don't mind (once you finish migration to ESM). I'm also planning to propose it to [`got`](https://npmjs.org/package/got), so they'll have support for both `formdata-node` and `formdata-polyfill`.

**Comment by jimmywarting** [comment]
We currently don't need to make a PR that brings in form-data-encoder since we are doing it by ourself already 
This Q is mostly about dropping support for form-data. 

Kind of want to use my formDataToBlob method but we can take it up in a other/later discussion. 
But the ESM would have to be resolved first for that.

**Comment by jespertheend** [comment]
I was just about to use this when I stumbled across this issue. What is the recommended alternative for sending POST requests with form data in the body?

**Comment by jespertheend** [comment]
Ah nevermind, just found out about https://github.com/node-fetch/node-fetch#post-with-form-parameters

**Comment by DaWe35** [comment]
I spent 5 hours trying to get [formdata-node](https://www.npmjs.com/package/formdata-node) work. It was unbelievably hard to switch to it from [form-data](https://www.npmjs.com/package/form-data). I couldn't make it work.

After this nightmare, I ended up using the default (yes, there is one, to my surprise!) `new FormData()`. Above NodeJS 18+, `new FormData()` is a default function, no package required.


```
const formData = new FormData();
    // Append text fields
    formData.append('key', value);

    // Append image files as Blobs
      const filePath = path.join(__dirname, 'file.png');
      const blob = await fileToBlob(filePath);
      const filename = path.basename(filePath);
      // append(name, blob, filename) is the standard way to append a file
      formData.append('image[]', blob, filename);

    ...
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: headers,
            body: formData
        });

    ...
async function fileToBlob(filePath) {
    const buffer = await readFile(filePath);
    const mimeType = filePath.endsWith('.png') ? 'image/png' : 'image/jpeg';
    return new Blob([buffer], { type: mimeType });
}
```

**Comment by octet-stream** [comment]
> After this nightmare, I ended up using the default (yes, there is one, to my surprise!) new FormData().

You will probably surprised, but there's native `fetch()` support in Node.js, so no formdata-node and node-fetch are necessary anymore ;)

Out of curiosity, what problem have you encountered with formdata-node?

**Comment by DaWe35** [comment]
> You will probably surprised, but there's native `fetch()` support in Node.js, so no formdata-node and node-fetch are necessary anymore ;)

I'm actually using the built in fetch, I just didn't know there is a built in FormData.

I think the issue was that the image blob was undefined 🤣😭 It's not my day, I don't really remember tho

**Comment by jimmywarting** [comment]
Its also better to use fs.openAsBlob
