### ISSUE TITLE
Add a verbose mode

### ISSUE THREAD

**Issue by simonppg** [node-fetch/node-fetch#1168]
Not sure if this already exists but I can't find any thing yet.

Is there a way to log what is pass to node-fetch? something like a verbose mode, passing an optional argument for specific calls.

```
const response = await fetch('https://httpbin.org/post', {
	method: 'post',
	body: JSON.stringify(body),
	headers: {'Content-Type': 'application/json'}
},
true <-- verbose mode, this would make node-fetch to console log http method, headers, body, etc.
);
```

sometime we are don't have error in the way we call fetch method, but those are related to the format a 3rd party server needs the data, I think it would be helpful to have this feature.

**Comment by jimmywarting** [comment]
already have some duplicated discussion about logging somewhere (that's still open)
