### ISSUE TITLE
Confused by README about `latest stable` version

### ISSUE THREAD

**Issue by Jolg42** [node-fetch/node-fetch#1184]
The [README](https://github.com/node-fetch/node-fetch/edit/master/README.md) here says

```
## Installation

Current stable release (`3.x`)

npm install node-fetch
```

But npm says `latest` is `2.6.1`, not 3
https://www.npmjs.com/package/node-fetch
<img width="970" alt="Screen Shot 2021-06-07 at 10 02 09" src="https://user-images.githubusercontent.com/1328733/120980985-78673f00-c777-11eb-9ba5-d1ec38ecd84a.png">

So running `npm install node-fetch` will install `2.6.1`, `not 3.x`

**Comment by Richienb** [comment]
The master branch currently contains the documentation for the influx 3.x version of node-fetch. I'll add a link to view the 2.x docs.
