### ISSUE TITLE
Interval between connection and fetch

### ISSUE THREAD

**Issue by KGriss** [node-fetch/node-fetch#1186]
Hello,
I am trying to fetch html from a PHP website but the website show a "Querying Server Data..." text during 0.5s before showing the informations I want to fetch
So I need to put an interval delay between "connection" and fetching data from the website

How can I do this ?

**Example Code**

```js
fetch("https://games.ludosoft.net/sourcebans/index.php", {delay: 500})
	.then((res) => res.text())
	.then((body) => {
		...
	});
```

**Expected behavior, if applicable**

The fetch() call will return the data `delay` (500 here) ms after accessing the website to give him time to load correct data

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.1
| node             | 14.15.3
| npm              | 6.14.9
| Operating System | Windows 10 Family, 20H2, x64

**Additional context/Screenshots**

Here is a GIF of what happen when loading the page
![ Querying Server Data gif](https://i.imgur.com/fJ7mduC.gif)

**Comment by jimmywarting** [comment]
Something like this?

```js
const sleep = t => new Promise(rs => setTimeout(rs, t))

await sleet(500)
const res = await fetch("https://games.ludosoft.net/sourcebans/index.php")
const text = await res.text()
await sleet(500)
```

**Comment by KGriss** [comment]
I got this error

```
d:\Users\Lucas\Documents\Autres\Discord bot\Bot #8061\index.js:257
				await sleet(500)
				^^^^^

SyntaxError: await is only valid in async function
```

**Comment by jimmywarting** [comment]
top level await can be supported in ESM modules.
in package.json you have the option to add `"type": "module"`

or you could use a iif-function 

```js
(async () => {
  await sleep()
})()
```

**Comment by KGriss** [comment]
Oh, ok
I don't have any more errors, but the program still doesn't work, I still have "Querying Server Data..." instead of the correct data
I tried putting sleep(3000) but it doesn't work anyway

**Comment by jimmywarting** [comment]
I see now... you are trying to scrape a website that is populated dynamically with ajax on the https://games.ludosoft.net/sourcebans/index.php page

The fetch api don't execute any javascript. it only upload & download data.

What you need to do is to make the same request they are doing... here is a example request found in the network pannel

eg: 
```js
fetch("https://games.ludosoft.net/sourcebans/index.php", {
  "headers": {
    "accept": "*/*",
    "accept-language": "sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7",
    "cache-control": "no-cache",
    "content-type": "application/x-www-form-urlencoded",
    "pragma": "no-cache"
  },
  "referrer": "https://games.ludosoft.net/sourcebans/index.php?p=servers",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "xajax=ServerHostPlayers&xajaxr=1623241295708&xajaxargs[]=1&xajaxargs[]=servers&xajaxargs[]=&xajaxargs[]=0&xajaxargs[]=-1&xajaxargs[]=&xajaxargs[]=70",
  "method": "POST",
  "mode": "cors"
});
```

**Comment by KGriss** [comment]
Oh yes !

This return a xml response. Do I have to parse the XML to find what I want or is there a way to "apply" the xml to the website data to scrap it ?

**Comment by jimmywarting** [comment]
I don't know. this is beyond our scope. Better ask this kind of question on Stackoverflow
one alternative is to use a headless browser that renders the website with javascript. but that is more tech heavy.

you would need some xml parser

**Comment by KGriss** [comment]
Thank you very much !
