### ISSUE TITLE
How is node-fetch so lightweight?

### ISSUE THREAD

**Issue by RayhanADev** [node-fetch/node-fetch#1190]
Hi there! I use `node-fetch` for all of my projects it's an amazing package! Recently though, one of my projects has been found to need a https package, not http so `node-fetch` subsequently could not be used :(. 

I decided to tackle this problem by making my own package and after getting GET and POST requests done I tried to create my ESM and CommonJS bundles, only to find that my significantly smaller codebase is still leagues greater in size ([lightfetch-node](https://bundlephobia.com/package/lightfetch-node@0.0.8) vs. [node-fetch](https://bundlephobia.com/package/node-fetch@2.6.1)). I am truthfully befuddled by how `node-fetch` is such a lightweight package for all it's codebase. Any tips or tricks you could possibly share? Thanks!

**Comment by jimmywarting** [comment]
if it shows that node-fetch is that small then it's something wrong, maybe is b/c of the browserify version
https://github.com/node-fetch/node-fetch/blob/2.x/browser.js

https://packagephobia.now.sh/ shows a hole different story

fetch uses so many component to be able to be able to work and being spec compatible...
- http
- https
- net
- socket
- http2
- AbortController
- AbortSignal
- Headers
- Request
- Response
- Blob
- FormData (+ de/serialize)
- EventTarget
- whatwg Streams
- node Streams
- URLSearchParams (+ de/serialize)
- URL
- Caching
- http(s) Agants
- De/Compression (deflate, gzip, br, etc)
- handling redirects
- data uri (base64 urls)

If you think for a second that node-fetch is lightweight, than you probably should think again.
If you only deal with one endpoint (rest api) then you could get away with so much less using only nodes https.request

more and more stuff is being implemented by node's core to align with more with the web. so we can shave of some few things here and there sometimes (AbortController for example was among the first to make fetch happening in node's core but for that they needed EventTarget, now we also got blobs)

**Comment by jimmywarting** [comment]
we only have two dependencies 
- "data-uri-to-buffer": "^3.0.1",    
- "fetch-blob": "^2.1.1"

**Comment by RayhanADev** [comment]
@jimmywarting woah yeah that is a completely different story 😅. That is still incredibly lightweight (although yeah, now there is the reasonable difference I expected). Thanks! I think I'll stick with PackagePhobia from now on.

Again, amazing project and good luck!

**Comment by jimmywarting** [comment]
take a look at this video: https://www.youtube.com/watch?v=6EDaayYnw6M&t=1155s
quite interesting
