### ISSUE TITLE
Information on how to prevent blocking?

### ISSUE THREAD

**Issue by goldingdamien** [node-fetch/node-fetch#1191]
I am trying to use node-fetch to fetch for automation purposes.  
In this way, I am trying to use this similarly to how Puppeteer is often used.  
Using node-fetch is simpler for smaller projects, so I would prefer to use it sometimes.

Is there information available on how to prevent blocking, similar to below for Puppeteer?
https://stackoverflow.com/questions/51731848/how-to-avoid-being-detected-as-bot-on-puppeteer-and-phantomjs

Regards.

**Comment by jimmywarting** [comment]
- change the user agant to something that a browser would send
- also include a bunch of unnecessary request header that always get sent, like accept header
