### ISSUE TITLE
Support TLS later versions

### ISSUE THREAD

**Issue by muscleman** [node-fetch/node-fetch#1195]
any plans to implement higher versions of TLS?

`{ FetchError: request to https://explorer.arqma.com/api/networkinfo failed, reason: write EPROTO 28049030244104:error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION:../../third_party/boringssl/src/ssl/tls_record.cc:586:SSL alert number 70`

**Comment by muscleman** [comment]
thats a tls1.3 site

**Comment by tekwiz** [comment]
@muscleman This is a node-version issue.  I believe TLS 1.3 was added in some Node.js 12.  I can confirm that I can fetch this URL successfully in both Node.js 12.17 and 14.15
