### ISSUE TITLE
How can I get errors fields provided by server from response when !response.ok ?

### ISSUE THREAD

**Issue by pfouque06** [node-fetch/node-fetch#1198]
How can I get errors fields provided by server from response when !response.ok ?

I need to get those error messages in order to proceed to specific code when I get status 4xx

### Your Environment

| software       | version
| ------------- | -------
| node-fetch  | 2.6.1
| node            |  14
| yarn             | 2.4.1

Thanks for your help

**Comment by jimmywarting** [comment]
You can still use it as normal
`res.ok` is only a boolean for if status code was 2xx

```js
const res = await fetch(url)
if (res.ok) {
  console.log(await res.json())
} else {
  console.log(await res.text())
}
```

**Comment by pfouque06** [comment]
Thx for your feedback.
I've tried your advice but cannot catch ctx.body from server :

**server code :** 

    const msg = 'Provided date is wrong'
    ctx.body = msg;
    ctx.status = 404;
    return;

**server log :** 

    DEBUG: Provided date is wrong

**client code :** 

    fetchResult = await fetch(url, {
      method: 'post', body: JSON.stringify(request.body), headers: { Authorization: etlInnerToken, 'Content-Type': 'application/json'}
    });
    if (!fetchResult .ok) {
      logger.debug(fetchResult );
      logger.debug(fetchResult .text());
      const error = `[fetch KO] ${fetchResult .status}: ${fetchResult .statusText}`;
      logger.debug(error);
      (....)
    }

**client log :**

    DEBUG:   (size=0, timeout=0)
    DEBUG: 
    DEBUG:  [fetch KO] 404: Not Found

Can you recommand something here to make it operational ?

**Comment by pfouque06** [comment]
Sorry for duplicate issue, I understand but I thought you did not see my comment on previous node after your closed it

**Comment by jimmywarting** [comment]
I get notified.
It seems like there is a problem with how you are dealing with the **server code** (cuz fetch works as intended)
i can't really help you with that little context or no sample url

**Comment by jimmywarting** [comment]
can you even POST anything to the right url endpoint?

are you only accepting a GET request 
```js
app.get('something', function(req, res){
  ...
})
```

**Comment by pfouque06** [comment]
Sorry could not earlier (business priority).
I use as backend a koa library (nodejs / express like) for my REST controller.
In this context, ctx object is the one containing everything I Need to get headers, params, body as well as response status, etc...
My POST url works very well actually for a successfull case (ctx.status = 200 and cts.body contains required json which I can properly fetch with your lib)
Now I am trying to get error details provided by backend because I need to process something.

so actually ctx.body = msg fill up body of response and ctx.status = 404 set the response status, very easy
This works very well for standard angular http client for instance (where I usually provide an errors json object in the body).

Anyway . I found the error in my code and fixed it :

  logger.debug(await fetchResult .text());

Sorry for holding your time and thx for your answers
