### ISSUE TITLE
[follow up] How can I get errors fields provided by server from response when ( ! response.ok ) ?

### ISSUE THREAD

**Issue by pfouque06** [node-fetch/node-fetch#1199]
Thx for your feedback for issue #1198 

I've tried your advice but cannot catch ctx.body from server  :

**server code :**

    const msg = 'Provided date is wrong'
    ctx.body = msg;
    ctx.status = 404;
    return;

**server log :**

    DEBUG: Provided date is wrong

**client code :**

    fetchResult = await fetch(url, {
      method: 'post', body: JSON.stringify(request.body), headers: { Authorization: etlInnerToken, 'Content-Type': 'application/json'}
    });
    if (!fetchResult .ok) {
      logger.debug(fetchResult );
      logger.debug(fetchResult .text());
      const error = `[fetch KO] ${fetchResult.status}: ${fetchResult.statusText}`;
      logger.debug(error);
      (....)
    }

**client log :**

    DEBUG:   (size=0, timeout=0) 
    DEBUG: 
    DEBUG:  [fetch KO] 404: Not Found

**result expected (client side) :** 
`  DEBUG:  Provided date is wrong`

**Environment**

software | version
-- | --
node-fetch | 2.6.1
node | 14
yarn | 2.4.1

Can you recommend something here to make it operational ?

**Comment by jimmywarting** [comment]
Don't open up a new issue

closing as dupl of #1198
