### ISSUE TITLE
[yarn][beta] "engine node is incompatible" error

### ISSUE THREAD

**Issue by Finesse** [node-fetch/node-fetch#1200]
When I install the beta version (3.0.0-beta.9) of node-fetch with Yarn, Yarn returns an error:

```
error fetch-blob@1.0.7: The engine "node" is incompatible with this module. Expected version "^10.17.0". Got "14.15.4"
error Found incompatible module.
```

So I have to force the installation with `--ignore-engines`.

**Reproduction**

1. Install Node.js version 14 (I use v14.15.4)
2. Install Yarn (`sudo npm i -g yarn`)
3. Create an empty folder, open it in a terminal
4. Install node-fetch version 3 beta with Yarn (`yarn add --dev add node-fetch@^3.0.0-beta.9`)

**Expected behavior**

No error because v14 is the current stable version of Node.js.

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.0.0-beta.9
| node             | 14.15.4
| yarn             | 1.22.5
| Operating System | macOS 11.4

**Comment by Richienb** [comment]
Unable to reproduce.

This issue may be caused by an out of date package cache that is downloading a different version of fetch-blob than the one actually specified.

**Comment by Finesse** [comment]
@Richienb I can reproduce it in a blank environment. More exact steps to reproduce:

```bash
mkdir test-project
cd test-project
yarn cache clean
yarn add --dev add node-fetch@^3.0.0-beta.9
```

Output:

```
user@device ~ % mkdir test-project
user@device ~ % cd test-project 
user@device test-project % yarn cache clean
yarn cache v1.22.5
success Cleared cache.
✨  Done in 27.51s.
user@device test-project % yarn add --dev add node-fetch@^3.0.0-beta.9
yarn add v1.22.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning node-fetch@3.0.0-beta.6-exportfix: This release contains some TypeScript definition issues and we therefore recommend to update to the next version. Changelog: https://git.io/JfV1D
warning node-fetch > fetch-blob@1.0.7: This release contains breaking changes, so it has been renamed to 2.0.0. Changelog: https://git.io/JfSDh
[2/4] 🚚  Fetching packages...
error fetch-blob@1.0.7: The engine "node" is incompatible with this module. Expected version "^10.17.0". Got "14.15.4"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by Finesse** [comment]
Same with the latest stable Node.js (v14.17.2)

**Comment by Richienb** [comment]
Try running `yarn init -y` first before running the install command. Also, `yarn add --dev add node-fetch@^3.0.0-beta.9` means you are installing both `node-fetch` and `add` modules.

**Comment by Finesse** [comment]
@Richienb 

> Try running `yarn init -y` first before running the install command.

I get the same result.

> Also, `yarn add --dev add node-fetch@^3.0.0-beta.9` means you are installing both `node-fetch` and `add` modules.

My bad, sorry. I meant installing only `node-fetch`. Removing `add` doesn't change the result too.

<details>
<summary>Input/output</summary>

```
user@device ~ % mkdir test-project
user@device ~ % cd test-project
user@device test-project % yarn init -y
yarn init v1.22.5
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.04s.
user@device test-project % yarn cache clean
yarn cache v1.22.5
success Cleared cache.
✨  Done in 0.07s.
user@device test-project % yarn add --dev node-fetch@^3.0.0-beta.9
yarn add v1.22.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning node-fetch@3.0.0-beta.6-exportfix: This release contains some TypeScript definition issues and we therefore recommend to update to the next version. Changelog: https://git.io/JfV1D
warning node-fetch > fetch-blob@1.0.7: This release contains breaking changes, so it has been renamed to 2.0.0. Changelog: https://git.io/JfSDh
[2/4] 🚚  Fetching packages...
error fetch-blob@1.0.7: The engine "node" is incompatible with this module. Expected version "^10.17.0". Got "14.17.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

</details>

What are your Node.js and Yarn versions?

**Comment by Richienb** [comment]
Just updated - can confirm.

The reason for the issue is because of the caret. It usually declares that the most recent minor version be used but because the development versions don't use semver, npm doesn't understand which version to fetch. Instead, use `yarn add node-fetch@next` or `yarn add node-fetch@3.0.0-beta.9`

**Comment by Finesse** [comment]
It works, thank you

**Comment by LinusU** [comment]
This is fixed in beta.10:

https://github.com/node-fetch/node-fetch/blob/b50fbc105755123cad34fb0bc9d5653ecc693b8a/package.json#L14

**Comment by chakflying** [comment]
unfortunately `"node-fetch": "^3.0.0-beta.10"` would still fetch the wrong version. Sticking to fixed version for now.
