### ISSUE TITLE
Value in method parameters got stringified

### ISSUE THREAD

**Issue by listiani13** [node-fetch/node-fetch#1204]
Thank you for this amazing package! However, I found that every value that is being set to header are stringified. I also notice this is an expected behavior in the [docs](https://github.com/node-fetch/node-fetch/blob/master/docs/v2-UPGRADE-GUIDE.md). 

I use openapi-typescript-codegen that will generate code from given spec & use node-fetch underneath it. Since it's generated, there are cases where it pass `undefined` as value when appending to Header. The problem is the destination server do additional field validation in the back (meaning, if we need to supply uuid, we can't simply supply any string to it), so I always ran into the validation error. Is there any reason why we need to stringify `null` & `undefined`?

**Expected behavior, if applicable**

I'm expecting when I set value of null / undefined for header, the field will always got omitted

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.1
| node             | 14.17.3
| npm              |6.14.13

**Comment by jimmywarting** [comment]
That is how webidl conversion works... try this in the browser devtool `[...new Headers([[null, null], [undefined, undefined]])]`

**Comment by jimmywarting** [comment]
It dose what it's suppose to do...
