### ISSUE TITLE
POST method doesn't work in a Cypress plugin.

### ISSUE THREAD

**Issue by alucardu** [node-fetch/node-fetch#1208]
I have an end point where I do a POST request, if the request has been received a icon will turn green (in this case showing  that the Cypress testing has ran successfully,

**Reproduction**

Add this block to Cypress plugin:

```js
module.exports = (on, config) => {
  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config
  require('cypress-mochawesome-reporter/plugin')(on)

  on('after:run', (results) => {
    fetch('https://status.**.**/api/webhook/cypress-e2e-testing', {
      method: 'POST',
      headers: { Authorization: 'Bearer Hk0WkGZMjckIxpIgSlpSVVe2g2DYibYCKMyV5SBdRYng****' }
    })
      .then(console.log('fetch'))
  })
}
```
**Expected behavior**
Fetch should do a POST request.

https://github.com/node-fetch/node-fetch#simple-post

**Screenshots**
![image](https://user-images.githubusercontent.com/779921/125751590-1020c10f-915d-4431-8aa2-8bd40706917c.png)

When using Postman to do the POST request the end point receives the request and everything works as expected.
But using the fetch method in the code block nothing seems to happen, although the `fetch` in the console log is shown and if I remove the `http` from the url I get an message that fetch only supports http(s) calls, so something is hapenning.

| software         | version
| ---------------- | -------
| node-fetch       |     "node-fetch": "^2.6.1",
| node             |  v12.18.4
| npm              | 6.14.6
| Operating System | W10

"cypress": "7.5.0",

**Comment by jimmywarting** [comment]
Think you should suppose to do: 

```diff
-      .then(console.log('fetch'))
+      .then(res => {
+        console.log(res)
+        res.text().then(console.log)
+      })
```

it's always going to log fetch

**Comment by alucardu** [comment]
@jimmywarting for some reason I'm not getting any logs:

      .then((res) => {
        console.log(res)
        res.text().then(console.log(res))
      })

![image](https://user-images.githubusercontent.com/779921/125972681-34041526-f4cf-4d4d-b3bd-a7bd483bbefb.png)

**Comment by jimmywarting** [comment]
```diff
  .then((res) => {
    console.log(res)
-    res.text().then(console.log(res)) // You are not suppose to write it like this...
+    res.text().then(text => console.log(text))
  })
```

**Comment by alucardu** [comment]
Had to make it async it seems! Works now. Thanks a lot.
