### ISSUE TITLE
Scraping

### ISSUE THREAD

**Issue by SirEpiclyAmazing** [node-fetch/node-fetch#1215]
It is being used for malicious activity (scraping my website)

**Comment by jimmywarting** [comment]
Sad to hear this. But there is nothing we can do about it.
We are not scraping your site. someone else is using our tool.

It's like saying "hey curl/wget is being used for malicious activity"

- Try reverse engineering, look at referrer header, ip address, headers, the data that are being sent and try to see what he is doing.
- block the ip address
- use a API rate limit, captcha, one time nonce tokens
- use robots.txt to forbid spider/crawlers
- use something like cloudflare to filter out malicious ip addresses 

https://datadome.co/bot-management-protection/scraper-crawler-bots-how-to-protect-your-website-against-intensive-scraping/
