### ISSUE TITLE
Support for fetching binary files and passing them to client to create object URLs

### ISSUE THREAD

**Issue by jyotirmoypan** [node-fetch/node-fetch#1228]
Hi Team,

I am trying to create a review feature where in files already uploaded in a remote server are fetched via node.js and the binary data is used to createObjectUrls and used to show the files(images/pdfs) in separate windows. While using node-fetch, if I write the stream to a file in Node.js the file looks good. Below is the code for the same:
```js
      fetch(doc_preview_url, requestOptions)
        .then((response) => {
          const dest = fs.createWriteStream("./test.jpg");
          response.body.pipe(dest);
      });
```
However, since I have to send the binary data to the client I am trying the below code which does send the binary data but its corrupted as I can verify looking at the file size and also the files cannot be previewed in the browser. 

```js
      fetch(doc_preview_url, requestOptions)
        .then((response) => {
          res.setHeader("Content-Type", response.headers.get("content-type"));
          response.buffer().then((buffer) => {
            res.send(response.status).send(buffer);
          });
      });
```
Wanted to know if there is some other way to send binary data to client that is fetched from third party APIs. I am not sure if this is a bug, marking this as a question as of now.

**Comment by jimmywarting** [comment]
Perhaps try doing this on the server:
```js
const response = await fetch(doc_preview_url, requestOptions)
res.setHeader('Content-Type', response.headers.get('content-type'))
res.status(response.statusCode)
response.body.pipe(res)
```

**Comment by jyotirmoypan** [comment]
@jimmywarting 
Thank you for your response. I was able to resolve the issue with this code. 

          const contentType = response.headers.get("content-type");
          response.buffer().then((buffer) => {
            res.setHeader("Content-Type", contentType);
            res.status(200).send(buffer);
          });

I tried with your code and that works as well.

**Comment by jimmywarting** [comment]
using pipe will mean that you can send bytes earlier as it comes in.
using buffer() will require you to buffer everything up in memory (that is less optimal)

**Comment by jyotirmoypan** [comment]
@jimmywarting : makes sense and its indeed faster. thanks.
