### ISSUE TITLE
Not receiving AbortError

### ISSUE THREAD

**Issue by fracalo** [node-fetch/node-fetch#1232]
in the browser fetch implementation (tested on chrome), when the request is aborted you receive an Error "DOMException: The user aborted a request.", while with node-fetch no error is emitted.

```js
import { assert } from "chai"
import fetch from "node-fetch"
import AbortController from "abort-controller";

describe("Use AbortController", function () {
  it(`Should be able to abort a request`, function (done) {
    const url = "http://httpbin.org/ip"
    const ac = new AbortController()

    const { signal } = ac
    const r = fetch(url, { signal })
    setTimeout(() => {
      ac.abort()
    }, 12)

    r.then((x) => { done("should not pass in then block") })
      .catch((e) => {
        assert.equal(e, "AbortError: The user aborted a request")
        console.log("expecting to fail here")
        done()
      })
      .finally(() => {
        console.log("we're getting here")
        done()
      })
  })
})
```

I've also tried the example in the [error handling docs](https://github.com/node-fetch/node-fetch/blob/master/docs/ERROR-HANDLING.md) but no error gets thrown.

| software         | version
| ---------------- | -------
| node-fetch             | 2.6.1
| node                      | 14.15.0
| npm                       | 6.14.8
| Operating System | linux

as `AbortCtrl` I'm using mysticatea/abort-controller, am I supposed to use something else?

**Comment by fracalo** [comment]
Problem fixed, it was a timeout issue with mocha.

**Comment by r-edwards** [comment]
@fracalo Are you able to provide any context for what the timeout issue with mocha was? Trying to validate abort-controller behaviour in some tests similar to this but encountering the same issue.

**Comment by fracalo** [comment]
Basically mocha tests will timeout after a certain time (default is 2s), [docs](https://mochajs.org/#timeouts).

To set it for a single test you just need to add `this.timeout(millis)` inside the __it__ functions (don't use arrow functions because `this` doesn't work if bound lexically).

**Comment by Sleepful** [comment]
for now you have to do something like 
```js
    if (error === "AbortError: The user aborted a request") {}
    ```
