### ISSUE TITLE
Fail to parse the JSON stream by iterate on response.body

### ISSUE THREAD

**Issue by summer-ji-eng** [node-fetch/node-fetch#1239]
Fail to parse the stream json in the sample 'https://httpbin.org/stream/3
**Reproduction**

sample code:
```js
const fetch = require('node-fetch');

async function main() {
  const response = await fetch('https://httpbin.org/stream/3');
  try {
    for await (const chunk of response.body) {
      console.log('----start')
      console.dir(JSON.parse(chunk.toString()));
      console.log('----end')}
  } catch (err) {
    console.error(err.stack);
  }
}

main()
```
The Error `SyntaxError: Unexpected token { in JSON at position 312`

Each chunk is end by `"\n"`, for example
```
'{"url": "https://httpbin.org/stream/3", "args": {}, "headers": {"Host": "httpbin.org", "X-Amzn-Trace-Id": "Root=1-6110767f-318d876e477f329d79db7b40", "Accept": "*/*", "User-Agent": "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)", "Accept-Encoding": "gzip,deflate"}, "origin": "73.223.140.186", "id": 0}\n'
```
**Expected behavior**

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | ^2.6.1
| node             | v14.17.0
| npm              | 7.15.0
| Operating System | MacOS

**Additional context**

**Comment by jimmywarting** [comment]
Streamed json isn't really valid json. and not something that we would support
what you need is probably: https://www.npmjs.com/package/JSONStream or some sort
```js
r=await fetch('https://httpbin.org/stream/3')
r=await r.text()
r=t.split('\n')
r.pop()
r=r.map(r => JSON.parse(r))
```
