### ISSUE TITLE
How to mock navigator.cookieEnabled

### ISSUE THREAD

**Issue by brightchip** [node-fetch/node-fetch#1242]
How do you mock the navigator.cookieEnabled  ? 
Because Cloudflare is checking this to send the Captcha page

``` 
var a = function() {try{return !!window.addEventListener} catch(e) {return !1} },
I20210809-18:28:34.415(8)?       b = function(b, c) {a() ? document.addEventListener("DOMContentLoaded", b, c) : document.attachEvent("onreadystatechange", b)};
I20210809-18:28:34.415(8)?       b(function(){
I20210809-18:28:34.415(8)?         var cookiesEnabled=(navigator.cookieEnabled)? true : false;
I20210809-18:28:34.415(8)?         if(!cookiesEnabled){
I20210809-18:28:34.415(8)?           var q = document.getElementById('no-cookie-warning');q.style.display = 'block';
I20210809-18:28:34.415(8)?         }
I20210809-18:28:34.415(8)?       });
I20210809-18:28:34.416(8)?   //]]>
```

**Comment by jimmywarting** [comment]
```js
globalThis.navigator = globalThis.navigator || {}
navigator.cookieEnabled = true
```

**Comment by brightchip** [comment]
> ```js
> globalThis.navigator = globalThis.navigator || {}
> navigator.cookieEnabled = true
> ```

Please tell me what  is the  `globalThis`

**Comment by jimmywarting** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

**Comment by brightchip** [comment]
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis

Thank you for the explaining .  But the navigator is not set on the fetch request 
`const response = await fetch(url, { } )`
I'd like to modify the navigator of the fetch to bypass Cloudflare page. It doesn't work when I tried to access the url from Node fetch but working fine from Puppeteer

**Comment by jimmywarting** [comment]
NodeJS is nothing like puppeteer that runs in an actual browser
node-fetch use different headers.
if you emulate exactly what the browser would normally send with request headers then you might get around it.
even then they could have some client side validation.
