### ISSUE TITLE
Engines field

### ISSUE THREAD

**Issue by labriola** [node-fetch/node-fetch#1260]
Looks like your latest engines is:

"node": "^12.20.0 || ^14.13.1 || >=16.0.0"

So either you intend to no longer support node 15 or someone made a mistake

**Comment by labriola** [comment]
I think it was accidentally introduced here if it helps:

https://github.com/node-fetch/node-fetch/blob/b50fbc105755123cad34fb0bc9d5653ecc693b8a/package.json#L14

Cheers

**Comment by Richienb** [comment]
Node.js 15 reached end of life 3 months ago.
