### ISSUE TITLE
Version 2.6.1 has incorrect configuration for CJS in package.json

### ISSUE THREAD

**Issue by yinzara** [node-fetch/node-fetch#1269]
As file with `jest-fetch-mock`:
https://github.com/jefflau/jest-fetch-mock/issues/161#issuecomment-911921788

There is a mistake in the "main" entry in the package.json release in 2.6.1 that is causing import errors.

It currently reads:
```
"main": "lib/index",
```

It should be:
```
"main": "lib/index.js",
```

**Comment by jimmywarting** [comment]
Fix on the way: #1274 
kind of finish - just waiting for review (acceptances from 2 team members)
