### ISSUE TITLE
Update or recreate the `2.x` branch

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#1272]
It needs to point to the latest 2.x.x tag (v2.6.1 right now). And we need to add the same semantic-release setup there in order to automate maintenance 2.x releases. Breaking changes are not allowed in the 2.x branch.

**Comment by jimmywarting** [comment]
Couldn't delete & recreate it... it was protected.

**Comment by lubber-de** [comment]
Also v2.6.2 is missing here in the github repo (as release as well as a tag).
However v2.6.2 is available at npm ... confusing and i was wondering if i really should merge out dependabot PR 
https://github.com/fomantic/Fomantic-UI/pull/2094

**Comment by jimmywarting** [comment]
v2.6.2 has a tiny fix that corrects the main path with an extension in the end that went unnoticed for a long time.
It's correct that it got released to npm, have just forgotten to tag it

**Comment by jimmywarting** [comment]
here is the relevant issue: https://github.com/node-fetch/node-fetch/issues/1269 that got fixed in 2.6.2

**Comment by jimmywarting** [comment]
I created a Tag now
