### ISSUE TITLE
Is there a way to get request from response?

### ISSUE THREAD

**Issue by professrr** [node-fetch/node-fetch#1286]
So for example the request is failed. And I want to repeat the request. It will be good to get request info from the response (s.a. Headers, Url, Body, Agent...). In python there is something like `response.request`

**Comment by yo1dog** [comment]
You can easily bundle them yourself.

```javascript
const req = new Request(...);
const res = await fetch(req);

const reqres = {req, res};
//...
if (reqres.res.ok) {
  const req2 = reqres.req.clone();
  const res2 = await fetch(req2);
}
```

**Comment by professrr** [comment]
@yo1dog But if I have more than one request, other than that Promise.all() its getting hard to implement this

**Comment by yo1dog** [comment]
The spec does not define a reference to the originating request: https://developer.mozilla.org/en-US/docs/Web/API/Response

But I see your point.

```typescript
async function fetch2(req: Request) {
  const res = await fetch(req);
  return {req, res};
}

const reqresList = await Promise.all([
  new Request(...),
  new Request(...),
].map(fetch2));
```

**Comment by professrr** [comment]
@yo1dog Yeah Mike, thx
