### ISSUE TITLE
v2: Better UTF-8 URL handling

### ISSUE THREAD

**Issue by jlowcs** [node-fetch/node-fetch#1290]
**Is your feature request related to a problem? Please describe.**

Since v3 is ESM only and your recommendation is to use v2 is ESM if this is blocking for us, could it be possible to port [this improvement](https://github.com/node-fetch/node-fetch/blob/main/docs/v3-UPGRADE-GUIDE.md#better-utf-8-url-handling) to v2?

Indeed, we already had a few instances of a SSR issue in production where the fetched url contained UTF-8 characters and made the fetch fail server-side but not client-side. Those issues are pretty tricky to catch ahead of time if the developer forgets to take UTF-8 into account when building the url.

**Describe the solution you'd like**

Port [the UTF-8 improvement](https://github.com/node-fetch/node-fetch/blob/main/docs/v3-UPGRADE-GUIDE.md#better-utf-8-url-handling) to v2.

**Comment by LinusU** [comment]
1. Do you have an example of an url that is failing that we could use as a test case?
2. Would you be able to submit a PR for this?

**Comment by jlowcs** [comment]
1. Here's a very simple test case:
```
require('node-fetch')('http://www.foo.com/ひらがな')
```
![image](https://user-images.githubusercontent.com/3777724/133255223-1734fe42-c4e8-4355-a032-5f331c602389.png)

2. Well, I would assume that you would have a pretty good idea on how to implement that fix since it was implemented in v3, while it will probably take me more time just because I'm not familiar with the codebase. That being said, if you give me the necessary pointers so I don't spend too much time on this, I suppose I could take care of that PR.

**Comment by LinusU** [comment]
I've submitted a PR for this here: https://github.com/node-fetch/node-fetch/pull/1291
