### ISSUE TITLE
dns.lookup's should be done with `verbatim=true`

### ISSUE THREAD

**Issue by zwhitchcox** [node-fetch/node-fetch#1298]
**Is your feature request related to a problem? Please describe.**

Currently, NodeJS ignores [rfc 6724](https://datatracker.ietf.org/doc/html/rfc6724) which can cause problems when a network drops IPv6 support, which is increasingly common on 4G networks.

**Describe the solution you'd like**

Node should set `verbatim=true` on all requests.

**Describe alternatives you've considered**

This will eventually be the default in Node, but it's better if we can go ahead an implement it, because this is a stupid design decision and causes extremely confusing bugs, while ignoring web standards

**Comment by jimmywarting** [comment]
can you explain/summarise what `verbatim=true` do?

**Comment by zwhitchcox** [comment]
@jimmywarting 

From the [NodeJS docs](https://nodejs.org/dist/latest-v16.x/docs/api/dns.html#dns_dns_setdefaultresultorder_order)

>verbatim <boolean> When true, the Promise is resolved with IPv4 and IPv6 addresses in the order the DNS resolver returned them. When false, IPv4 addresses are placed before IPv6 addresses. Default: currently false (addresses are reordered) but this is expected to change in the not too distant future. Default value is configurable using dns.setDefaultResultOrder() or --dns-result-order. New code should use { verbatim: true }.

So, node actually encourages you to use `verbatim=true`.

Since v16.4.0, you can [set the default result order to `verbatim`](https://nodejs.org/dist/latest-v16.x/docs/api/dns.html#dns_dns_setdefaultresultorder_order), but it's still not the default, and most people probably have no clue why they should do that anyway.

`dns.lookup`, the default dns resolution function resolves addresses using [`getaddrinfo`](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html). This algorithm follows [rfc 6724](https://datatracker.ietf.org/doc/html/rfc6724). For full details, read the document, but basically, it governs the order of the IP addresses in the linked list provided by through a rather complex and sophisticated algorithm.

This really wasn't a big deal for most people, but with IoT devices becoming more and more common, non-smartphone hosts are being more commonly used over cellular networks which can drop IPv4 support sporadically, due to [IPv4 address exhaustion](https://en.wikipedia.org/wiki/IPv4_address_exhaustion).

Mobile developers use high level APIs which make decisions like which IP address to resolve for you, and both iOS and Android follow RFC 6724. They also implement Happy Eyeballs (see #1297), so failover is handled automatically.

So, really, it wasn't that big of a problem now, but with the rise of IoT, NodeJS environments are increasingly being deployed on mobile networks, making this more of a problem.

Particularly in less-developed countries, IPv6-only support is more common, and they may not have the resources to figure out what the problem actually is. I recently discovered a misconfiguration on a major cellular provider in India, which probably caused massive network latency issues and unneccessary failed connections.

**Comment by treysis** [comment]
Verbatim=true is the default starting with Node.js 16.10.0. So not sure if this issue is really important aside from maybe some backwards compatibility for people running it with older Node.js versions.

**Comment by zwhitchcox** [comment]
Yeah, I mean a lot of companies don't use the latest node version, but still, with #1297, this is done anyway, as well as fixing other compatibility issues. I'll close this issue in favor of that one though
