### ISSUE TITLE
Authentication parameters in url does not work on 2.6.3

### ISSUE THREAD

**Issue by Kaspanoombro** [node-fetch/node-fetch#1302]
**Reproduction**

1. node
2. FETCH = require('node-fetch');
3. FETCH("http://admin:p#ass!word@localhost:5984/mydatabase").then(r => {return r.json();}).then(l => {console.log(l);});

**Expected behavior**
Return the response from database but instead i always get access denied. The error does not occur with node-fecth@2.6.2

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.3
| node             | 16.9.1
| npm              | 7.24.0
| Operating System |
Ubuntu 20.04LTS or 16.04LTS

**Comment by jimmywarting** [comment]
dupl of #1301

**Comment by jimmywarting** [comment]
Think we got a fix for it already (#1301)
