### ISSUE TITLE
node-fetch@2.6.4 build error in webpack@4, node-fetch@2.6.2 works fine

### ISSUE THREAD

**Issue by paranoidjk** [node-fetch/node-fetch#1305]
**Reproduction**
- https://unpkg.alipay.com/browse/node-fetch@2.6.4/lib/index.mjs
-  `import { URL } from 'whatwg-url';`  （es module）
-  https://unpkg.alipay.com/browse/whatwg-url@5.0.0/lib/public-api.js  (commonjs, no default export)
-  `ModuleDependencyError: Can't import the named export 'URL' from non EcmaScript module (only default export is available)`

**Expected behavior**

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       |
| node             |
| npm              |
| Operating System |

**Additional context**

**Comment by jimmywarting** [comment]
released 2.6.5
