### ISSUE TITLE
`multipart/form-data` should contain `Content-Length` header for parts if size is known

### ISSUE THREAD

**Issue by AuHau** [node-fetch/node-fetch#1307]
**Is your feature request related to a problem? Please describe.**

Some server applications require to have known `Content-Length` for each part of the multipart request.

**Describe the solution you'd like**

Add `Content-Length` header **in part's headers** if the size is known (for example for `Blob` use the `Blob.size`) in the [`getHeader()`](https://github.com/node-fetch/node-fetch/blob/main/src/utils/form-data.js#L21) function.

**Describe alternatives you've considered**

At the moment I have to use `form-data` package instead of the spec complaint  `FormData` as it has support for this.

**Additional context**

Happy to create patch for this.

Discussion about part's `Content-Length` in multipart request: https://github.com/square/okhttp/issues/2138

**Comment by jimmywarting** [comment]
> Some server applications require to have known `Content-Length` for each part of the multipart request.

The web (and many other http libraries) don't send `Content-Length` for each part. So relying on it would be unwise. But I agree that it's useful to send it (by default).
But right now i'm a little bit on the fence about it.

In my own formdata package (where i serialize the entries) i got a issue regarding this issue: https://github.com/jimmywarting/FormData/issues/116

There is also a spec <s>proposal</s> issue of adding more custom headers into the web specification also: https://github.com/whatwg/fetch/issues/1130 feel free to chime in there

---

If you haven't heard the news yet we are looking into removing suport for the old `form-data` (cuz it don't follow the spec)

My [formdata-to-blob](https://github.com/jimmywarting/FormData/blob/master/formdata-to-blob.js) is compatible to take any spec compatible FormData that is iterable and convert it into a Blob (sync)
a easy modification to it can solve your issue with adding more headers to each part.

there is also @octet-stream spec compatible FormData encoder: https://github.com/octet-stream/form-data-encoder
(don't know if it has support for adding custom headers to each part)

**Comment by Kristrue** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Some server applications require to have known `Content-Length` for each part of the multipart request.
> 
> **Describe the solution you'd like**
> 
> Add `Content-Length` header **in part's headers** if the size is known (for example for `Blob` use the `Blob.size`) in the [`getHeader()`](https://github.com/node-fetch/node-fetch/blob/main/src/utils/form-data.js#L21) function.
> 
> **Describe alternatives you've considered**
> 
> At the moment I have to use `form-data` package instead of the spec complaint  `FormData` as it has support for this.
> 
> **Additional context**
> 
> Happy to create patch for this.
> 
> Discussion about part's `Content-Length` in multipart request: https://github.com/square/okhttp/issues/2138
