### ISSUE TITLE
Keep on par with 2.x tags, releases and npm uploads (2.6.4, 2.6.5 only on npm)

### ISSUE THREAD

**Issue by lubber-de** [node-fetch/node-fetch#1309]
## Description
Please take care of adding tags, create github releases and npm uploads

At the moment v2.6.4 and v2.6.5 are not tagged, are not listed in the releases list but already got an upload at npm.

Because of that, githubs dependabot creates PRs to upgrade from 2.6.3 to 2.6.4 or 2.6.4 to 2.6.5 but cannot clearly distinguish the related commits or changelog history (it always refers to latest commits for 3.0 instead which makes merge decisions on our side difficult, if i cannot figure out what really has changed)

**Comment by jimmywarting** [comment]
@LinusU can you fix this?

**Comment by LinusU** [comment]
Sorry for missing this one! It seems like it is fixed now.

Generally, I think that this is why one shouldn't bump the version in the PR, but instead push a single commit that just bumps the version by using `npm version` directly to the branch when releasing...
