### ISSUE TITLE
TypeError: the object have a 'unknow' type in response.json();

### ISSUE THREAD

**Issue by Zixasis** [node-fetch/node-fetch#1312]
Fetch has the function `res.function()` which is responsible for returning the response as an Object. The problem is that in types the function --- returns a promise with an `unknown` value instead of any value.

The main difference between `any` and` unknow` is that `unknow` you cannot treat it as an object whereas` any` you can treat it ... like anything.

It is no problem. if you work with Javascript, but when you work with Typescript it brings problems (added pictures in spanish)

The solution is simple `json(): Promise<unknown>;` to `json(): Promise<any>;`
https://github.com/node-fetch/node-fetch/blob/8721d79208ad52c44fffb4b5b5cfa13b936022c3/%40types/index.d.ts#L110

Typescript when is `unknow`:

![2021-09-25_00h02_04](https://user-images.githubusercontent.com/29090346/134758977-1d0e574a-ab89-451c-9751-1a4af8c18848.png)

Typescript when is `any`:

![image](https://user-images.githubusercontent.com/29090346/134758991-23cda585-c6da-40ac-87b9-09ea11ec34c6.png)
![image](https://user-images.githubusercontent.com/29090346/134758988-fca569c1-8ac1-41c3-9c32-df5a97797d76.png)

PD: Sorry for my TERRIBLE ENGLISH

**Comment by LinusU** [comment]
The reason for `unknown` is that in your example there is nothing that says that there will be a `token` field on the returned object, or even that the return value will be an object...

This is discussed more in #1262 which would be the right place to continue the discussion ☺️

**Comment by austinoracle8** [comment]
@LinusU https://stackdev.space/questions/how-can-i-retrieve-objects-using-the-json-function
