### ISSUE TITLE
TypeError: Invalid URL

### ISSUE THREAD

**Issue by tyanbiao** [node-fetch/node-fetch#1342]
**Reproduction**

1.  use node-fetch to request url https://r2---sn-n4v7sney.googlevideo.com
2. throw error: `TypeError: Invalid URL`

You can try to reproduce the issue by running the code below

```JavaScript
const fetch = require('node-fetch')

async function getAudio() {
    const ret = await fetch('https://r2---sn-n4v7sney.googlevideo.com')
    const text = await ret.text()
    return text
}

getAudio().catch(e => console.error(e))
```

**Expected behavior**

https://r2---sn-n4v7sney.googlevideo.com is a valid url

**Screenshots**

![temp](https://user-images.githubusercontent.com/19632522/138259790-b7367280-396d-4dc2-ad6f-9bc5b1606f65.png)

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       |  2.6.5 
| node             |  v14.18.1 
| npm              |  6.14.15
| Operating System | Windows 10

**Additional context**

**Comment by jimmywarting** [comment]
could you try 2.6.6 if it works now?

**Comment by tyanbiao** [comment]
> could you try 2.6.6 if it works now?
It works fine in version 2.6.6
