### ISSUE TITLE
Question: node fetch

### ISSUE THREAD

**Issue by Kanna72** [node-fetch/node-fetch#1360]
**Example Code**

```js
```

**Expected behavior, if applicable**

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       |
| node             |
| npm              |
| Operating System |

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by Kanna72** [comment]
Pls slove my node fetch prblms

**Comment by jimmywarting** [comment]
we don't know what your problem is, fill in the details in a new issue

**Comment by dargmuesli** [comment]
And I thought the repos I maintain receive conspicuous issue reports. This one is golden. Keep it up @jimmywarting!
