### ISSUE TITLE
Are there plans to upgrade Fetch Blob to version 3.1.3？

### ISSUE THREAD

**Issue by iakoug** [node-fetch/node-fetch#1370]
There was a "stream/web is an experimental feature" warning in my repo fetch-blob@3.1.3 solved this problem fortunately.
So, are there plans to upgrade Fetch Blob to version 3.1.3？Appreciate!

**Comment by jimmywarting** [comment]
yes

(i wonder why dependabot haven't sent any pr)

**Comment by noodny** [comment]
Hi @jimmywarting 👋  Any chance this can get released as a patch version of `node-fetch`? The error is still present when using `latest` from npm.

**Comment by jimmywarting** [comment]
@noodny release on the way: https://github.com/node-fetch/node-fetch/pull/1451

coming any day now... just need acceptance
