### ISSUE TITLE
Typo in `formdata-polyfill` code in `README.md`.

### ISSUE THREAD

**Issue by HarshKapadia2** [node-fetch/node-fetch#1379]
There is a typo in the 2nd code block of the [Post data using a file](https://github.com/node-fetch/node-fetch#post-data-using-a-file) section in the `README.md` file.

Mistake: `import {FormData} from 'formdata-polyfill/esm-min.js';`
Correction: `import {FormData} from 'formdata-polyfill/esm.min.js';`

**Screenshot**
Mistake 👇 
![image](https://user-images.githubusercontent.com/50140864/141368602-b2241605-78ff-4a58-92f3-577a6fbb14b9.png)

**Comment by jimmywarting** [comment]
ty, will fix it

**Comment by HarshKapadia2** [comment]
Found another typo. 😅 

The Table of Contents entry for the 'Post data using a file' section in `README.md` is incorrect.

Mistake: `[Post data using a file stream](#post-data-using-a-file-stream)`
Correction: `[Post data using a file](#post-data-using-a-file)`

**Screenshot**
Miatske 👇 
![image](https://user-images.githubusercontent.com/50140864/141415618-045ce2a0-dc48-45aa-9375-98aee6a50c5d.png)
