### ISSUE TITLE
alternative package that doesn't require huge refactor?

### ISSUE THREAD

**Issue by dcsan** [node-fetch/node-fetch#1382]
trying to use this package on a typescript project. 
like many others I guess getting the `  code: 'ERR_REQUIRE_ESM'` error 

I read the locked/closed issue here:
https://github.com/node-fetch/node-fetch/issues/1279

So it seems v3 has broken typescript support.
After reading a couple pages of that, it seems a lot of requirements to change my project config just to use this module, and the reasoning/benefits aren't discussed. 

So I'm wondering what other packages will do simple network IO without such requirements?

**Comment by LinusU** [comment]
If you aren't ready to switch to ESM yet you can use version 2.x of this library, which still receives updates.

**Comment by Richienb** [comment]
The problem is never that TypeScript is being used. The problem is that the code that the compiler transforms it into doesn't work either. You need to configure it to output the code as ESM. https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by jimmywarting** [comment]
Sry to hear that.

Request have brought up a bunch of alternatives https://github.com/request/request/issues/3143

There is also:
- https://github.com/nodejs/undici
- https://github.com/feross/simple-get (like this one cuz it's just 100 lines of code)
- and many even smaller fetch version that is just a super thin wrapper around nodes built in http/https with very limited support

also don't be afraid to just use node's http/https directly. Many times you don't actually need a super complicated library that handles posting/parsing bodies and dose a lots of advance stuff like compressing and uncompressing.

---

Anyhow, this is what have worked for some typescript user:

```ts
// this prevents typescript from ever transforming `import` to `require`
const _importDynamic = new Function('modulePath', 'return import(modulePath)')

async function fetch(...args) {
  const {default: fetch} = await _importDynamic('node-fetch'))
  return fetch(...args))
}
```

you can also stay on the 2.x version until you feel ready to go ESM also or until nodejs comes up with a solution to better load esm packages

**Comment by dcsan** [comment]
thanks for the thoughtful replies. Still trying to understand the pros of moving to ESM, and risks like other libraries then complaining... in the end i just used `got` npm module, seems to work fine.

**Comment by jimmywarting** [comment]
`got` really? dose it work for you? it's also built as ESM?

**Comment by jimmywarting** [comment]
ah, the next version will be in ESM, you must be using v11, 
v12 (beta 4) is built as ESM, but it's not released as stable yet.
