### ISSUE TITLE
node-fetch ver 3.1.0 don't work inside ts file

### ISSUE THREAD

**Issue by Ulibka68** [node-fetch/node-fetch#1397]
node-fetch ver 3.1.0 don't work inside ts file

**Reproduction**

package.json :
```
{
  "name": "node-typescript-v1",
  "scripts": {
    "start": "nodemon --exec 'ts-node' src/index.ts localhost 8080"
  },
  "dependencies": {
    "@types/node": "16.11.10",
    "node-fetch": "3.1.0",
    "ts-node": "10.4.0",
    "typescript": "4.5.2"
  },
  "devDependencies": {
    "nodemon": "1.18.4"
  },
  "keywords": []
}
```

tsconfig:
```
{
  "compilerOptions": {
    "outDir": "./dist",
    "allowJs": true,
    "lib": ["esnext"],
    "target": "es5"
  },
  "include": ["./src/**/*"],
  "exclude": ["node_modules", "__tests__"]
}
```

index.ts
```
import fetch from "node-fetch";
async function test() {
  const response = await fetch("https://api.github.com/users/github");
  const data = await response.json();
  console.log(data);
}
(async ()=>{await test();})();
```

Result:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /sandbox/node_modules/node-fetch/src/index.js
```

**Expected behavior**
write result to console

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       |
| node             | 14
| npm              | 6
typescript ver 4.5.2
| Operating System |

**Additional context**

**Comment by msieurtoph** [comment]
I spent the entire day investigating the same issue ;)
My error message was : 

```
Error [ERR_REQUIRE_ESM]: require() of ES Module xxxxx/node_modules/node-fetch/src/index.js from xxxxx/my-personal-file.ts not supported.
```

I rollbacked to version 2.6.6 to fix the issue.

**Comment by jimmywarting** [comment]
it can work in ts, there is a couple of things to make it work
1. first you need to say that it should be of `{"type": "module"}` in package.json 
2. then you need to set the target output to generate esm output and not commonjs.

note that esm requires you to have explicit paths so you need to change stuff like `import './foo'` to `import './foo.js'`

This will be a breaking change for your own package... and you may have to take extra action to fix existing test frameworks etc to work with esm instead.

but there are other easier ways to load esm-only packages in commonjs also that don't require you to refactor your entire codebase... then you have to use dynamic `import('node-fetch')` but need to take extra mercures to not have TypeScript rewriting your import statments to `require('node-fetch')`...

have a look here https://github.com/node-fetch/node-fetch/issues/1279 and at https://github.com/node-fetch/node-fetch/issues/1279#issuecomment-915063354 if you find something that might help

**Comment by jimmywarting** [comment]
also the other option is to stick to v2 until node or typescript comes up with a better way to deal with esm and explicit paths in imports, or switch to vanilla javascript, it's 100% possible to have a type safety with IDE completions without typescript flavorded  syntax with some bit of jsdoc help

**Comment by peabnuts123** [comment]
> it's 100% possible to have a type safety with IDE completions without typescript flavorded syntax with some bit of jsdoc help

Hey bud I don't think you actually know what type-safety is 😅
