### ISSUE TITLE
blob() method shouldn't use buffer() method

### ISSUE THREAD

**Issue by cjh980402** [node-fetch/node-fetch#1401]
body.blob() use body.buffer() inside so I see the this error log even if I didn't use body.buffer().
I think it should be replaced to consumeBody() like other method (body.text(), body.json())
```
[node-fetch#buffer] DeprecationWarning: Please use 'response.arrayBuffer()' instead of 'response.buffer()'
```

**Comment by jimmywarting** [comment]
ironic that we are using it ourself, miss on our part... didn't notice it cuz it only emitted once. and some buffer test maybe runs before calling blob.
should be an easy fix just replacing buffer() with arrayBuffer()
