### ISSUE TITLE
Does not work with any formData implementations

### ISSUE THREAD

**Issue by juliomac** [node-fetch/node-fetch#1404]
I have tried using node-fetch to POST a simple Object JSON to an API without success.

I started using Node-Fetch together with the npm package "form-data". But the response from the API never recognised the value sent through Node-fetch. I have then moved to package "formdata-polyfill/esm.min.js" as suggested by Node-fetch documentation, also without success, and finally tested with package "formdata-node", that also did not work.

The solution was to move away from Node-fetch and use Axios with package "form-data", my original choice.

I have tested appending the JSON to formData in zillions of ways, such as:
```js
formData.append("guest[phone_country_code]","55");
```
OR
```js
const Guest = {
  phone_country_code: "55",
  country_id: null,
};
formData.append("Guest", JSON.stringify(Guest));
```
OR
```js
formData.append("guest", "{\"phone_country_code\":55,\"country_id\":null}");
```

I am running a Meteor.js version 2.3 server application with its pre-installed Node-Fetch package.

**Comment by jimmywarting** [comment]
Do you have any public GitHub repo and do you use version 2 or 3?

**Comment by juliomac** [comment]
Have been preparing a GitHub repo in order to show you the issue and found a problem in my own code.

I have made it to work with form-data package. Will test again with the other packages and post it back here. 

You may close this issue for now.
