### ISSUE TITLE
ReferenceError: exports is not defined.

### ISSUE THREAD

**Issue by albertost5** [node-fetch/node-fetch#1406]
Hello,

I'm trying to use the .fetch method but it's not working fine for me.

This is my tsconfig:

![image](https://user-images.githubusercontent.com/48953066/144763412-9acc7fd2-0aca-4987-86dc-f39eaf178563.png)

This is my server.ts: 

![image](https://user-images.githubusercontent.com/48953066/144763431-706cab6a-a827-4b3b-a585-4ec521282355.png)

After running the server.js this is the error that I'm getting:
![image](https://user-images.githubusercontent.com/48953066/144763450-b97d553e-1337-4aec-bd6f-8207ab9a9e22.png)

I saw in stackoverflow to resolve this, add "type":"module" to the package.json but if I do that I have a different error:

![image](https://user-images.githubusercontent.com/48953066/144763485-1aeeaeb4-da57-4fec-92e9-24854de08036.png)

Can someone explain why I'm getting those errors? What should I do to be able to use the fetch? I've been trying to resolve this problem like two days... really annoying...

**Comment by jimmywarting** [comment]
Hi @albertost5 👋 

node-fetch@3 is built as a esm-only, this means you can no longer use `require` to load node-fetch...
I know it looks like you are using import syntax... but you tsconfig is configured to output commonjs when set to module: commonjs
Meaning: It downgrades your import to require (commonjs) syntax...

When your package is configured to be of type module `"type":"module"` in the package.json then you also need to compile to newer syntax such as `import`, you can do this by setting  `"module": "ES2020"` in your tsconfig.json.

This might get more problematic for some, specially typescript users and the introduction of compiler and test framework that are not production ready to handle esm-only modules... So some ppl stay with commonjs and use older version, node-fetch@2 is still written in commonjs and will continue to get bug and security fixes, but not so much new features. 

There are also async methods to load esm-only modules from commonjs

you can read more here https://github.com/node-fetch/node-fetch/issues/1279#issuecomment-915062146

from the look of you simple server you don't use any typescript syntax... perhaps [you might not need typescript](https://jimmywarting.github.io/you-might-not-need-typescript/)
