### ISSUE TITLE
async import('node-fetch') with v3.1.0 breaks in vite build for sveltejs

### ISSUE THREAD

**Issue by krry** [node-fetch/node-fetch#1408]
Building a Svelte Kit app with Vite, and using the latest v3.1.0 of node-fetch, I receive this error:

```sh
[vite-plugin-svelte] ENOENT: no such file or directory, open 'node:http/package.json'
> ENOENT: no such file or directory, open 'node:http/package.json'
Error: ENOENT: no such file or directory, open 'node:http/package.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at resolveViaPackageJsonSvelte (…vite@2.6.14/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1148:39)
```

I have attempted the async ESM import as suggested in the pinned issue here.  Here is my attempt:

```typescript
	const fetch =
		typeof window !== 'undefined'
			? window.fetch
			: await import('node-fetch').then(mod => mod.default);
```

**Reproduction**

```sh
# 1. Build a new Svelte Kit app with Vite:
npm init svelte@next my-app # choose `skeleton app`, then say no to all prompts
# 2. 
cd my-app && npm i node-fetch
# 3.
touch src/routes/api.js && echo "async function send() {const fetch=await import('node-fetch').then(m => m.default);}" >> src/routes/api.js
# 4.
npm run build
```

**Expected behavior**

When I revert to 3.0.0, the app builds fine.

**Screenshots**

**Your Environment**

```sh
ϕ 00:36:32 ⚭ $ npx envinfo --system --binaries --browsers --npmPackages "{node-fetch,svelte,@sveltejs/*,vite}"

  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 107.44 MB / 16.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - ~/.asdf/shims/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Chrome Canary: 98.0.4751.0
    Firefox: 92.0.1
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3 
    @sveltejs/kit: next => 1.0.0-next.201 
    node-fetch: ^3.1.0 => 3.1.0 
    svelte: ^3.44.0 => 3.44.2 
```
**Additional context**

Many thanks for your labors and attentions!

**Comment by LinusU** [comment]
Hmm, I'm not too familiar with Svelte or Vite. It seems like Vite is for frontend, is the thing that you are building intended to run on Node.js?

From searching around a bit, it seems like this PR that was merged 10 days ago might fix the problem? https://github.com/vitejs/vite/pull/5827

It seems like this went out in the `2.7.0-beta.9` version, could you try that and see if it fixes it?

**Comment by jimmywarting** [comment]
if v3.0.0 works but 3.1.0 don't then i suspect it might be b/c of the `node:` prefix/protocol we added and that PR seems to fix it.

**Comment by ximus** [comment]
for those still scratching their heads:

> Core modules can also be identified using the node: prefix, in which case it bypasses the require cache. For instance, require('node:http') will always return the built in HTTP module, even if there is require.cache entry by that name.

- https://nodejs.org/api/modules.html

**Comment by krry** [comment]
Ah, much thanks for excavating this issue. Glad to see Vite is on it too

**Comment by LinusU** [comment]
@krry did you try the 2.7.0 beta of Vite? Did it work? ☺️

**Comment by krry** [comment]
> @krry did you try the 2.7.0 beta of Vite? Did it work? ☺️ 

Yes, like a charm.
