### ISSUE TITLE
Error when sending response.body using formdata-node

### ISSUE THREAD

**Issue by lynxtaa** [node-fetch/node-fetch#1413]
Using node-fetch@3.1.0 and formdata-node@4.3.1 I'm trying to send a body as stream and getting an error:
```
node:internal/buffer:959
    super(bufferOrLength, byteOffset, length);
    ^

TypeError: Cannot perform Construct on a detached ArrayBuffer
    at new Uint8Array (<anonymous>)
    at new FastBuffer (node:internal/buffer:959:5)
    at Buffer.slice (node:buffer:1120:10)
    at Socket.<anonymous> (file:///home/alexk/code/node_modules/node-fetch/src/index.js:331:35)
```

**Reproduction**

Run this code and see the error
```ts
import { FormData } from 'formdata-node'
import { createServer } from 'http'
import fetch from 'node-fetch'

class BlobFromStream {
	#stream

	constructor(stream, size) {
		this.#stream = stream
		this.size = size
	}

	stream() {
		return this.#stream
	}

	get [Symbol.toStringTag]() {
		return 'Blob'
	}
}

createServer((req, res) => {
	res.end(Buffer.alloc(64 * 1024, '_'))
}).listen(3000)

const response = await fetch('http://localhost:3000')
const form = new FormData()

const contentLength = Number(response.headers.get('Content-Length'))

form.append(
	'file',
	new BlobFromStream(response.body, Number(contentLength)),
	`index.html`,
)

await fetch('http://localhost:3000', {
	method: 'POST',
	body: form,
})
process.exit(0)
```

**Expected behavior**

I expect it to work as intended. It works OK, when I use `form-data` package. Am I missing something?

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.1.0
| node             | 16.13.1
| npm              | 8.1.2
| Operating System | WSL

**Additional context**

**Comment by jimmywarting** [comment]
didn't give me any error:

https://stackblitz.com/edit/node-b8hpn5?file=index.js

---

i think that the "detached ArrayBuffer" means it can't read a stream which have already been consumed 
like as if it have been read twice or something.

**Comment by lynxtaa** [comment]
@jimmywarting I've accidentally tested with node-fetch@ in Windows. Running code above from Windows with node-fetch@3 gives me the same error. Sorry for the confusion

**Comment by lynxtaa** [comment]
Adding `setTimeout(0)`  after getting a response solves the issue for me

```ts
import { FormData } from 'formdata-node'
import { createServer } from 'http'
import fetch from 'node-fetch'
import { setTimeout } from 'timers/promises'

const payloadSize = 64 * 1024

class BlobFromStream {
	#stream

	constructor(stream, size) {
		this.#stream = stream
		this.size = size
	}

	stream() {
		return this.#stream
	}

	get [Symbol.toStringTag]() {
		return 'Blob'
	}
}

createServer((req, res) => {
	res.end(Buffer.alloc(payloadSize, '_'))
}).listen(3000)

const response = await fetch('http://localhost:3000')

// Adding this line solves the issue for me
await setTimeout(0) 

const form = new FormData()

form.append('file', new BlobFromStream(response.body, payloadSize), `index.html`)

await fetch('http://localhost:3000', { method: 'POST', body: form })
process.exit(0)
```

**Comment by jimmywarting** [comment]
must have something to do with how node allocates memory

**Comment by lynxtaa** [comment]
@jimmywarting But adding timeout is unreliable. For example, when running NodeJS in Docker I still have this issue even with `setTimeout(0)`. I've tested it with another FormData implementations and undici:

|  lib  | FormData impl.  | result |
| ----------- | ----------- | -|
| node-fetch@3.1.0 |formdata-node      | ❌       | 
| node-fetch@3.1.0 |formdata-polyfill   | ❌        |
| node-fetch@3.1.0 | form-data | ✔️    |
| undici/fetch | formdata-node | ✔️|

@octet-stream Maybe I'm using `formdata-node` wrong?

**Comment by octet-stream** [comment]
As far as I can tell this usage example with stream body is correct. Not sure what is happening in your environment though.

----

On my machine the first request returns the 400 error for some reason.
