### ISSUE TITLE
Changing the banner

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#1415]
I would like to spread a message 

- That vaccination is optional and it's your own choice if you want to take the vaccine or not.
- A vaccine should not have to be something that should be mandatory.
- You should not have to get a fine for it if you don't have a vaccine passport or if you are unvaccinated.
- One shouldn't have to lose your own job for being unvaccinated.
- One shouldn't be rejected a job for not being unvaccinated.
- You shouldn't be restricted to visit places if you don't have a passport.
- And you shouldn't go and have to take a PCR test everytime you go to the store.

it's you own personal matter, and you should not have to share medical information of it either.

Something we should keep doing is keeping distances, wear mask, clean our hands, limit number of ppl at certain places, recommend people to take vaccine and so forth.

A covid or vaccin passport or so called green pass only bring bad things with it... it divide us,  people gathers and start to demonstrate.

So I would like to change the banner to be something in lines of: "Say NO to vaccin passport"

---

Note: this has nothing to do with weather or not vaccin is good or bad... it's just solo about the freedom

**Comment by jimmywarting** [comment]
yea, we do have a banner: https://github.com/node-fetch/node-fetch/tree/main/docs/media named banner.svg (used in the readme)

**Comment by bitinn** [comment]
We don’t have a banner for social message though, even though I can understand the aversion of mandate or passport, I cannot support such message.

**Comment by jimmywarting** [comment]
> Not sure why node-fetch needs to take a stand on this.

in my country they just started with the vaccin passport for public gatherings and public events this month. it resulted in that a friend of mine couldn't come to an event that we have planed long before.
it goes against some fundamental ground rules that you can't demand that ppl takes a medicine and/or restrict people's freedom of movement. it's discrimination.

I just want to remind ppl of this. The direction we are heading towards is wrong IMO. 

with a message like this on node-fetch then we could reach out to many... big corporations is censoring things left and right that spread false information about covid.

**Comment by cwchristerw** [comment]
I fully understand @jimmywarting and I agree with every point made in list in first message.

In my country Finland, there was no significant restrictions (for poor students like me) until covid pass was ready. Then goverment decided to introduce more restrictions to make it necessary to use covid pass. When there is no restrictions, its not allowed to require covid pass in Finland if I remember correctly.

Although I agree its important to say these stance, its political messaging and I'm not sure if its good for the node-fetch community to take a stand on either side of this argument.

**Comment by LinusU** [comment]
> Not sure why node-fetch needs to take a stand on this. Also “changing” implies we have a banner?

> We don’t have a banner for social message though, even though I can understand the aversion of mandate or passport, I cannot support such message.

This is how I feel as well

**Comment by jimmywarting** [comment]
ok, lets delete this issue
