### ISSUE TITLE
SSL through a custom port

### ISSUE THREAD

**Issue by gask** [node-fetch/node-fetch#1419]
Hi there, I've read different issues here and I think I have a different problem here.
I don't have any self signed certificate, I'm trying to make a connection to a third party that has his SSL connection in other port than 443. 

When I try making a connection to his endpoint using https://hisdomain.com:hisport/his-endpoint I'm getting the "unable to verify the first certificate"

I read the posts that says about using a custom agent and tried creating a custom agent and passing it to the agent parameter in options but it's giving me the same error.
Can you help me how to solve this?

The third-party is playing hardball with me not wanting to go to the pattern of the standard SSL port (443)...

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       |   2.6.1
| node             | 12.13.0
| npm              | 6.14.4
| Operating System | amazon AMI (linux)

___

<div align=center>
<b>Don't post comments like: +1, Same here</b><br>They don't help, they spam and will only be removed<br>Press the subscribe button instead if that is what you want<br>vote with reactions</p>

**Comment by ArthurSN57** [comment]
Up

**Comment by pedroh2604** [comment]
same issue here

**Comment by alefemmanuel** [comment]
I'm also having this issue

**Comment by IsabelaEtt** [comment]
I'm having the same issue here

**Comment by gtretow** [comment]
same here

**Comment by jimmywarting** [comment]
Stop we get it... it's a problem
you don't have to spam it and say "yea same here"
it don't help the issue in any way

**Comment by jimmywarting** [comment]
Do you have any example code?
what have you tried so far?

Maybe this could help?
```js
import { Agent } from 'node:https'
import fetch from 'node-fetch'

const agent = new Agent({ rejectUnauthorized: false })

fetch(url, { agent })
```

**Comment by gask** [comment]
That did it @jimmywarting ! Thank you so much for this. It's not clear in node.js docs that this is an option available to the constructors of Agent instances!

**Comment by fukemy** [comment]
hi, does `rejectUnauthorized` can cause any problem on production?
