### ISSUE TITLE
Unhandled 'error' event when using AbortSignal to cancel requests with a body

### ISSUE THREAD

**Issue by morrisrob** [node-fetch/node-fetch#1420]
Node: 12.21.0
Node-fetch: 3.1.0
Node-abort-controller: 3.0.1

When using an AbortSignal to cancel a 'post' request with a body, node is crashing with an 'Unhandled 'error' event.'  If I remove the 'body' everything works as expected and I can catch the AbortError without any issues.  

**Here is a stripped down example of the code I'm using:**

---------------------------------------------------------
```js
const controller = new AbortController();

const fetchTimeout = setTimeout(() => {
    controller.abort();
}, 500);

const requestOptions = {
    method: 'POST',
    headers: {
      'content-type': 'application/json'
    },
    body: JSON.stringify({test: 'test'}),
    signal: controller.signal
};

try {
    const response = await fetch(url, requestOptions)
} catch (err) {
    // handle error
}
```
----------------------------------------------------------

**Here is a stacktrace of the error:**

events.js:291
throw er; // Unhandled 'error' event
^
AbortError: The operation was aborted.
at abort (/../../../node_modules/node-fetch/src/index.js?:80:18)
at EventEmitter.abortAndFinalize (/../../../node_modules/node-fetch/src/index.js?:99:4)
at EventEmitter.emit (events.js:314:20)
at AbortSignal.dispatchEvent (/../../../node_modules/node-abort-controller/index.js?:27:23)
at AbortController.abort (/../../../node_modules/node-abort-controller/index.js?:38:17)
at Timeout.eval [as _onTimeout] (/./src/testing/api/test.ts?:53:20)
at listOnTimeout (internal/timers.js:554:17)
at processTimers (internal/timers.js:497:7)
Emitted 'error' event on Readable instance at:
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21) {
type: 'aborted'

**Comment by NoUJoe** [comment]
You're missing a `try-catch`, the last line should be

try
{
const response = await fetch(url, requestOptions)
}
catch (error)
{
//handle error here
}

**Comment by morrisrob** [comment]
> You're missing a `try-catch`, the last line should be
> 
> ```js
> try
> {
>     const response = await fetch(url, requestOptions)
> }
> catch (error)
> {
>     //handle error here
> }
> ```

I guess I abbreviated and cut out too much code when posting an example here.  I do indeed have a try / catch and I'm still crashing node when making a post request with a 'body' and aborting the request with AbortSignal.  I went ahead and updated my original post to include this try / catch.  I appreciate your response to this.

**Comment by jimmywarting** [comment]
Umh... sry but i was not able to reproduce it with either v3.1.1 or v3.1.0

This only logs true:
```js
const controller = new AbortController();

setTimeout(() => {
  controller.abort();
}, 500);
const url = 'https://httpbin.org/post';
const requestOptions = {
    method: 'POST',
    headers: {
      'content-type': 'application/json'
    },
    body: JSON.stringify({test: 'test'}),
    signal: controller.signal
};

;(async () => {
  try {
      const response = await fetch(url, requestOptions)
  } catch (err) {
    // handle error
    console.log(err instanceof Error) // true
  }
})();
```

**Comment by morrisrob** [comment]
> Umh... sry but i was not able to reproduce it with either v3.1.1 or v3.1.0
> 
> This only logs true // The operation was aborted:
> 
> ```js
> import('node-fetch').then(async mod => {
>   const fetch = mod.default;
>   const controller = new AbortController();
> 
>   setTimeout(() => {
>     controller.abort();
>   }, 500);
>   const url = 'https://httpbin.org/post';
>   const requestOptions = {
>       method: 'POST',
>       headers: {
>         'content-type': 'application/json'
>       },
>       body: JSON.stringify({test: 'test'}),
>       signal: controller.signal
>   };
> 
>   try {
>       const response = await fetch(url, requestOptions)
>   } catch (err) {
>     // handle error
>     console.log(err instanceof Error) // true
>     console.log(err.message) // The operation was aborted.
>   }
> })
> ```

I just tested with v3.1.1 and confirmed that I could no longer reproduce the issue. I went back to v3.1.0 and confirmed that I still could reproduce.  Perhaps an issue with v3.1.0 and the version of node I'm using (12.21.0) ?  Either way, looks like I'm good here.  I appreciate your help.  Thank you.
