### ISSUE TITLE
clarify : how to pass arguments to new Headers.append  .set

### ISSUE THREAD

**Issue by tst32** [node-fetch/node-fetch#1426]
i want to construct headers for fetch (v3.1) all goes well if i pass an obj {'key':'value'} but not if i do from a  variable 
**Example Code**

```js
import {Headers} from 'node-fetch';
const headers = new Headers()
const headers_default=['referer:somesite.com', 'key1:value1']
headers.append(headers_defaults)
```

**Expected behavior, if applicable**
how to get headers as {'referer':'somesite.com'  }?

what i miss?
###  Environment

| software         | version
| ---------------- | -------
| node-fetch       | 3.1
| node             |  14.1
| npm              | 8.1
| Operating System | ubuntu

**Comment by jimmywarting** [comment]
headers takes either a 2D array or an object, not a flat array...
```js
new Headers([
  ['referer:somesite.com', 'key1:value1'],
  ['content-type': 'text/plain']
])
```
