### ISSUE TITLE
Breaking type annotation in patch release

### ISSUE THREAD

**Issue by KnorpelSenf** [node-fetch/node-fetch#1430]
You released version 2.6.6 which introduces breaking changes. Please revert them. Existing compiling code was broken.

**Reproduction**

Compile
```ts
    const { body } = await fetch(url);
    for await (const chunk of body) {}
```
under 2.6.5 and under 2.6.6.

**Expected behavior**

This library is following semver.

**Actual behavior**

This library is doing breaking changes in patch releases.

```
error TS2531: Object is possibly 'null'.

        for await (const chunk of body) {
                                  ~~~~
```

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.5 and 2.6.6 |
| deno2node | 1.1.0 |
| typescript | 4.5.2 |
| node             | 17.3.0 |
| npm              | 8.3.0 |
| Operating System | Debian 11 |

**Comment by KnorpelSenf** [comment]
There are more issues. What happened here???

```ts
error TS2504: Type 'ReadableStream<Uint8Array>' must have a '[Symbol.asyncIterator]()' method that returns an async iterator.

        for await (const chunk of body) {}
                                  ~~~~
```

You also dropped support for URL objects? Is this an accident?

```ts
error TS2345: Argument of type 'URL' is not assignable to parameter of type 'RequestInfo'.
  Type 'URL' is not assignable to type 'string'.

    fetch(new URL(""));
          ~~~~~~~~~~~
```

**Comment by KnorpelSenf** [comment]
It rather seems to be related to a TypeScript update. I'm no longer sure this is to be fixed here. Closing for now.

**Comment by Maxim-Mazurok** [comment]
> You also dropped support for URL objects? Is this an accident?
> 
> ```
> error TS2345: Argument of type 'URL' is not assignable to parameter of type 'RequestInfo'.
>   Type 'URL' is not assignable to type 'string'.
> 
>     fetch(new URL(""));
>           ~~~~~~~~~~~
> ```

Did you find a solution to that? Or perhaps there's another opened issue?

**Comment by KnorpelSenf** [comment]
I remember this being unrelated to node-fetch, but I cannot recall the context in which the issue arose, nor do I remember my solution. Can you reproduce this bug exactly as described above? If so, I'm open to reopening this issue, even though it technically wasn't valid originally :D

**Comment by Maxim-Mazurok** [comment]
I see, thank you, I can reproduce it, but there's an issue already that tracks this: https://github.com/node-fetch/node-fetch/issues/1261
Thanks for your reply!
