### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [node-fetch/node-fetch#1443]
Hey there!

I belong to an open source security research community, and a member (@ranjit-git) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jimmywarting** [comment]
contact jimmy@warting.se

**Comment by JamieSlome** [comment]
@jimmywarting - thanks for the heads up!

If you would prefer, you can view the report directly here:

https://huntr.dev/bounties/d26ab655-38d6-48b3-be15-f9ad6b6ae6f7/

It is private and only accessible to maintainers with repository write permissions.

**Comment by JamieSlome** [comment]
@jimmywarting - if possible, could you kindly update the status of the report to valid/invalid?

This will make sure the researcher gets rewarded for their work, and you can also bag a bounty yourself for fixing it ❤️

**Comment by ranjit-git** [comment]
As the bug is fixed plz Mark the report as valid

**Comment by ranjit-git** [comment]
Ops sorry @JamieSlome 
I did not see you commented

**Comment by jimmywarting** [comment]
Reported it as valid, and fixed in a PR will be released soon i hope: see #1451 
needs one member to accept it first

**Comment by JamieSlome** [comment]
@jimmywarting - thanks for the support here!
