### ISSUE TITLE
v2.6.7 is reporting a high severity vulnerability

### ISSUE THREAD

**Issue by mantorok1** [node-fetch/node-fetch#1467]
According to the v2.6.7 release notes it should fix a security issue but when installing that version npm is reporting that it contains a high severity vulnerability. Is there a way I can overcome this? Note that I can't upgrade to v3.x.x due to its breaking changes.

$ npm install node-fetch@2.6.7

added 3 packages, removed 5 packages, changed 1 package, and audited 351 packages in 4s

80 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.7
| node             | 16.13.1
| npm              | 8.1.2
| Operating System | macOS 11.6

**Comment by Pyrolistical** [comment]
Looks like a github needs to update the cve https://github.com/node-fetch/node-fetch/pull/1453#issuecomment-1019285891

**Comment by jimmywarting** [comment]
2.6.7 is patched and safe from the attack
