### ISSUE TITLE
Apply security patch fix for v2.6

### ISSUE THREAD

**Issue by justinmchase** [node-fetch/node-fetch#1493]
Version 3.1.1 had a security fix applied:
https://github.com/node-fetch/node-fetch/pull/1449

In that fix this comment appeared:

> Should patch v2 also (not many can update to esm)

Which is indeed the case for some dependees (https://github.com/apollographql/apollo-server/issues/6065).

This issue is specifically to request that the same security issue be patch fixed for `v2.6`.

**Comment by jimmywarting** [comment]
2x have been patched
