### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'body') after update from 3.2.4 to 3.2.5 on 302 status code

### ISSUE THREAD

**Issue by PanSzelescik** [node-fetch/node-fetch#1574]
**Reproduction**

```js
import fetch from 'node-fetch';

fetch('URL which returns 302 code')
    .then((response) => response.text())
    .then(console.log)
    .catch(console.error);
```
```
file:///C:/Git/monitoring_bot/node_modules/node-fetch/src/index.js:113
                        response.body.destroy(error);
                                 ^

TypeError: Cannot read properties of null (reading 'body')
    at file:///C:/Git/monitoring_bot/node_modules/node-fetch/src/index.js:113:13
    at TLSSocket.onSocketClose (file:///C:/Git/monitoring_bot/node_modules/node-fetch/src/index.js:386:5)
    at TLSSocket.emit (node:events:539:35)
    at node:net:715:12
    at TCP.done (node:_tls_wrap:582:7)

Node.js v17.9.0
```

**Expected behavior**

Don't throw error, follow redirect and print response.text()

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.2.5
| node             | 17.9.0
| npm              | 8.5.0
| Operating System | windows and linux

**Additional context**

Problem exists after update to 3.2.5, on 3.2.4 example code doesn't throw error

**Comment by ProgrammingNerdGit** [comment]
yep, having the same issue here.

do you know the latest release that doesn't have this issue?

**Comment by PanSzelescik** [comment]
3.2.5 version is the same as https://github.com/node-fetch/node-fetch/commit/a92b5d5cf4457c2da95d8404b08cfd06a426a2fa and version from GitHub also throws error

**Comment by Lucabenj** [comment]
> 3.2.5 version is the same as [a92b5d5](https://github.com/node-fetch/node-fetch/commit/a92b5d5cf4457c2da95d8404b08cfd06a426a2fa) and version from GitHub also throws error

The same

**Comment by jimmywarting** [comment]
#1578 was just released, could you try the newest version?

**Comment by Lucabenj** [comment]
Just 4 hours of crawling with 2,000 smiultaneous connections and it is ok. It seems as stable as version 3.2.1

**Comment by jimmywarting** [comment]
good, closing this then
