### ISSUE TITLE
Error "SyntaxError: Cannot use import statement outside a module" when using node-fetch in Jest with Typescript

### ISSUE THREAD

**Issue by roblframpton** [node-fetch/node-fetch#1588]
I am trying to write an integration test in Typescript with Jest which uses node-fetch, like this:

```
import fetch from 'node-fetch';

test('Hello', async () => {
    await fetch("http://www.google.com");
});
```

But I am getting the following error:

    Jest encountered an unexpected token

    [...]
    
    Details:

    /home/xxx/node_modules/node-fetch/src/index.js:9
    import http from 'node:http';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import fetch from 'node-fetch';
        | ^
      2 |
      3 | test('Hello', async () => {
      4 |     await fetch("http://www.google.com");

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (temp.test.ts:1:1)

I believe this is specifically a problem with `node-fetch` because it **only** affects imports from this package.  For example, I can do `import express from 'express'` without any difficulty.

**Reproduction**

1. Run the following:

```
npm init
npm install --save-dev jest typescript ts-jest @types/jest node-fetch @types/node-fetch
npx ts-jest config:init
```

2. Create the file `temp.test.ts`:

```
import fetch from 'node-fetch';

test('Hello', async () => {
    await fetch("http://www.google.com");
});
```

3. Run `npx jest`

**Expected behavior**

The test calls fetch

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.2.6
| node             | v16.0.0
| npm              | 8.5.5
| jest             | 28.1.1
| Operating System | Windows 10 x64

**Comment by roblframpton** [comment]
I solved this - it was not an issue with node-fetch, apoligies.  See [here](https://stackoverflow.com/questions/72706090/error-syntaxerror-cannot-use-import-statement-outside-a-module-when-using-nod?noredirect=1#comment128426614_72706090) if you need the solution.

**Comment by corderop** [comment]
I don't think this has been resolved. It's still happening to me. I don't think the solution is to downgrade the library to the 2.x version.

We will need to upgrade at any moment, which will continue to fail. Is there any solution to get this working with 3.x version?

**Comment by jimmywarting** [comment]
An alternative method is switching to using NodeJS v18 \w built in fetch, FormData, and the rest. it's more spec compliant using web streams instead.

**Comment by corderop** [comment]
@jimmywarting I didn't know that Node v18 comes with built-in fetch. I will consider switching instead of trying to migrate to the 3.x version. 

However, thanks to your fantastic effort with this library. It helped me solve particular problems I was facing with other libraries.

**Comment by Plausiblebowhead26** [comment]
After a thorough search, I found the answer to my question



https://nodeer.space/questions/typescript-when-using-ts-node-dev-an-error-occurred-while-trying-to-import-express-due-to-an-unexpected
