### ISSUE TITLE
node-fetch hangs indefinitely on fetch

### ISSUE THREAD

**Issue by mohd-akram** [node-fetch/node-fetch#1589]
A request to a certain URL hangs indefinitely.

**Reproduction**

1.  `await fetch('https://uae.voxcinemas.com')`

**Expected behavior**

The request completes successfully.

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.2.6
| node             | 18.4.0
| npm              |  8.12.2
| Operating System | macOS

**Comment by mohd-akram** [comment]
This issue does not seem to happen with node-fetch v2.

**Comment by mohd-akram** [comment]
This did not happen with node-fetch v2 because it had a different user agent, and this server seems to hang forever when using HTTP/1.1 combined with a user agent it doesn't like (`curl -A "" --http1.1 'https://uae.voxcinemas.com'`).

**Comment by XericZephyr** [comment]
I actually tried 2.6.9 (also 2.6.6) and the problem still exists. Any workaround?

**Comment by augustoapg** [comment]
Still happening with me on version `^3.3.2`.

**Comment by michaeldoron59** [comment]
same here macOS, Node.js v21.6.1

**Comment by yangli-io** [comment]
Also experienced this issue.
why was this closed, theres no solution/workaround proposed.

**Comment by mohd-akram** [comment]
I closed it because it was an issue with the website not the library. Node.js has `fetch` built-in now so you should try with that.

**Comment by michaeldoron59** [comment]
> I closed it because it was an issue with the website not the library. Node.js has `fetch` built-in now so you should try with that.

This website returns a valid response with other libraries like python requests.
In [1]: import requests

In [2]: requests.get('https://uae.voxcinemas.com')
Out[2]: <Response [200]>

and it still hangs on node fetch when freshly installed by Homebrew on Mac.

And, it works just fine when installed by MacPorts:
Welcome to Node.js v22.5.1.
Type ".help" for more information.
> await fetch('https://uae.voxcinemas.com');
Response {
  status: 200,
  statusText: 'OK',
...
  },
  body: ReadableStream { locked: false, state: 'readable', supportsBYOB: true },
  bodyUsed: false,
  ok: true,
  redirected: false,
  type: 'basic',
  url: 'https://uae.voxcinemas.com/'
}

**Comment by mohd-akram** [comment]
See my comment when closing the issue - I was able to reproduce the hang using curl. Some websites behave differently depending on IPv4/IPv6, HTTP 1.1/HTTP 2, and the user agent. I would suggest experimenting with curl via the `-4`/`-6`, `--http1.1`/`--http2`, and `-A` flags respectively to figure out which scenario is problematic. In this case, the issue could be bypassed by passing a different `User-Agent` header.
