### ISSUE TITLE
Response status error. Shows incorrect status code

### ISSUE THREAD

**Issue by AndersSpringborg** [node-fetch/node-fetch#1607]
Fetch reads status as 200, even though express returns a 404.

**Reproduction**

1. Express endpoint
```tsx
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));


// Catch everything else and return 404
app.get('*', function (req, res, next) {
  const error: CustomError = new Error(
    `${req.ip} tried to access ${req.originalUrl}`
  );

  error.statusCode = 404;

  next(error);
});

export const server = app.listen(process.env.PORT, function () {
  console.log(`Server listening on PORT: ${process.env.PORT}`);
});
```
2. fetch endpoint `const response await fetch("http://localhost/")`
3. curl same endpoint `curl http://localhost/`
4. `response.status` is 200, but should be 404 like curl

**Expected behavior**

I expect it to have statuscode 404, like curl.
Curl output:
```shell
Connected to serviceapi(docker container) (172.22.0.5) port 80 (#0)
> GET / HTTP/1.1
> Host: serviceapi-client
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 136
< Date: Sun, 24 Jul 2022 14:53:16 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Not Found</pre>
</body>
</html>
```

**Screenshots**

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6
| node             | 16.15.1
| rollup           | 2.75.6
| Docker image     | node:16.15.1-bullseye

**Additional context**

This is run inside a compose environment, where it's a graphql service, trying to reach the express service

**Comment by TCM-dev** [comment]
@AndersSpringborg This is an old issue but how did you fix it? I'm having the same problem and since you closed the issue yourself I assume this is one that I can fix myself too?
