### ISSUE TITLE
Found potential security but got no response

### ISSUE THREAD

**Issue by vovikhangcdv** [node-fetch/node-fetch#1609]
## Issue

Hi there,

I have found a potential security issue in [node-fetch](https://github.com/node-fetch/node-fetch). I had tried to connect to SECURITY.md email but got no response too. I don't create a full disclosure issue there cause it could affect the users. So please get in touch with me through email [doublevkay@gmail.com](mailto:doublevkay@gmail.com) or just access the report on https://huntr.dev/bounties/a7e6a136-0a4b-46c4-ad20-802f1dd60bf7 (only private accessible by maintainers).

**Comment by vovikhangcdv** [comment]
Hi @NotMoni and @jimmywarting, can you verify [the report on Huntr](https://huntr.dev/bounties/a7e6a136-0a4b-46c4-ad20-802f1dd60bf7)?

**Comment by titivuk** [comment]
Hello,
What about version 2.x?

**Comment by vovikhangcdv** [comment]
> Hello, What about version 2.x?

Hi, Version 2.x is not affected by this vulnerability.

**Comment by titivuk** [comment]
> > Hello, What about version 2.x?
> 
> Hi, Version 2.x is not affected by this vulnerability.

Hi, looks like Snyk issue, I did not code causing the issue in v2 but Snyk says v2 is affected as well.
Thank you for confirmation
