### ISSUE TITLE
remove "light weight" from "A light-weight module that brings Fetch API to Node.js."

### ISSUE THREAD

**Issue by Pomax** [node-fetch/node-fetch#1637]
Nitpicking, but: `node-fetch` is an almost 8MB install. It is very much _not_ light weight (even if its own code is, it is _heavily_ weighed down by the 7.5MB `web-streams-polyfill` dependency used by `fetch-blob`)

**Comment by jimmywarting** [comment]
once web-streams-polyfill release [v4](https://github.com/MattiasBuelens/web-streams-polyfill/milestone/21) then it will drop it's size again...

**Comment by Pomax** [comment]
I don't see anything in v4 that justifies the claim that it'll be drastically smaller?

**Comment by jimmywarting** [comment]
https://github.com/MattiasBuelens/web-streams-polyfill/issues/82

**Comment by Pomax** [comment]
Cool, but in the mean time, there is no indication that it's being actively worked on (just incidentally), and as a user of `node-fetch` _I_ do not have the option to tell node fetch that it's installing on a normal, current version of Node and so needs almost nothing from the web-streams polyfill. So unless `npm install node-fetch` can be told to install only what it needs (which as far as I know is impossible?) node-fetch is not leight weight, even if web-streams-poly V4 becomes the ultimate pick-and-choose, the problem is still installing `node-fetch` pulling in the full polyfill dependency.

**Comment by jghaanstra** [comment]
Why is this closed, the term lightweight is very misleading and the it's been huge in size for more than a year now with no real indication of a solution any time soon.

**Comment by jimmywarting** [comment]
It where was once "lightweight" before we decided to make blob streams spec compatible by introducing whatwg streams polyfill that will conditionally be loaded. 
And it will be that once again when stream polyfill release v4 (which i hope would have happen sooner).
So i really think it's up to Mattias to fix the release as he has promised but it has taken a very long time... hence why i closed this.

**Comment by Pomax** [comment]
On a different note, Node 18 added the Fetch API as built-in now, so if you have the option of using the current LTS version of Node, you no longer even need node-fetch (as well as quite a few other packages that shimmer or filled network fetching functionality).
