### ISSUE TITLE
default export not working on pure-ESM typescript (node v16)

### ISSUE THREAD

**Issue by Polve** [node-fetch/node-fetch#1643]
### Discussed in https://github.com/node-fetch/node-fetch/discussions/1642

<div type='discussions-op-text'>

<sup>Originally posted by **Polve** September  9, 2022</sup>
I'm developing a new project so I can start from scratch using latest standards, so I'm using latest 16.x node, latest typescript (4.8.2), and trying to develop an ESM library.

The problem I have is that I can't import the default export, while everything works fine for the named imports.

So for example this works fine:
```
import {  Blob,  File,  Headers,  Request,  Response } from 'node-fetch'
```
while this code:
```
import fetch from 'node-fetch'
```
gives this error:
```
/home/user/.nvm/versions/node/v16.13.0/lib/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/user/x/node_modules/node-fetch/src/index.js from /user/x/foo.ts not supported.
Instead change the require of index.js in /home/user/x/foo.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.require.extensions.<computed> [as .js] (/home/x/.nvm/versions/node/v16.13.0/lib/node_modules/ts-node/dist/index.js:851:20)
```

Is it possible for you do avoid exporting the default and simply do a named export for "fetch"?
Or maybe both, to have better compatibility with cjs?

I'm no export on ESM modules but I think that a trivial fix would be to avoid exporting the definition of the function this way:
```
export default async function fetch(url, options_) {
```
and define the function and export it in two different places like this:
```
async function fetch(url, options_) {...}
export default fetch;
```</div>

**Comment by jimmywarting** [comment]
lets stick to keeping this in the discussion thread instead.
