### ISSUE TITLE
node-fetch user-agent still says 1.0 when we're now on 2.x and 3.x

### ISSUE THREAD

**Issue by jamesmortensen** [node-fetch/node-fetch#1658]
Here is the header sent by node-fetch:
- 'user-agent': 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)',

**Reproduction**

- Check the user agent when your app makes a node-fetch request.

1. Make a fetch request to some server endpoint.
2. Observe the user-agent string.

**Expected behavior**

Is the 1.0 a version number?  If it is, then it would be cool to keep it up to date with the library, similar to how user-agent version numbers are kept up to date by browsers.

**Your Environment**

We were running on macOS, but I'm sure it's the same in any environment.

| software         | version
| ---------------- | -------
| node-fetch       |  3.2.10
| node             |  v16.17.0
| npm              |. v8.15.0
| Operating System | macOS 12.4 M1 chip

**Additional context**

**Comment by jimmywarting** [comment]
the v3 have the user-agent set to just `node-fetch` by default if you want to change it then you can do so.
(we have removed the version number... to not leak as much information about what version somebody is using)
