### ISSUE TITLE
Cannot bundle Node.js built-in "node:http" while vite build

### ISSUE THREAD

**Issue by supproduction** [node-fetch/node-fetch#1665]
I am working on Vite v3.0.9 and using node-fetch 3.2.10. I used doc to import node-fetch (see screen) 
While build I have next issue 
<img width="917" alt="image" src="https://user-images.githubusercontent.com/16482929/198272939-a0c9f375-b414-4009-bb6b-6566519cbb9e.png">

**Current Behavior**

<img width="468" alt="image" src="https://user-images.githubusercontent.com/16482929/198272720-9db2b7b0-8e0c-4f1d-9201-295b91580348.png">

**Expected Behavior**
Successful build

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.2.10
| node             | 18.12.0
| npm              | 8.19.2
| Operating System |

**Additional context**

I've already tried workaround with replacing `node:http` into `http`
But than I have the same error but with just `http` module

**Comment by LinusU** [comment]
Are you trying to bundle for the web or for Node.js? This library only works in Node.js

**Comment by supproduction** [comment]
Hm, If I have `import fs from 'fs'` - all work.
For vite I have next settings, looks all good.

```
build: {
      target: 'esnext',
      lib: {
        entry: 'src/entry-server.ts',
        formats: ['iife'],
        name: 'storefront',
      },
      emptyOutDir: true,
      outDir: '../../dist/apps/storefront/server',
      ssr: 'src/entry-server.ts',
    },
    ssr: {
      noExternal: true,
    },
```

Mb could you clarify is it issue of node-fetch or vite?

**Comment by cannonmaster** [comment]
@supproduction , did you solve the issue, I am facing the exactly same issue.
