### ISSUE TITLE
Can't pass URL class object to fetch() in TypeScript

### ISSUE THREAD

**Issue by Maxim-Mazurok** [node-fetch/node-fetch#1695]
**Reproduction**

1. Write `fetch(new URL(""));`
2. `tsc --noEmit`
3. Observe `Argument of type 'URL' is not assignable to parameter of type 'RequestInfo'.ts(2345)`

**Expected behavior**

Works as per example in README: https://github.com/node-fetch/node-fetch#manual-redirect

**Screenshots**

![image](https://user-images.githubusercontent.com/7756211/210482898-83994651-a9dd-4600-aab1-b0529670bdbb.png)

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       |  3.3.0
| node             | 19.3.0
| npm              | 9.2.0
| typescript     | 4.9.4
| Operating System | Windows

**Additional context**

Related:
https://github.com/node-fetch/node-fetch/issues/372
https://github.com/nodejs/node/pull/17365
https://github.com/node-fetch/node-fetch/issues/1430

**Comment by jimmywarting** [comment]
According to the spec I couldn't find anything related to that the input should specifically accept a URL class.
![image](https://user-images.githubusercontent.com/1148376/210562778-8b7d5899-6a0c-403e-a90b-4223198e2868.png)

https://fetch.spec.whatwg.org/#request-class

---

I would also like to pass URL to fetch/request but i genuinely feel like this is a typescript issue then anything else.

You see some of this web api's have WebIDL conversion that normalize parameters to what it would like to have as an input parameter.

> - [any](https://heycam.github.io/webidl/#es-any)
> - [undefined](https://heycam.github.io/webidl/#es-undefined)
> - [boolean](https://heycam.github.io/webidl/#es-boolean)
> - [Integer types](https://heycam.github.io/webidl/#es-integer-types), which can additionally be provided the boolean options { clamp, enforceRange } as a second parameter
> - [float](https://heycam.github.io/webidl/#es-float), [unrestricted float](https://heycam.github.io/webidl/#es-unrestricted-float)
> - [double](https://heycam.github.io/webidl/#es-double), [unrestricted double](https://heycam.github.io/webidl/#es-unrestricted-double)
> - [DOMString](https://heycam.github.io/webidl/#es-DOMString), which can additionally be provided the boolean option { treatNullAsEmptyString } as a second parameter
> - [ByteString](https://heycam.github.io/webidl/#es-ByteString), [USVString](https://heycam.github.io/webidl/#es-USVString)
> - [object](https://heycam.github.io/webidl/#es-object)
> - [Buffer source types](https://heycam.github.io/webidl/#es-buffer-source-types), which can additionally be provided with the boolean option { allowShared } as a second parameter
 > 
> ref: https://www.npmjs.com/package/webidl-conversions

So you can (if you like to) just simply pass in an object, number, boolean, or literally anything you want. and WebIDL will try it's best to convert whatever you throw at it into a string.

```js
fetch({
  toString() {
    return 'https://httpbin.org/get'
  }
}) // will fetch https://httpbin.org/get
fetch(true) // will fetch `./true`
fetch((blogId = 2)) // will fetch `./2`
fetch({}) // // will fetch `./[object%20Object]`
fetch({
  [Symbol.toPrimitive](hint) {
    console.log(hint)
    if (hint === 'string') {
      return 'https://httpbin.org/image/png'
    }
    return null
  }
}) // will fetch https://httpbin.org/image/png and log the hint: 'string'
```

And the URL class just so happens to have a `URL.prototype.toString` method that makes it work as you would like it to do.

So do i feel like we should add in each and every method like URL, boolean, number, bigint, toString and toPrimitive and so on? no
Do i think this is a typescript issue? yes, TS isn't so good for a loosed typed language.
If anything i think it should be

```js
/**
 * @param { Request | any } input
 * @param { RequestInit } init
 */  
function fetch(input, init) { ... }
```

Something even better would be to use `USVString`
```js
/**
 * @param { Request | USVString } input
 * @param { RequestInit } init
 */  
function fetch(input, init) { ... }
```
but TS don't have any logic about USVString and how it can convert whatever into a USVString (it only have string support)

it's the same argument about `URLSearchParams` not supporting numbers and booleans: https://github.com/microsoft/TypeScript/issues/32951

TS should actually have some kind of stringable USVString logic that we can use  for ppl who mostly write polyfills https://github.com/microsoft/TypeScript/issues/28775

**Comment by LinusU** [comment]
Duplicate of #1261?

But yeah, this is a though one. There is no special handling of `Url` in the spec, but it is a common use case.

TypeScript DOM typings does allow `URL` specifically:

https://github.com/microsoft/TypeScript/blob/f43cd0accac3e5033820fd27035731ed88f54938/lib/lib.dom.d.ts#L18281

**Comment by Maxim-Mazurok** [comment]
Thanks for your input guys, I believe this is a duplicate of #1261 indeed, so I'll reply in there, cheers!
