### ISSUE TITLE
Deno process crashes while using node-fetch 2.x.x

### ISSUE THREAD

**Issue by joamag** [node-fetch/node-fetch#1725]
Using deno (which now supports npm packages) and node-fetch 2.x.x yields an unhandled error due to "socket" event not being triggered.

I believe keeping deno compatibility is not a priority but a simple `undefined` testing in the socket variable should fix the issue.

**Reproduction**

1. Use deno and node-fetch
2. Perform a simple fetch operation (ex: GET)
3. Verify that the deno process has exited with an Uncaught error on `fixResponseChunkedTransferBadEnding()`

**Expected behavior**

No unhandled error is raised and the fetch requests are handled properly.

**Screenshots**

![image](https://user-images.githubusercontent.com/25441/225905633-5b9598c0-fd14-4c05-a1e2-ded2f7ed79aa.png)

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | v2.6.8+
| deno            | v1.31.3
| Operating System | Windows

**Additional context**

This is verified only while using deno and not in node.js.

**Comment by joamag** [comment]
PR added #1726 @jimmywarting

**Comment by jimmywarting** [comment]
Why do you want to use node-fetch when deno have it built in already? 
...so those NodeJS v18

**Comment by joamag** [comment]
> Why do you want to use node-fetch when deno have it built in already? ...so those NodeJS v18

Transitive dependency of a node API package that makes use of node-fetch
