### ISSUE TITLE
Configured environment is not supported yet

### ISSUE THREAD

**Issue by EngineerHus** [node-fetch/node-fetch#1737]
When I am trying to compile my code, I get the following error:
```
 > node_modules/fetch-blob/from.js:83:2: error: Transforming async generator functions to the configured target environment ("node10") is not supported yet
    83 │   async * stream () {
       ╵   ~~~~~

 > node_modules/node-fetch/src/body.js:223:6: error: Transforming for-await loops to the configured target environment ("node10") is not supported yet
    223 │     for await (const chunk of body) {
        ╵         ~~~~~

 > node_modules/fetch-blob/index.js:12:0: error: Transforming async generator functions to the configured target environment ("node10") is not supported yet
    12 │ async function * toIterator (parts, clone = true) {
       ╵ ~~~~~

 > node_modules/fetch-blob/index.js:122:8: error: Transforming for-await loops to the configured target environment ("node10") is not supported yet
    122 │     for await (const part of toIterator(this.#parts, false)) {
        ╵         ~~~~~

 > node_modules/fetch-blob/index.js:145:8: error: Transforming for-await loops to the configured target environment ("node10") is not supported yet
    145 │     for await (const chunk of toIterator(this.#parts, false)) {
        ╵         ~~~~~

 > node_modules/web-streams-polyfill/dist/ponyfill.es2018.js:519:79: error: Transforming async generator functions to the configured target environment ("node10") is not supported yet
    519 │     const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf(async function* () { }).prototype);
        ╵                                                                                ~~~~~

 > node_modules/node-fetch/src/utils/multipart-parser.js:425:5: error: Transforming for-await loops to the configured target environment ("node10") is not supported yet
    425 │   for await (const chunk of Body) {
        ╵       ~~~~~
   Packaging the app... ✖
 ›   Error:    ⟿  Build failed with 7 errors:
 ›   node_modules/fetch-blob/from.js:83:2: error: Transforming async generator functions to the configured target environment ("node10") is not supported yet
 ›   node_modules/fetch-blob/index.js:12:0: error: Transforming async generator functions to the configured target environment ("node10") is not supported yet
 ›   node_modules/fetch-blob/index.js:122:8: error: Transforming for-await loops to the configured target environment ("node10") is not supported yet
 ›   node_modules/fetch-blob/index.js:145:8: error: Transforming for-await loops to the configured target environment ("node10") is not supported yet
 ›   node_modules/node-fetch/src/body.js:223:6: error: Transforming for-await loops to the configured target environment ("node10") is not supported yet
```

My current code is:
```
import {
    IHttp,
    IModify,
    IRead,
} from '@rocket.chat/apps-engine/definition/accessors';
import fetch from 'node-fetch';
import {
    ISlashCommand,
    SlashCommandContext,
} from '@rocket.chat/apps-engine/definition/slashcommands';

 export class n implements ISlashCommand {
    public command = 'n';
    public i18nParamsExample = '';
    public i18nDescription = '';
    public providesPreview = false;

    public async executor(context: SlashCommandContext, read: IRead, modify: IModify, http: IHttp): Promise<void> {

      const supply = '{"fields": {"project": {"key": "TEST"},"summary": "TEST the API","description": "testing API","issuetype": {"name": "Bug"},"customfield_11050": "idk."}}'
      const response = await fetch('http://localhost:3000/', {
        method: 'post',
        body: JSON.stringify(supply),
        headers: {'Content-Type': 'application/json'}
        });
      const data = await response.json();

      console.log(data);
};
};
```

My tsconfig.json file looks like this:
```
{
"compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    },
"include": [
    "**/*.ts"
    ]
}
```
**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 3.3.1
| node             | 18.16.0
| npm              | 9.5.1
| Operating System | Linux Ubuntu

**Comment by LinusU** [comment]
> Transforming async generator functions to the configured target environment ("node10") is not supported yet

You have somehow configured TypeScript's target to be Node.js 10.x, even though you are using Node.js 18.16.

node-fetch supports a minimum of Node.js 12.20.0...

**Comment by EngineerHus** [comment]
> > Transforming async generator functions to the configured target environment ("node10") is not supported yet
> 
> You have somehow configured TypeScript's target to be Node.js 10.x, even though you are using Node.js 18.16.
> 
> node-fetch supports a minimum of Node.js 12.20.0...

a noobie question but how have I done that?

**Comment by jimmywarting** [comment]
fyi, if you are running node 18.16 then fetch is available globally
https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch

so no dependency is needed.

**Comment by EngineerHus** [comment]
> fyi, if you are running node 18.16 then fetch is available globally https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch
> 
> so no dependency is needed.
Are you suggesting I should uninstall node-fetch with npm and just use the import statement within my code?

**Comment by EngineerHus** [comment]
> > a noobie question but how have I done that? the target in tscongif.json shows es2017, is there somewhere else where I could have set the target of my TypeScript?
> 
> I'm not sure actually, how are you invoking TypeScript? Are you using a bundler as well?

I believe it is being invoked through either Node.js VM or the Apps Engine CLI for Rocketchat. If there is a way to find out please let me know so I will look into it

**Comment by jimmywarting** [comment]
> > fyi, if you are running node 18.16 then fetch is available globally https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch
> > so no dependency is needed.
> 
> Are you suggesting I should uninstall node-fetch with npm and just use the import statement within my code?

yes, uninstall `node-fetch` and just use fetch as normal. it's available globally, so you don't even have to import anything.
so is Response, Request, FormData, Blob and web streams

and you don't have to use any import statement at all.

```diff
- import fetch, { FormData } from 'node-fetch'

const res = await fetch('http://example.com')
```
But if you are building a package for other to use, then maybe you want to keep node-fetch if you target node LTS (v16)

**Comment by EngineerHus** [comment]
> > > fyi, if you are running node 18.16 then fetch is available globally https://nodejs.org/dist/latest-v18.x/docs/api/globals.html#fetch
> > > so no dependency is needed.
> > 
> > 
> > Are you suggesting I should uninstall node-fetch with npm and just use the import statement within my code?
> 
> yes, uninstall `node-fetch` and just use fetch as normal. it's available globally, so you don't even have to import anything. so is Response, Request, FormData, Blob and web streams
> 
> and you don't have to use any import statement at all.
> 
> ```diff
> - import fetch, { FormData } from 'node-fetch'
> 
> const res = await fetch('http://example.com')
> ```
> 
> But if you are building a package for other to use, then maybe you want to keep node-fetch if you target node LTS v16 ...or lower down to v12

ah okay. Well my problem was solved when I deleted the node-fetch package and instead used fetch globally by importing it.

**Comment by marcosfelipeti** [comment]
> > > a noobie question but how have I done that? the target in tscongif.json shows es2017, is there somewhere else where I could have set the target of my TypeScript?
> > 
> > 
> > I'm not sure actually, how are you invoking TypeScript? Are you using a bundler as well?
> 
> I believe it is being invoked through either Node.js VM or the Apps Engine CLI for Rocketchat. If there is a way to find out please let me know so I will look into it

Hi there! I'm having the exact issue with Rocketchat app engine. Have you ever faced the same problem?

**Comment by EngineerHus** [comment]
> > > > a noobie question but how have I done that? the target in tscongif.json shows es2017, is there somewhere else where I could have set the target of my TypeScript?
> > > 
> > > 
> > > I'm not sure actually, how are you invoking TypeScript? Are you using a bundler as well?
> > 
> > I believe it is being invoked through either Node.js VM or the Apps Engine CLI for Rocketchat. If there is a way to find out please let me know so I will look into it
> 
> Hi there! I'm having the exact issue with Rocketchat app engine. Have you ever faced the same problem? 

I can't help too much, but once I switched from fetch to axios the errors went away 🤷‍♂️

**Comment by marcosfelipeti** [comment]
Thanks a lot for replying! Could you give me details on how you moved from fetch do axios? I'm really new on nodejs stuff. Thanks in advance!

**Comment by EngineerHus** [comment]
> Thanks a lot for replying! Could you give me details on how you moved from fetch do axios? I'm really new on nodejs stuff. Thanks in advance!

Honestly, I'm as new as you, it was my first time using TypeScript too but the link I used was this:

https://www.npmjs.com/package/axios
