### ISSUE TITLE
v2.7.0: punycode is deprecated in 'whatwg-url' and 'tr46'

### ISSUE THREAD

**Issue by riprsa** [node-fetch/node-fetch#1794]
**Reproduction**

Using node v21.2.0:

_package.json:_
```json
{
    "dependencies": {
        "node-fetch": "^2.7.0"
    }
}
```

_index.js:_
```bash
const fetch = require('node-fetch');
fetch("https://google.com").then((res) => {
    console.log(res.status);
});
```

_output:_
```
(node:25053) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
200
```

**Expected behavior**

Lack of deprecation note

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       |2.7.0
| node             |21.2.0
| npm              |10.2.3
| Operating System |macOS

**Comment by jimmywarting** [comment]
see: https://github.com/node-fetch/node-fetch/pull/1793#issuecomment-1839050150

**Comment by erictheswift** [comment]
See line 40 at https://www.npmjs.com/package/node-fetch/v/2.7.0?activeTab=code
Seems wrong package.json was published, thus this issue is not resolved

**Comment by erictheswift** [comment]
Ah ok, there's an ongoing issue about that https://github.com/node-fetch/node-fetch/issues/1797 @jimmywarting
