### ISSUE TITLE
Implement body.formData

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#199]
The spec implements a formData method to turn a request/response body back into a FormData

**Comment by bitinn** [comment]
Node.js doesn't have FormData, I just don't think we can do that without explicit dependency on `form-data`, and `form-data` isn't explicitly isomorphic either.

**Comment by TimothyGu** [comment]
When the user is already using node-fetch, then he/she is probably already past the isomorphic layer – as node-fetch itself is not isomorphic. Regarding the dependency on form-data, I don't consider it to be that great of an issue; but we could let the user specify the constructor as an option if we were to care about the size of this installation.

**Comment by jimmywarting** [comment]
Something that just pop-out of my mind is handing over just a instance to wish we can append the data into...  May not be the *right* thing to do...

```js
var FormData = require('form-data')
new Response(...).formData(new FormData)
```

One think i don't like so much about form-data today is that's not fully implemented. Lacks many feature of reading and manipulate the form. Without this it would be no point in even implementing body.formData since you would not have any way of changing/reading it... But hopefully they will resolve this issue: https://github.com/form-data/form-data/issues/124 someday - kind of lost hope since it have taken them a long time now...

I did implement a better fully spec'ed FormData polyfill [here](https://github.com/jimmywarting/FormData). But it was targeted for browser (not for node - since it depends on Blob & File)

**Comment by octet-stream** [comment]
@jimmywarting Hi! If you still need a FormData implementation, may be you check out [this one](https://github.com/octet-stream/form-data)? I've implemented more than just an .append method.

**Comment by jimmywarting** [comment]
Never seen it before, have only used https://www.npmjs.com/package/form-data so far.
Just another implementation of FormData. It's nice that the rest of the methods are implemented like the iterator and all that. But maybe not certain node-fetch can work together with that.

The sad part is that there is no standard spec of how it should be read/handeld. 
But the feature might look brighter: https://github.com/w3c/FileAPI/issues/40
We will maybe get `Symbol.stream` or something like that. There have been numerus of talk about  making FormData streamable and having a unknown content-length

**Comment by jimmywarting** [comment]
btw, i did this for the fetch polyfill: https://github.com/github/fetch/issues/571

The reason i would like to see this implemented on the server is so that i can have one less dependency :P

Express.js app:
```js
app.post('/user', async (req, res) => {
  const fd = new FormData()
  await new Response(req).formData(fd)

  fd.get('username')
})
```
