### ISSUE TITLE
body conversion

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#210]
Haven't tested v2 if this works but i would like for this to work:
It currently doesn't in 1.x

```js
stream = new Response('hi').body
str = await new Response(Uint8Array.from([97])).text() // a
stream = new Response(Uint8Array.from([97])).body // returns a Uint8array [97] (should return a stream)
```

Ideally every acceptable thing you put into Response should work with<br> `arraybuffer() json() text() and .body`

**Comment by TimothyGu** [comment]
To implement this efficiently one would need to add a `body` getter function, so as to prevent having to go through the process of creating streams when the body is read synchronously anyway.

@bitinn, what are your thoughts on this?

**Comment by bitinn** [comment]
I will say we hold off from this feature for now. We will get around to it when available.

**Comment by garthk** [comment]
Fixing this _might_ justify a major semver bump. It wouldn't surprise me if people who took a dependency on `node-fetch` directly or via `isomorphic-fetch` somehow rely on `Response.body` being whatever was passed to the `Response` constructor, not necessarily a stream.

Arguing against that, for a sec: most customers wouldn't follow us across a major semver bump, and would miss out on bug and security fixes unless we back-ported them, which might require more effort than we've got spare.

I worked around it in fetch-hooks by wrapping a `Proxy` around the final `Response`, modifying `body`, and binding all methods to the original object so their view of `this.body` remained unchanged.

**Comment by jimmywarting** [comment]
This have been hold of for a long time now

**Comment by bitinn** [comment]
With #547 merged I think we are now a step towards making `req.body` and `req.body` more consistent even when you create it with Request/Response constructor.

I don't currently have time to make the rest of conversion, @jimmywarting let me know if you are up to the task.

I also think the next release should trigger a major version bump (and release into `next` branch) due changes on Request/Response constructor (even though I expect few to depend on it).

Given there are quite a few issues pending for V3 release, it's now a good time to fix this problem along with them.

**Comment by jimmywarting** [comment]
I'm up for it

**Comment by bitinn** [comment]
@jimmywarting just `master`,  I have created a new branch `2.x` with latest code `2.3.0`, but not our last commit.

**Comment by xxczaki** [comment]
@jimmywarting As it is in our [v3 Roadmap](https://github.com/bitinn/node-fetch/issues/668), wouldn't you mind to implement it in your free time? Thanks ;)

**Comment by jimmywarting** [comment]
Now that most are either a buffer or a stream it would make it a lot easier now to convert the buffer to a stream using `stream.Readable.from`

**Comment by jimmywarting** [comment]
should come up with some test also

**Comment by jimmywarting** [comment]
I guess we don't want to convert it to a stream internally.
the stream can only be consumed once. and there are some redirects where body follows like 307 and some PATCH method.

Here is what happens when you post some data in chrome using a simple body:

![Skärmavbild 2020-09-03 kl  03 46 35](https://user-images.githubusercontent.com/1148376/92062076-26346000-ed98-11ea-8c7e-4059ee3e9c07.png)

And here is another where streams are being used:

![Skärmavbild 2020-09-03 kl  03 43 17](https://user-images.githubusercontent.com/1148376/92062114-39473000-ed98-11ea-9ab7-4b84885e084f.png)

So my assumption is that it's best to have either null, buffer or stream as the only internal data. tried to convert body to a stream but that only created more headache. The easier solution was to create a body getter function instead.

---

working on a PR
