### ISSUE TITLE
When redirecting to a different host, strip Authorization header

### ISSUE THREAD

**Issue by bitinn** [node-fetch/node-fetch#274]
This is a tricky one, on the surface, security first, why would you want to do that?

But:

- There isn't a Spec / RFC enforcing it.
- Some single sign-on solutions even rely on it.

Request that do implement such a thing:

- https://github.com/request/request/blob/b12a624/lib/redirect.js#L134

So does curl (but only when using a http proxy?)

- https://github.com/curl/curl/blob/6beb0eee/lib/http.c#L710
- http://stackoverflow.com/questions/37865875/stopping-curl-from-sending-authorization-header-on-302-redirect

Either way, I am not rushing to *fix* this, but a heads-up if anyone is using `node-fetch` for authorisation.

**Comment by TimothyGu** [comment]
The reason why the Fetch Standard doesn't enforce it is because it doesn't allow fetching a URL with credentials in the first place. See [`Request()`](https://fetch.spec.whatwg.org/commit-snapshots/5b7dae0fcc24cc8e025b216b80248d2619177ac4/#dom-request) step 6.3:

> 6. If *input* is a string, then run these substeps:
>    1. Let *parsedURL* be the result of parsing *input* with *baseURL*.
>    2. If *parsedURL* is failure, then throw a `TypeError`.
>    3. If *parsedURL* includes credentials, then throw a `TypeError`.

I think we should make this change.

**Comment by Richienb** [comment]
@bitinn @TimothyGu For this issue, should we stick as close as possible to the spec and deny credentials or just strip the Authorisation header?

**Comment by bitinn** [comment]
close via #1449
