### ISSUE TITLE
missing response stream error events

### ISSUE THREAD

**Issue by randypuro** [node-fetch/node-fetch#309]
The response stream is setup as a series of pipes, but node-fetch only listens for errors on the end of the pipe. Pipes don't send error events along the way. We've seen expected end of JSON input errors which are in fact probably caused by ECONNRESET's which are not surfacing because of this issue.

**Comment by bitinn** [comment]
You will have to give us a concrete example, we handle errors on this 2 level (response and response body).

- https://github.com/bitinn/node-fetch/blob/master/src/index.js#L62-L65
- https://github.com/bitinn/node-fetch/blob/master/src/body.js#L197-L199

And you can see timeout handling on the top.

**Comment by randypuro** [comment]
Great, sorry for not being more clear. The problem is here (and subsequent pipes related to compression):

https://github.com/bitinn/node-fetch/blob/master/src/index.js#L118

It's my understanding that the pipe won't forward error events:

https://groups.google.com/forum/#!msg/nodejs/lJYT9hZxFu0/L59CFbqWGyYJ

As a result, the response body error listener won't actually pick up error events from the response  stream source.

**Comment by bitinn** [comment]
@randypuro Thx for the explanation, could you help to provide a failing test case?

Our test cases are pretty easy to work on:

1) you setup a simple server route that simulate what you experience, [like this](https://github.com/bitinn/node-fetch/blob/master/test/server.js#L277-L279)

2) then you try to access it and test for your expected result, [like this](https://github.com/bitinn/node-fetch/blob/master/test/test.js#L434-L439)

You just need to figure out how to replicate your situation.

**Comment by randypuro** [comment]
Unfortunately, the node api isn't low level enough to simulate some of the use cases that might occur in the wild (eg. TCP level connection reset while reading data from the socket of a response stream which results in a `read ECONNRESET`).  Even calling socket.destroy() from the node server perspective won't trigger those same tcp level errors you might see from [the client perspective](https://github.com/nodejs/node/blob/master/lib/net.js#L610) I'm not sure how to help reproduce it, but we've seen the same issue, when using the request library, reported as a ECONNRESET whereas now using node-fetch, we see a seemingly successful request, but with an incomplete/partial response.

**Comment by bitinn** [comment]
Alright so the only safe way to ensure we capture all error events relating to network is to listen to the initial `res` body.

It might take a while before we can properly look into this. Are you using a standard JSON API or a JSON stream?

**Comment by TimothyGu** [comment]
@bitinn Is there a reason why we are [piping](https://github.com/bitinn/node-fetch/blob/master/src/index.js#L118) `res` to a new stream in the first place? I was never able to figure this one out.

**Comment by bitinn** [comment]
@TimothyGu It's quite possible my initial design decision is to prevent users from accessing the raw http response. So that they stick to the Fetch API.

Now that I looked at it, I am not sure this issue can be nicely resolved if you also happen to `.clone()` the response, by definition it must be *teed* (*piped*).

**Comment by randypuro** [comment]
We see this issue just using the standard `.text()` api.

**Comment by atishay** [comment]
Did anyone figure out a workaround. In some error case, if we pipe the stream, the response never comes and it hangs forever.

**Comment by ajhyndman** [comment]
I just ran into this issue, and want to confirm that it's still happening in the latest release (2.6.0).

@atishay I worked around some connections hanging by setting a timeout and retrying, manually.

**Comment by jstewmon** [comment]
I think I've fixed this in #768
