### ISSUE TITLE
Support trailers

### ISSUE THREAD

**Issue by TimothyGu** [node-fetch/node-fetch#330]
The `Response` class has a [`trailer`](https://fetch.spec.whatwg.org/#dom-response-trailer) attribute that we don't currently implement. Node.js exposes trailers through [`res.trailer`](https://nodejs.org/api/http.html#http_message_trailers) that is only populated when `'end'` event is fired.

**Comment by Pixcell** [comment]
Hi,

This would be a feature I would be interested in having.
Is it in your near future roadmap ?

Thanks

**Comment by Richienb** [comment]
See https://github.com/node-fetch/node-fetch/pull/690#issuecomment-589401669
