### ISSUE TITLE
default method

### ISSUE THREAD

**Issue by yzfshuijing** [node-fetch/node-fetch#374]
if there's a method just like :
var baseRequest = require('request');
baseRequest.defaults({
    timeout: 5
});
so we may not set the timeout and other params everytime

**Comment by bitinn** [comment]
Interesting, not sure Fetch Spec has this feature or not, but does copying this default option objects help? Or maybe we could expose the request options somehow in the future.

https://github.com/bitinn/node-fetch#options

**Comment by xxczaki** [comment]
Fetch spec doesn't have this feature. I don't think it's really that useful since you can just do something like this:

```js
const options = {
	method: 'GET',
	timeout: 0
	// Other options
};

fetch('https://amazon.com', options);
fetch('https://google.com', options);
```

Please reopen if necessary ;)
