### ISSUE TITLE
Testcase "should handle DNS-error response" is flaky

### ISSUE THREAD

**Issue by ThisIsMissEm** [node-fetch/node-fetch#512]
The test case "should handle DNS-error response" relies on an actual DNS query to happen, so if your DNS isn't setup in a conventional way or is having issues, then you'll receive spurious text failures. I've just uncovered these whilst working on my fork.

If my DNS server is misconfigured and takes a greater than 2 seconds to respond, then I get the following failure:

```console
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (test/test.js)
```

As a customer of Telekom in Germany for internet, my DNS servers always respond with a result, even if the page isn't found. They offer this weird branded google thing, see the attached screenshot. This means that domain.invalid actually returns a response:

```console
$ cross-env BABEL_ENV=test mocha --require babel-register --grep "/should handle DNS-error response$/" test/test.js


  node-fetch
    1) should handle DNS-error response


  0 passing (219ms)
  1 failing

  1) node-fetch
       should handle DNS-error response:
     AssertionError: expected promise to be rejected but it was fulfilled with { size: 0,
  timeout: 0,
  url: [Getter],
  status: [Getter],
  ok: [Getter],
  statusText: [Getter],
  headers: [Getter],
  clone: [Function: clone],
  body: [Getter],
  bodyUsed: [Getter],
  arrayBuffer: [Function: arrayBuffer],
  blob: [Function: blob],
  json: [Function: json],
  text: [Function: text],
  buffer: [Function: buffer],
  textConverted: [Function: textConverted] }

```

![screen shot 2018-08-28 at 18 48 26](https://user-images.githubusercontent.com/30827/44737702-02781880-aaf3-11e8-84be-9ad766299e9e.png)

**Comment by TimothyGu** [comment]
Right, I remember seeing this as well (before I just switched my DNS server to Google's). However, the [`.invalid` TLD](https://en.wikipedia.org/wiki/.invalid) is designed for testing.

Could you see if any of the other TLDs for this purpose (like `.example` and `.test`) work for you?

**Comment by xxczaki** [comment]
Marking this as `wontfix`, as it's Telekom's issue.

**Comment by ThisIsMissEm** [comment]
@xxczaki a way that this could actually be "fixed" would be to improve the test case to not actually rely on DNS queries, and instead stub out the DNS resolution, e.g., 

```
it('should handle DNS-error response', function(done) {
  const url = 'http://domain.invalid';
  const dnsErrorAgent = new http.Agent({
    lookup: function(hostname, options, callback) {
      const err = new Error(`getaddrinfo ENOTFOUND ${hostname}`);
      err.errno = 'ENOTFOUND';
      err.code = 'ENOTFOUND';
      err.syscall = 'getaddrinfo';
      err.hostname = hostname;

      callback(err)
    }
  });

  const originalAgent = http.globalAgent;

  http.globalAgent = dnsErrorAgent;

  expect(fetch(url)).to.eventually.be.rejected
    .and.be.an.instanceOf(FetchError)
    .and.have.property('code', 'ENOTFOUND')
    .and.notify((err) => {
      http.globalAgent = originalAgent;
      done(err);
    });
});
```

Granted, it's been a while since I've worked with chai and mocha, so maybe there's a better way of setting `http.globalAgent` just for the given test-case
