### ISSUE TITLE
Not posting body data

### ISSUE THREAD

**Issue by hrwndr** [node-fetch/node-fetch#565]
I am trying send a post request but the json data in body attribute is not getting sent. I tried sending this request with Postman and it is working just fine.

**Code:** 
```
const fetch = require('node-fetch')
fetch('https://test.instamojo.com/api/1.1/payment-requests/', {
  method: "POST",
  headers: {
    'Content-Type': 'application/x-www-form-urlencoded',
    'X-Api-Key': 'xxx', 
    'X-Auth-Token': 'xxx'
  },
  body: JSON.stringify({
    purpose: 'FIFA 16',
    amount: '2500'
  })
}).then(res => res.json())
.then(data => console.log(data)).catch(e => console.log(e))

```
**Error:** 
```
{ success: false,
  message: 
   { amount: [ 'This field is required.' ],
     purpose: [ 'This field is required.' ] } }
```

**Comment by hrwndr** [comment]
@Leko i tried that as well but i am getting the same error

**Comment by jimmywarting** [comment]
Try using https://httpbin.org/post and see what the request looks like

**Comment by hrwndr** [comment]
It is working just fine with postman.

**Comment by luispaulorsl** [comment]
Try use `URLSearchParams`, like in [README.md](https://github.com/bitinn/node-fetch#post-with-form-parameters)

**Comment by xxczaki** [comment]
@hrwndr Have you tried the solution suggested by @luispaulorsl?

**Comment by jimmywarting** [comment]
have been one year without any respond.
