### ISSUE TITLE
Enable a tool like greenkeeper to keep dependencies up to date

### ISSUE THREAD

**Issue by JustinBeckwith** [node-fetch/node-fetch#626]
When running `npm install` on the project, I noticed a fair number of dependencies were out of date:
![image](https://user-images.githubusercontent.com/534619/56867264-22b8e980-6998-11e9-996e-4e8329f4f498.png)

Keeping these up to date on your own can be kind of painful.  We use tools https://greenkeeper.io or https://renovatebot.com to keep deps up to date by auto-submitting PRs.  It's lovely :)  Would be great to see this set up here too!

**Comment by gr2m** [comment]
@bitinn I can setup Greenkeeper and take care of any trouble it might cause (it won’t).

**Comment by bitinn** [comment]
@gr2m really appreciate it, but I need to let you know many of the current dev dependency pinning is solely due to node v4/v6 support, which I fear automation would break.

Is it possible for me to open a 3.x branch and let you experiment with it? I am thinking of moving towards that anyway: I plan to drop v4, v6 and some current legacy code (and extract some into a separate package).

**Comment by gr2m** [comment]
Sure, sounds like a plan 👍 

I can also help setup semantic-release which automates releases, and it supports maintenance releases, too. It lowers the barrier to contribute and release updates to older versions. From my experience, it’s usually bigger companies that depend on these legacy versions. If that’s the case here, we could find an arrangement to let them maintain the legacy version while `node-fetch@latest` can solely support the latest and greatest :)

I can make a separate issue if you are interested in that.

**Comment by bitinn** [comment]
Alright, I just pushed a `3.x` branch, feel free to setup greenkeeper and make PR towards it.

I haven't used greenkeeper before so let me know if you need anything.

Thx @gr2m for reaching out!

**Comment by gr2m** [comment]
Turns out Greenkeeper only supports sending pull requests against a repository’s default branch. I’ll update the dependencies manually for the time being

**Comment by xxczaki** [comment]
We are going to use [Dependabot](https://dependabot.com/) as soon as `v3` gets released :smile:

**Comment by Richienb** [comment]
I've added Dependabot for the `3.x` branch.
