### ISSUE TITLE
"Bring your own stream"

### ISSUE THREAD

**Issue by bitinn** [node-fetch/node-fetch#647]
(Just a question for me to consider in future.)

Is it possible to allow users to bring their own stream implementation, thus satisfy demands from both node stream and web stream camps? We did exactly that during the node <1 era when `Promise` isn't native yet. Perhaps it's time for that again...

**Comment by jimmywarting** [comment]
Not sure. 

But If both node and web streams are asyncIterable, we could read both stream in the same way and send that over the wire. 
Internally we could support reading both streams but then the question is more, what should we give  back to the user?

Considering this as a node environment and that user could as well use asyncIterator on their own part makes the differences less important. 

I would maybe revisit this question when/if whatwg streams lands in node
https://github.com/nodejs/whatwg-stream
b/c as of right now it don't bring much value to the node side.

**Comment by ThisIsMissEm** [comment]
is it worth linking in #387 here?

**Comment by jimmywarting** [comment]
fyi, my above [comment](#issuecomment-497978324) was posted as a proposal to let the body accept any iterator too https://github.com/whatwg/fetch/issues/809

**Comment by sodabrew** [comment]
Hello, I found my way to this issue because I'm writing unit tests for fetch with body as whatwg readable stream, and learning that there might not be any way right now to execute the unit tests in NodeJS.

There's also https://www.npmjs.com/package/fetch-readablestream and https://github.com/evidentpoint/isomorphic-fetch-readablestream, which also has the benefit of TypeScript bindings.

I can see that I'm not the first person to wander my way down this road, but there isn't yet any awesome solution. The proposal here, that I could use this package in conjunction with something like web-streams-polyfill, sounds like the best option that might come together with a nudge.

**Comment by jimmywarting** [comment]
if https://github.com/whatwg/streams/issues/1018 gets implemented in both node and whatwg stream then maybe we can just keep the current stream that we are using.

Then they could use their own stream as they like.
```js
res = await fetch(url)
ReadableStream.from(res.body)
```

**Comment by jimmywarting** [comment]
FYI, i saw that node implemented [Readable.from](https://nodejs.org/docs/latest-v13.x/api/stream.html#stream_stream_readable_from_iterable_options) in v12.3
```js
const { Readable } = require('stream');

async function * generate() {
  yield 'hello';
  yield 'streams';
}

const readable = Readable.from(generate());

readable.on('data', (chunk) => {
  console.log(chunk);
});
```

kinda what i expected to land eventually :)

maybe this old generator/iterator combined with async iterator will be the new norm of writing cross node/web platform features hopefully

**Comment by pkieltyka** [comment]
the generator pattern is pretty cool and works for reading chunks, but how would you cancel a stream or cancel a response in a consistent way with node/web?

**Comment by jimmywarting** [comment]
using [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController)

**Comment by pkieltyka** [comment]
@jimmywarting thanks, makes sense. Have you thought about including a small AbortController impl inside of node-fetch then so it completes the api? I know there is abort-controller-npm package, but its pretty small and not much there, and now requires a consumer to remember to install deps `node-fetch` and `abort-controller-npm`

**Comment by jimmywarting** [comment]
Worth mentioning that we could use [stream.Readable.from(iterable, [options])](https://nodejs.org/dist/latest-v13.x/docs/api/stream.html#stream_stream_readable_from_iterable_options) if they passed a whatwg stream

```js
fetch(url, { body: whatwg_readableStream })

// somewhere in body.js
if (body === whatwg_stream) {
  if (stream.Readable.from) {
    body = stream.Readable.from(body)
  } else {
    throw new Error('reading whatwg stream requires node > v12.3.0')
  }
}
```

or you could do it yourself as a quick solution.
```js
fetch(url, { body: stream.Readable.from(whatwg_readableStream) })
```

**Comment by jimmywarting** [comment]
Closing this and deciding on using whatwg stream that is built in or fallback to using a polyfill

**Comment by pkieltyka** [comment]
Would you mind dropping a few links please? What do you mean “whatwg stream” ? How to do streams with node and fetch api? Will node add this directly or is there another library which provides an interface impl?

**Comment by jimmywarting** [comment]
NodeJS community have wanted to get fetch into core https://github.com/nodejs/node/issues/19393

...They listen and they are going for it. To ship it they need to implement many underlying methods such as Blob, AbortSignal, and many more like the [whatwg stream](https://streams.spec.whatwg.org/) that is part of fetch's `response.body` first

So they added whatwg streams in node v16.5 behind experimental flags: https://github.com/nodejs/node/pull/39062

we could shim it using a polyfill.

For ppl that still want/need a `node:stream` with `.pipe()` can do: `stream.Readable.from(iterable_or_responseBody)` or use the `for await (let chunk of res.body)`.

Think we are still going to support uploading `node:streams` with Requests but the Body.body are going to return a speced whatwg:stream instead

**Comment by pkieltyka** [comment]
Awesome thank you
