### ISSUE TITLE
Not explicit documentation about cookies

### ISSUE THREAD

**Issue by GrosSacASac** [node-fetch/node-fetch#702]
In the documentation, nothing says what happens when cookies are received.
Are they stored or not ? It should be written.

Also it would be nice to have an example that show how to make a request with specific cookies (node only ?). If not, then a sentence to say it is not possible.

**Comment by bitinn** [comment]
True, someone could add it to the doc (please submit PR against `v3` branch for now)

Also the current design is we don't store or pass cookies, you need to extract and pass them manually. This might change in future to allow users to set a cookie store.

https://github.com/bitinn/node-fetch#extract-set-cookie-header

**Comment by ramitmittal** [comment]
I want to work on this.

**Comment by bitinn** [comment]
Sure, you can open a PR against V3 branch readme.

(From my phone)

**Comment by ramitmittal** [comment]
The docs already contain information about extracting the set-cookie header. I have simply added a section mentioning the default behavior.
Please check PR #750
