### ISSUE TITLE
it's impossible to remove the user-agent header

### ISSUE THREAD

**Issue by UnCrevard** [node-fetch/node-fetch#704]
hello,

from code :

if (!headers.has('User-Agent')) {
	headers.set('User-Agent', 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)');
}

I can change it but I CAN'T REMOVE IT.

So maybe something like this :

fetch(url,{
headers:{
"user-agent":null
})

it's not a big deal but I need it😊

thanks

**Comment by Richienb** [comment]
@bitinn @xxczaki Should we incorporate this feature?

**Comment by xxczaki** [comment]
@Richienb Yes, I think this should be possible. I can create a PR for that ;)

**Comment by UnCrevard** [comment]
Great. Thank you !
