### ISSUE TITLE
Cannot send request body in HTML request

### ISSUE THREAD

**Issue by sslotsky** [node-fetch/node-fetch#721]
I'm currently using node-fetch to request HTML pages, parse them, and display some of their content on the page that I'm serving. This works fine for GET requests, but I also need to support a form POST, and when I try to add the request body, it doesn't come across. I've tried a couple different ways, shown below. Your docs seem to indicate that these should both be possible, but in both cases, the request body is empty when the other party receives it.

Forgive me if this is a dupe, I couldn't tell if this was the same thing being discussed [in this issue](https://github.com/node-fetch/node-fetch/issues/199) or in [the related PR](https://github.com/node-fetch/node-fetch/pull/603)

## JSON.stringify

```ts
          const response = await fetch(`${p.address}/${p.version}${req.path}`, {
            method: req.method,
            body: JSON.stringify(req.body),
            headers: {
              Accept: 'text/html',
              'Content-Type': 'x-www-form-urlencoded',
            },
          });
```

## URLSearchParams

```ts
          const response = await fetch(`${p.address}/${p.version}${req.path}`, {
            method: req.method,
            body: formData,
            headers: {
              'Transfer-Encoding': 'chunked',
              Accept: 'text/html',
              'Content-Type': 'x-www-form-urlencoded',
            },
          });
```

**Comment by Richienb** [comment]
@sslotsky 

> Forgive me if this is a dupe, I couldn't tell if this was the same thing being discussed [in this issue](https://github.com/node-fetch/node-fetch/issues/199) or in [the related PR](https://github.com/node-fetch/node-fetch/pull/603)

Correct.

Full `FormData` serialisation is coming in v3. For now, see https://github.com/node-fetch/node-fetch#post-with-form-data-detect-multipart.

**Comment by sslotsky** [comment]
@Richienb I wish you hadn't closed this so quickly as the workaround you proposed doesn't seem to satisfy the TypeScript definitions. Neither [form-data](https://www.npmjs.com/package/form-data) nor [formdata-node](https://www.npmjs.com/package/formdata-node) are working for me. The `FormData` class from form-data is missing properties contained by the `FormData` expected by `fetch` (I'm using `isomorphic-fetch`, not sure if that makes a difference), and the `stream` object exposed by formdata-node is a `Readable` where the type definitions seem to expect `ReadableStream<Uint8Array>`. Any further advice would be appreciated.

**Comment by Richienb** [comment]
@sslotsky Try using formdata-node which provides spec-compliant FormData and inherit its values into an instance of form-data.

Something like this:

```js
const FormData = require("formdata-node")
const FetchFD = require("form-data")

const myFormData = new FormData()
myFormData.set("a", "b")

const newFormData = new FetchFD()

for (let pair of myformData.entries()) {
    newformData.append(pair[0], pair[1])
}

// Start request...
```

We're working to implement `formdata-node` in v3 to be used directly so for now, hold tight!

**Comment by sslotsky** [comment]
But I can't pass an instance of `FormData` as the `body`, as I explained previously, so I don't understand how this helps. Maybe I'm missing something in your explanation.

**Comment by Richienb** [comment]
@sslotsky I see. I presumed your problem was not being able to use the full spec-compliant FormData. The only thing I can recommend at the moment is to sit tight for v3.

**Comment by sslotsky** [comment]
Thanks, any idea when v3 will be shipped?

**Comment by Richienb** [comment]
@sslotsky The first alpha *should* be released in March at the latest.
