### ISSUE TITLE
Confusion about whether utf8.encode(url) or not

### ISSUE THREAD

**Issue by chinesedfan** [node-fetch/node-fetch#722]
I read #245 by coincidence. It said that `node-fetch` should always encode `url` parameter.

But I have a counter-example. Please check https://runkit.com/chinesedfan/node-fetch-245.

As you can see, without `utf8.encode`, it works well. And with encoding, an error is thrown. Did I misunderstand something?

**Comment by jimmywarting** [comment]
fyi `url = new URL("http://смольный-институт.рф")` works

haven't been active for a while but think i remember node-fetch v3 will start using `new URL` in all places

**Comment by jimmywarting** [comment]
https://github.com/node-fetch/node-fetch/issues/668

**Comment by Richienb** [comment]
https://github.com/node-fetch/node-fetch/pull/701

**Comment by chinesedfan** [comment]
> without utf8.encode, it works well. And with encoding, an error is thrown.

Confirmed with the latest commit(d63d9a3c027e2e8b504c47fb3c57a4563eb40376) on branch 3.x. It behaves the same with the provided Runkit example.

**Comment by Richienb** [comment]
@chinesedfan #701 is yet to be merged.

**Comment by chinesedfan** [comment]
Sure. So everything is reasonable now. Thanks for your time.
