### ISSUE TITLE
v3-limits needs update

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#731]
We are working towards changing body to become either null or a stream.

https://github.com/node-fetch/node-fetch/blob/2e8c4aa8c25bb2593dac2e17e0899c6d494884c8/docs/v3-LIMITS.md#L15

If I remember correctly i have already removed all occurrence of string and replaced it with buffer to easier be able to change it for a stream later on. (#552)

Maybe should mention it in the upgrade guide too https://github.com/node-fetch/node-fetch/issues/210#issuecomment-382907994

**Comment by xxczaki** [comment]
Updated both the v3 limits & upgrade guide:

1f119f16432125468ed3becec49e0de53ec6b98c
acca53fede47ef2cd5abd40f998491562eb08f13
