### ISSUE TITLE
Coverage status not working

### ISSUE THREAD

**Issue by pensierinmusica** [node-fetch/node-fetch#732]
Hi,

It looks like the code coverage status indication of this project is not working.

The icon at the top of the readme file looks broken to me, and clicking on it doesn't work either:

https://github.com/node-fetch/node-fetch/blob/master/README.md

https://codecov.io/gh/bitinn/node-fetch

<img width="583" alt="screenshot" src="https://user-images.githubusercontent.com/3594037/74734704-62b2cb00-524f-11ea-9762-62f040212212.png">

Is there any way this could be fixed?

Thanks!

**Comment by Richienb** [comment]
This is because we transferred the repository from bitinn/node-fetch to node-fetch/node-fetch which broke the badge. The in-flux branch which has the correct badge is here: https://github.com/node-fetch/node-fetch/blob/3.x/README.md

**Comment by pensierinmusica** [comment]
@Richienb thanks for the quick reply, I see.

Shall I send a PR to update the readme in the master branch then?

Otherwise it looks broken.

Thx, cheers!

**Comment by Richienb** [comment]
@pensierinmusica You could. However, we'll be merging the v3 branch into master soon so it shouldn't be necessary.

**Comment by pensierinmusica** [comment]
Cool, thx @Richienb!
