### ISSUE TITLE
API for Node headers object

### ISSUE THREAD

**Issue by rlindner81** [node-fetch/node-fetch#734]
I may not be using fetch correctly here, but I would expect that there is some easy way to get a headers object as expected by the node API, 
https://nodejs.org/docs/latest-v12.x/api/http.html#http_message_headers
Using their example
```js
{
  'user-agent': 'curl/7.22.0',
  host: '127.0.0.1:8000',
  accept: '*/*' 
}
```

It seems you do have this internally via `exportNodeCompatibleHeaders`, but I would have expected this as a function on Headers similar to `.raw()`, because it is super useful and not every user should build their own. I wrote my own for now, but it feels wrong.

**Comment by Richienb** [comment]
We're trying to follow the fetch spec as closely as possible here. However, hooks that let you intercept the options _may_ be coming in v3.

**Comment by rlindner81** [comment]
I get that, but `.raw()` is not in the spec, so you already have a convenience function and I felt that this usecase to be compatible with the runtime you run on deserves one as well...

**Comment by Richienb** [comment]
v3 might already have something brewing. Just play the waiting game.

**Comment by rlindner81** [comment]
Ok, I will have another look when v3 is out then. Thanks for clarifying.
