### ISSUE TITLE
Joplin freezes upon invoking Node-Fetch for Syncing to server on Kernel 5.5.x

### ISSUE THREAD

**Issue by bedwardly-down** [node-fetch/node-fetch#735]
Ever since kernel 5.5 dropped on Arch Linux, there's been a surprising number of users that have experienced https://github.com/laurent22/joplin/issues/2518. It's now been reported that it's appearing on Solus, Fedora and Ubuntu. 

### What's been tested so far:

1. Upgrading to Electron 8, since that seems to be the recommended way to fix this issue in certain circumstances
2. Brief testing to see if the issue is related to Glibc

Latest Stable Release Without Electron 8: https://github.com/laurent22/joplin/releases/download/v1.0.179/Joplin-1.0.179.AppImage

### Steps To Reproduce:

1. `chmod +x Joplin-1.0.179.AppImage`
2. `./Joplin-1.0.179.AppImage --open-dev-tools --log-level debug` (to enable debug mode)
3. Open terminal
4. `tail -f $HOME/.config/jolin-desktop/log.txt`
5. Open Tools=>Options=>Syncronization 
6. Set to Filesystem sync
7. Set to local path (must be a full path)
8. Click Apply and Back
9. Create and Delete as many notes / todos as possible
10. Click Synchronize on the bottom corner or hit Ctrl + S
11. Keep repeating until the app freezes during sync

### Notes
1. Syncing to Filesystem uses the same processes as syncing to Dropbox, OneDrive or any of the other syncing services available in the dropdown menu. This is just the only one that is universally testable and runs into the same issue.
2. Joplin doesn't save notebooks / notes locally
3. All versions of Joplin use node-fetch-1.7.3. Hasn't upgraded to v2 due to possible API breaking changes

**Comment by bitinn** [comment]
How do you expect us to solve this problem given your information? This issue needs to be addressed by the downstream, there is nothing we can do unless there is a reproducible bug on Node.js runtime with node-fetch.

(From my phone)

**Comment by bedwardly-down** [comment]
No problem. I figured as much. Just wanted to shoot in the dark and see if maybe I can get some information. I'm testing it downstream by upgrading to verison 2.6.0 to see if it works.
