### ISSUE TITLE
ReadableStreams, consistent with fetch api standard

### ISSUE THREAD

**Issue by pkieltyka** [node-fetch/node-fetch#754]
Hi there, thanks for making node-fetch, it's awesome and super useful! 

One question though.. the purpose of node-fetch is to "bring fetch to nodejs", which is wonderful, but then shouldn't the goal be to always have api parity with the Web-standards in browsers?

for this reason, I can't understand why in node-fetch v3.x's upcoming version, the response body api for readable streams isn't consistent with the Web versions. Specifically, response.body.getReader() should function the same as in a Web browser. By doing so, this would allow http streaming apis to work with node-fetch as they do in Web browsers with normal fetch apis.

for some info on how to convert between formats, perhaps this would help as some example code between casting which would be very nice to have incorporated directly into node-fetch https://github.com/gwicke/node-web-streams

**Comment by jimmywarting** [comment]
v3 have became better at unify the `.body` to always be the same than it was before.

My recomendation for reading both whatwg/node streams are with async iterators

```js
// for web - simplefied inperfect polyfill that solves most of your problem
if (!ReadableStream.prototype[Symbol.asyncIterator]) {
  ReadableStream.prototype[Symbol.asyncIterator] = async function* () {
    const reader = this.getReader()
    while (1) {
      const chunk = await reader.read()
      if (chunk.done) return chunk.value
      yield chunk.value
    }
  }
}

// later
for await (let chunk of response.body) {
  console.log(chunk) // Uint8Array
}
```

closing this since there already is existing descussion around whatwg vs node streams

#647 
#387 
nodejs/node#22352
