### ISSUE TITLE
v3.0.0-beta.1 dist / package error

### ISSUE THREAD

**Issue by pkieltyka** [node-fetch/node-fetch#755]
hello,

I've been trying v3.0.0-beta.1 with TS and ts-node, however it fails to import.

The resolution (which I've tried + works), is to edit package.json, `"main"` key and set to `"dist/dist-src/index.js"`

**Comment by pkieltyka** [comment]
v3.0.0-beta.2 doesn't work either..

**Comment by Richienb** [comment]
@pkieltyka Those versions are deprecated. Don't use them.
