### ISSUE TITLE
upload of files do not work

### ISSUE THREAD

**Issue by Kaspanoombro** [node-fetch/node-fetch#756]
I have this code in one server that uploads a file as a formdata to another server:

```
                const fd = new FormData();
                let en;
                fd.append('i', FS.createReadStream("/tmp/trash.jpg"));
                try {
                    en = await FETCH("https://destiny.com", {
                        method: 'POST', body: fd, headers: fd.getHeaders()
                    }).then(r => {
                        return r.json();
                    });
                } catch (e) {
                    console.log(e);
                }
```
On the destiny, i use node HTTP and Formidable to receive the file but it gives error:
Error: Request aborted
```
    at IncomingMessage.<anonymous> (.../node_modules/formidable/lib/incoming_form.js:122:19)
    at IncomingMessage.emit (events.js:315:20)
    at abortIncoming (_http_server.js:536:9)
    at socketOnClose (_http_server.js:529:3)
    at Socket.emit (events.js:327:22)
    at TCP.<anonymous> (net.js:674:12)

```
But if i use the curl to make a upload from server 1 to server 2 it works perfectly:
curl -F "i=@/tmp/trash.jpg" https://destiny.com

I was using the package require but is obsolete. With require it was also working. Also, i have a developing computer in which the node-fetch works well. I do not understand what is the problem. All the nodes and npm packages are on the same versions.
Any suggestions? Thank you.

**Comment by Kaspanoombro** [comment]
I gave up and stop using node-fetch.

**Comment by drzraf** [comment]
I'm struggling too and I'd not be surprised to learn that there is a big node-fetch regression somewhere that breaks `FormData` + `readFileSync`

**Comment by vincenthawke** [comment]
@Kaspanoombro 
I had same issue today and found https://www.npmjs.com/package/isomorphic-form-data that solved it.

Example: 
```
async function sendFile() {
    return new Promise(async (resolve, reject) => {
        try {
            const formData = new FormData();  // requires isomorphic-form-data npm
            formData.append('file', fs.createReadStream("./yourfile"));
            let response = await fetch('https://yourwebsite.com/endpoint', {
                method: 'POST',
                body: formData
            });
            let res = await response.json(); //if server replied with json
            resolve(res);
        } catch (error) {
            reject(error);
        }
    });
}
```
