### ISSUE TITLE
Response does not support Blob as a body

### ISSUE THREAD

**Issue by uzer-ua** [node-fetch/node-fetch#757]
Response class does not correctly process body of type Blob

`new Response(new Blob(['content'])).json()` causes
**3.x**
`SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at consumeBody.call.then.buffer (node_modules/node-fetch/dist/dist-src/body.js:124:55)`
**2.x**
`FetchError: invalid json response body at undefined reason: Unexpected token o in JSON at position 1
    at node_modules/node-fetch/lib/index.js:239:32`

Calling `text()` returns response body as `[object Blob]`

**Comment by jimmywarting** [comment]
1. Your example fails in the browser also. - 'content' isn't valid json.
2. Your Blob implementation better have the new reading methods

```js
class Blob {
  async arrayBuffer () {
    return arrayBuffer
  }
  async text () {
    return text
  }
  stream () {
    return stream.Readable.from(x)
  }
}
```

**Comment by uzer-ua** [comment]
Indeed, with better Blob implementation everything works fine.
Sorry for false alarm.
