### ISSUE TITLE
Hi, is it possible to get the remote ip address from this package?

### ISSUE THREAD

**Issue by HenrikGr** [node-fetch/node-fetch#758]
As the title suggest, I want to check the headers in the response object, preferable in raw format?

Thanks in advance.
Henrik

**Comment by Richienb** [comment]
@HenrikGr Can't you just use https://developer.mozilla.org/en-US/docs/Web/API/Response/headers?

**Comment by HenrikGr** [comment]
Thanks, yes I can and my question was to abstract in the first place.
My use case is that I need to check the remoteAddress in the response but I now know it is not possible with getch or node-fetch.

Do you know about a solution for me?

**Comment by xxczaki** [comment]
@HenrikGr You can check headers like so (this is the method @Richienb suggested):

```js
fetch(url).then(response => {
	console.log(response.headers);
});
```

I'm not sure what `remoteAddress` is. If it is a header - the method above is probably the best for you.

**Comment by xxczaki** [comment]
If you want to get remote IP address, you can use a service like https://geoiplookup.io/ to do so.

**Comment by dzek69** [comment]
Others already provided a way to read headers, but I will respond to a question from a title:
> is it possible to get the remote ip address from this package?

Short answer: No.

Longer answer:
Be aware that servers do not return that information as a standard. It's the client job to get a IP adress from a domain name, then send a request to an IP address with `Host` header specified. `fetch` doesn't do that either, as it relies on node's `http` module.

You can do DNS resolve manually before each request, you can wrap `fetch` with some method injecting that information into a response or probably creating a custom http agent is another way to achieve the same: https://github.com/node-fetch/node-fetch#custom-agent

**Comment by HenrikGr** [comment]
Thank you all.

I solved it this time by parsing the attribute x-forwarded-for in the http header on the server side and used a similar solutions such as xxxczaki suggested on the client side.

dsek69, thanks for your answer, will keep that in mind for the future.

**Comment by xxczaki** [comment]
Closing as it seems that the initial question was answered. Please reopen if necessary ;)
