### ISSUE TITLE
IE11 - SCRIPT5007: Unable to get property 'bind' of undefined or null reference

### ISSUE THREAD

**Issue by githubnikola** [node-fetch/node-fetch#765]
Hi,

I keep getting this error which prevents page from loading

![image](https://user-images.githubusercontent.com/29466660/78261326-651b6c80-74ff-11ea-9343-8b138b1fbf09.png)

![image](https://user-images.githubusercontent.com/29466660/78261414-7f554a80-74ff-11ea-95e5-dc9c5ac34f2b.png)

Is there something I'm missing to do?
I'll provide any additional info you might need.

Thanks,
Nikola

**Comment by Richienb** [comment]
@githubnikola 

`node-fetch` is only built to work with Node.js, as the name states. For isomorphic usage in the browser, use https://github.com/lquixada/cross-fetch

**Comment by githubnikola** [comment]
Despite being used only with Node.js, Chrome doesn't fail to load the same page.
Do you have any idea why is that the case?
Thanks.

**Comment by Richienb** [comment]
@githubnikola Webpack polyfills the entire HTTP library to make it work.
