### ISSUE TITLE
Looking for Issue and PR reviewers (2020)

### ISSUE THREAD

**Issue by bitinn** [node-fetch/node-fetch#772]
Hey folks,

There have been an increased amount of PRs and issues since our alpha release of node-fetch v3, while our key maintainers have been mostly busy in life.

I would like to use this opportunity to recruit a few more issues and PR reviewers as our core contributors, so that node-fetch is still taken care of while we are away.

We know node-fetch has been an important tool for a lot of users; but personally, my day-to-day job no longer require me to use node.js, so my ability to keep up with latest development in the scene will only reduce overtime.

I think it's a good time for me to fade into background (one could argue I already have) and leave node-fetch to our community of maintainers.

So, if you are invested or simply care about the node-fetch ecosystem, please feel free to reply and help :)

(PS: I have added @xxczaki to the node-fetch npm owner list, so that work on v3 can still continue without me.)

**Comment by eaviles** [comment]
@bittin I would love to help!

**Comment by NotMoni** [comment]
@Bitinn count me in! It would be a honor to contribute to node-fetch as a PR reviewer or anything else needed 😁

**Comment by tbalmeida** [comment]
Hi, if there's any way that I could contribute as a junior dev, please count me in.

**Comment by bitinn** [comment]
@eaviles @NotMoni @tbalmeid Thx for applying, we will get back to you soon.

@xxczaki @Richienb do you mind adding these fine folks and organize a list of todo tasks so they can take a look? I haven't look into permission settings for GitHub org, it would be great for you to figure it out too :)

**Comment by xxczaki** [comment]
@eaviles @NotMoni @tbalmeida 

I invited you all to the @node-fetch/reviewers team. I will try to create a list of todo tasks later today :smile:

**Comment by NotMoni** [comment]
Sure mate. 😀

**Comment by JefferyHus** [comment]
I am able to help, and if there is a way, just tag me on it :)

**Comment by curtisjohnson1** [comment]
Hi there, I'm happy to help if you need an extra pair of hands and a keyboard that goes with them!

**Comment by larson-carter** [comment]
@bitinn Count me in! I wouldn't mind helping maintain it!

**Comment by Richienb** [comment]
@JefferyHus @curtisjohnson1 @larson-carter I invited you to the @node-fetch/reviewers team. For now, take a look at the open issues, especially the older ones.

**Comment by larson-carter** [comment]
@Richienb I accepted. I'm going to work on issues right now!

**Comment by tinovyatkin** [comment]
@bitinn I'm already helping, but I think I will be more useful as part of the team if you want to accept me.

**Comment by Richienb** [comment]
@tinovyatkin Invited you!

**Comment by gyojkim-sh** [comment]
@bitinn @Richienb I love to help if there is room to join.

**Comment by iamcap** [comment]
@bitinn @Richienb I love to help if there is room to join.

**Comment by ghinks** [comment]
Hello, an issue was raised. On the [package maintenance repo](https://github.com/nodejs/package-maintenance/issues/360#issue-616954118). We see that you have managed to get some support. If you are not familiar with this group. We are writing governance rules and formulating best practices for package maintenance. We are also helping out a few trial projects. We see that you have managed to keep your community vibrate. Do you still need help?

**Comment by xxczaki** [comment]
> Do you still need help?

@ghinks No, I think we have enough people on the @node-fetch/reviewers team, at least for now :smile:

**Comment by ghinks** [comment]
excellent, if you need help please reach out to the package maintenance team.

**Comment by xxczaki** [comment]
I will close this issue, we can reopen them if we will need more reviewers.
