### ISSUE TITLE
When using fetch to connect to the websocket server, there has been no response, no failure, and no success for long time.

### ISSUE THREAD

**Issue by masx200** [node-fetch/node-fetch#773]
When using fetch to connect to the websocket server, there has been no response, no failure, and no success for long time.

```js
var fetch=require('node-fetch')

fetch("http://localhost:2000/websocket", {
  "headers": {
    'Upgrade': 'websocket',
    'Connection': 'Upgrade',
    "accept-language": "zh-CN,zh;q=0.9",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "sec-websocket-extensions": "permessage-deflate; client_max_window_bits",
    "sec-websocket-key": "uHUOnXD3pfLwh2XZXK447A==",
    "sec-websocket-version": "13"
  },
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
}).then(console.log,console.log)
```

But it can be connected successfully with websocket.

```js
new WebSocket('ws://localhost:2000/websocket')
```

If you use fetch to connect to the websocket server, you should report an error.

**Comment by JefferyHus** [comment]
`node-fetch` is replica of `window.fetch` API. The API only communicate through the HTTP protocol. As of this moment the request and ambiguous comparison between `WebSocket` API and ` fetch` API have been discussed here https://github.com/whatwg/fetch/issues/235

Closing this issue as it is out of what the package is designed for.
