### ISSUE TITLE
GitHub Api authentification is not working

### ISSUE THREAD

**Issue by EV3R4** [node-fetch/node-fetch#774]
Hello, i wanted to use the GitHub Api but i couldn't find a working solution to authentificate.

I tried to use the following code:
```javascript
const headers = new fetch.Headers();
headers.set('Authorization', `token ${config.github.accesstoken}`);
fetch(url, headers).then((res) => {
    if (res.status != 200) {
        console.log(`${res.status}: ${res.statusText}`);
        return;
    }
}
```

But it returns:
403: rate limit exceeded

**Comment by Richienb** [comment]
@EV3R4 Exceeding your rate limit is nothing to do with node-fetch.

**Comment by EV3R4** [comment]
Yes, but i asked because i think i maybe set the headers wrong.

**Comment by Richienb** [comment]
@EV3R4 Wait until your rate limit has renewed and try again.

Here's the proper way to set headers:

```js
fetch(url, {
	headers: {
		'Authorization': `token ${config.github.accesstoken}`
    }
}).then((res) => {
    if (res.status != 200) {
        console.log(`${res.status}: ${res.statusText}`);
        return;
    }
}
```

**Comment by EV3R4** [comment]
Thanks!
