### ISSUE TITLE
doesn't correctly handle multiple `content-type` values

### ISSUE THREAD

**Issue by char0n** [node-fetch/node-fetch#783]
I found a peculiar issue of incompatibility of this library comparing to native browser fetch version. Affected **version 2.6.0**

Steps to reproduce:

**1.) Create simple node server and run it**
```js
const http = require('http');

const requestListener = function (req, res) {
  res.setHeader('Cookie', ['one=1', 'two=2']);
  res.setHeader('Content-Type', ['text/plain', 'application/json']);
  res.writeHead(200);
  res.end('Hello, World!');
}

const server = http.createServer(requestListener);
server.listen(8080);
```

**2.) Fetch the server**

`In browser`
```js
fetch('http://localhost:8080').then(r => r.headers).then(h => h.get('Content-Type')).then(console.dir);
// text/plain, application/json
```

`node-fetch`
```js
fetch('http://localhost:8080').then(r => r.headers).then(h => h.get('Content-Type')).then(console.dir);
// text/plain
```
As you can see, `node-fetch` doesn't correctly handle multiple headers with the same name.

**Comment by xxczaki** [comment]
I was able to reproduce this on both `2.6.0` and `3.0.0-beta.5`.

> As you can see, node-fetch doesn't correctly handle multiple headers with the same name.

This is not true, because it works fine with the `cookie` header:
```js
fetch('http://localhost:8080').then(r => r.headers.get('cookie')).then(console.dir); //=> 'one=1; two=2'
```

Also, it looks like this issue is not related just to the `get()` method:
```js
fetch('http://localhost:8080').then(r => r.headers.raw()).then(console.dir); //=> [ 'text/plain' ]
```

**Comment by xxczaki** [comment]
This works correctly:
```js
const headers = new Headers({
	'Content-Type': ['text/plain', 'application/json']
});

headers.get('Content-Type') //=> 'text/plain,application/json'
headers.raw()['Content-Type'] //=> 'text/plain,application/json'

**Comment by char0n** [comment]
> This is not true, because it works fine with the cookie header:

`Cookie` header is special case, and is directly serialized by server and instead of two headers, one serialized header is sent.

Another special case is `Set-Header`. [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2.2) says it should be handled in specific manner. And it is, at least by browser native `fetch` where headers will never contain entry for `set-cookie`. 

Reason for both `Cookie` and `Set-Cookie` is simple. They can contain `,` character to delimit parts of header info: 
`Cookie-set: language=pl; expires=Sat, 15-Jul-2017 23:58:22 GMT; path=/; domain=x.com `

> headers.get('Content-Type') //=> 'text/plain,application/json'

I don't think this is correct either. [Specification](https://fetch.spec.whatwg.org/#concept-headers-append) says that serialized headers should `0x2C` `0x20` which translates to `, ` (comma followed by single space)

**Comment by char0n** [comment]
Seems that it is caused by this project special handling of `Content-Type` header. Other headers work as expected and return values of headers separated by `0x2c` and `0x20`.

Regarding the code fragment:
```js
const headers = new Headers({
	'Content-Type': ['text/plain', 'application/json']
});
```
..I IMHO this is unexpected init object. The array of `['text/plain', 'application/json']` is passed later inside `append` method which serializes it into `text/plain,application/json` as it tries to stringify the value of it's second argument (correctly).
