### ISSUE TITLE
Is there a way to remove "TypeError: Expected signal to be an instanceof AbortSignal"? 

### ISSUE THREAD

**Issue by 1c7** [node-fetch/node-fetch#784]
https://github.com/node-fetch/node-fetch/blob/master/src/request.js?ts=2#L120

## This line causing problem
![image](https://user-images.githubusercontent.com/1804755/80098326-40b32d00-859f-11ea-9493-c55d8053d663.png)

## Let's check out ths `isAbortSignal` function
![image](https://user-images.githubusercontent.com/1804755/80098053-d4382e00-859e-11ea-82ab-4d99084ee448.png)

## When would it happen?
After Webpack bundle my code, code minification would change the name,   
``object[NAME] === 'AbortSignal'`` is not true anymore
so this error would pop up, 
The only solution is to turn off code minification
There should be a better way than this

# Propose (What to do next)
1. Delete this part altogether, don't check the name
2. Don't compare with string  'AbortSignal' like this `object[NAME] === 'AbortSignal'`,
in Ruby we have `class.name` to get the class name, I am not sure what's the equivalent in JS

[Maybe this StackOverflow question helpful: How to get a JavaScript object's class?](https://stackoverflow.com/questions/1249531/how-to-get-a-javascript-objects-class)

Thanks

**Comment by 1c7** [comment]
I can not provide reproducible code for now. sorry.

### How I encounter this problem?
I am building a Electron.js app that can upload file to Azure Storage.
using `"@azure/storage-blob": "12.1.1"`
everything works fine in development, but after I bundle the code for production,  
this error would popup.
After tracking it, I found out it's `node-fetch` rasing this error

**Comment by 1c7** [comment]
I hope this problem can be fixed because I want to turn on code modification for my electron.js main process code.
for now I have to turn off
(file size 898kb -> 2.3mb)

**Comment by Richienb** [comment]
Using `Symbol.toStringTag` was supposed to prevent this specific problem.

**Comment by 1c7** [comment]
@Richienb Thank you for helping, so should I send a PR or? What's the next step?

**Comment by Richienb** [comment]
@1c7 PRs are welcome to fix this issue.

**Comment by 1c7** [comment]
@Richienb 
Even though just changing this one line, 
I have to run all the test and make sure not to break other things, 
and understand how other pieces works
it's still quite complicated, 
would you mind helping me change this 
or let other core members who are familiar with these codes to fix it?

Really appreciate that, Thanks!

**Comment by 1c7** [comment]
### Enviroment
* Electron.js 8.0.0
* "vue-cli-plugin-electron-builder": "^1.4.5"
* "@azure/storage-blob": "12.1.1"

## Solution：
This can still minify code, 
but, without mangle with class name and function name

`vue.config.js`
```javascript
const TerserPlugin = require('terser-webpack-plugin');
const TerserPlugin = require('terser-webpack-plugin');
module.exports = {
 pluginOptions: {
  electronBuilder: {
   chainWebpackMainProcess: config => {
    config.plugins.delete('uglify')
    config.plugin('uglify').use(TerserPlugin, [{
     terserOptions: {
      mangle: false,
      sourceMap: true,
      compress: false,
      keep_classnames: true,
      keep_fnames: true,
      output: {
       comments: false,
      },
     }
    }])
    config.optimization.minimize(false);
    console.log(config.toString())
   },
  }
 },
}
```

## Result
![image](https://user-images.githubusercontent.com/1804755/80128789-c13a5380-85c8-11ea-8b78-07c3edbdbda5.png)

**Comment by RuurdBijlsma** [comment]
I couldn't get the TerserPlugin to work, so I fixed it another way, maybe someone else has a use for this as well. I wrapped the abort signal in the following class: https://gist.github.com/RuurdBijlsma/66e31f47c1e2f2c14b4652b43f65a8fc

So instead of passing abortController.signal to node-fetch or a googleapis request, I would pass new AbortSignal(abortController.signal), the main thing here is statis get name() which returns the proper name even when minimization is fully enabled

**Comment by UrielCh** [comment]
RuurdBijlsma sugarcode looks nice, but, can not be use in a typescript project:
The Typescript transpiler refused to overwrite the `name` getter with the Error:

    Static property 'name' conflicts with built-in property 'Function.name' of constructor function 'AbortSignal'.ts(2699)

Setting `keep_classnames: true` in the TerserPlugin works, but this change is applied to all classnames, I do not see any option in the TerserPlugin to provide a set of classname to keep untouched.

**Comment by turansky** [comment]
WA, which save single name `AbortSignal`

```Kotlin
// keep_classnames is required to workaround node-fetch Expected signal to be an instanceof AbortSignal
config.optimization = {
  minimizer: [
    new TerserPlugin({
      cache: true,
      parallel: true,
      sourceMap: true, // Must be set to true if using source-maps in production
      terserOptions: {
        // https://github.com/webpack-contrib/terser-webpack-plugin#terseroptions
        mangle: false,
        sourceMap: true,
        // compress: false,
        keep_classnames: /AbortSignal/,
        keep_fnames: /AbortSignal/,
        output: {
          beautify: true,
          indent_level: 1
        }
      }
    }),
  ],
};

```

[Source](https://github.com/burrunan/gradle-cache-action/blob/main/cache-action-entrypoint/webpack.config.d/config.js)

**Comment by domgenv** [comment]
For those using [esbuild](https://esbuild.github.io/), an equivalent solution to [1c7's solution](https://github.com/node-fetch/node-fetch/issues/784#issuecomment-618527886) is to set the "keepNames" option to true.

https://esbuild.github.io/api/#keep-names

**Comment by raulfdm** [comment]
I came up to this problem (using Esbuild) and fixed that by making the package that uses `node-fetch` (in my case `@sanity/client`) as external resource or in other words, excluding the package from the bundling itself:

```js
// build.js

// ...
const baseConfig = {
  external: ['@sanity/client', /* ... other external dependencies ... */]
}
```

I tried the suggestion from @domgenv to set `keepNames` to true but unfortunately it didn't work.

**Comment by Gbr22** [comment]
https://github.com/node-fetch/node-fetch/issues/784#issuecomment-618527886 How could I achieve this with nuxtjs?

**Comment by joshkel** [comment]
A bit more information, in case anyone is curious: As mentioned in https://github.com/node-fetch/node-fetch/issues/784#issuecomment-618372321, current versions of node-fetch use `Symbol.toStringTag`, so they should work just fine, even after minification. node-fetch 2.x (the most recent pre-ESM version, and the version used by, e.g., `@azure/storage-blob` 12.12.0) still checks against `name`, so it's affected by this (and can be fixed by adding one of the keep-names options).

**Comment by yantze** [comment]
Node.js 16.x internal AbortController can use in node-fetch 2.x.

**Comment by vlinder** [comment]
For reference, when using terser with `@swc/core` this is the minimal config to fix this issue in your webpack config. It does not appear to support regexes for `keep_classnames` nor `keep_fnames`

```js
    optimization: {
      minimizer: [
        new TerserPlugin({
          minify: TerserPlugin.swcMinify,
          terserOptions: {
            mangle: {
              // older versions of node-fetch requires AbortSignal to be untouched.
              // https://github.com/node-fetch/node-fetch/issues/784
              reserved: ['AbortSignal'],
            },
          },
        }),
      ]
    },
```

**Comment by dimaboychev** [comment]
FYI if anyone stumbles on this. I get this error in nextjs 14 application with "@azure/storage-blob": "^12.17.0":
"Blob Upload Error TypeError: Expected signal to be an instanceof AbortSignal".

To bypass the error you can disable server minification via next.config.js file like this:
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverMinification: false
  }
}

module.exports = nextConfig
```

**Comment by shinebayar-g** [comment]
If anyone is using https://github.com/actions/toolkit/tree/main/packages/artifact v2 with esbuild and facing this issue, using `--keep-names` (https://esbuild.github.io/api/#keep-names) flag seems to be fixing the issue. Thanks to the above linked issue.
