### ISSUE TITLE
Header.forEach incosistent with standard fetch API

### ISSUE THREAD

**Issue by char0n** [node-fetch/node-fetch#790]
Following fragment will have different results depending if it runs in browser or in node using `node-fetch`.

```js
const headers = new Headers() // eslint-disable-line no-undef
headers.append('Authorization', 'Basic hoop-la')
headers.append('Authorization', 'Advanced hoop-la')

headers.forEach((headerValue, header) => {
  console.dir(headerValue);
}); 
```

### Result in browser
```
Loop1: Basic hoop-la, Advanced hoop-la
```

### Result with node-fetch in node.js

```
Loop1: Basic hoop-la
Loop2: Advanced hoop-la'
```

The distinction is quite big and building inter-op doesn't seem to be the right thing to do (doing ifing). Could we fix that in v3.x? It's already major release and contains breaking changes. The browser joins the header with multiple values according to [spec](https://fetch.spec.whatwg.org/#concept-headers-append) before it feeds it to `forEach` function. `node-fetch` iterates all the values instead.

**Comment by bitinn** [comment]
I might be missing something here, but isn't this what you want?

https://github.com/node-fetch/node-fetch/blob/master/test/headers.js#L31-L50

**Comment by char0n** [comment]
You're right. Thanks. I'm using version 1.7.3 which has the behavior I describe. Later major versions have expected behavior.
