### ISSUE TITLE
OAuth implementation, should I make a PR?

### ISSUE THREAD

**Issue by siscia** [node-fetch/node-fetch#801]
Folks, 

I develop a little bit of code to support OAuth1.0 (most notably used by twitter).

Should I make a PR against your codebase or I keep it as separate package?

Cheers,

**Comment by Richienb** [comment]
The point of node-fetch is to act as a ponyfill for the browser fetch API. Therefore, OAuth shouldn't be built-in.

**Comment by siscia** [comment]
Then I close the issue!
