### ISSUE TITLE
Switch to GitHub Org Sponsor?

### ISSUE THREAD

**Issue by bitinn** [node-fetch/node-fetch#807]
I haven't looked into it, but seems like it would have much better integration than Open Collective.

We could offer issue-based sponsor if it's a thing, otherwise just getting some small monthly or quarterly contribution would be fine too :)

**Comment by xxczaki** [comment]
Yeah, I was thinking about that as well. We can still use Open Collective as our fiscal host.

I can apply our organization to the waitlist. In order to do so I would need e-mail addresses of all @node-fetch/core members. You can send them here or to `a@kepinski.me` :smile:

**Comment by xxczaki** [comment]
In terms of issue-based sponsorship, [Tidelift](https://tidelift.com/about/lifter) is also pretty popular.

**Comment by bitinn** [comment]
Mine: `bitinn@gmail.com`

We could add tidelift too, but it's up to the org members. The less friction the better (unless we are seriously doing funding drive, it's up to people's kindness :)

**Comment by NotMoni** [comment]
Tidelift is also very popular for npm packages. But it's up to you, because Github sponsors are embedded into the Github page and system

**Comment by JefferyHus** [comment]
I think that it is a good step. Github sponsor is smoother and easier for github users to use it.
Mine: `jefferytutorials@gmail.com`

**Comment by Richienb** [comment]
Mine: `richiebendall@gmail.com`

**Comment by gr2m** [comment]
Mine is `gregor@martynus.net`. Let me know once you sign up, I know most of the folks at Open Collective. Would be nice to get it set up in time for v3

**Comment by xxczaki** [comment]
Ok, I sent the application :smile:

**Comment by xxczaki** [comment]
In terms of Tidelift, one of the cool things about them is the security contact & policy (see https://github.com/node-fetch/node-fetch/issues/813). However, I'm not sure about how to configure Tidelift for a project with multiple maintainers. I sent them an email about this, will post updates here once I receive a response.

**Comment by jimmywarting** [comment]
jimmy@warting.se

**Comment by xxczaki** [comment]
After thinking more about Tidelift, I came to the conclusion that it might not be the right time to integrate it. It's something more than just a funding opportunity and requires legal agreements to be signed. So I think for now we will stick with Open Collective and (hopefully soon) Github Sponsors.

**Comment by Richienb** [comment]
We're accepted on GitHub Sponsors!

// @xxczaki

**Comment by NotMoni** [comment]
![image](https://user-images.githubusercontent.com/40552237/83146815-ceb19480-a0c4-11ea-8838-81635d36cc26.png)

🎉 💯

**Comment by xxczaki** [comment]
Hmm, I don't think we actually got accepted yet. The current sponsor button was already there, with a link to our Open Collective. AFAIK Github Sponsors for Organizations would allow us to use the actual sponsor feature (available for individuals), but with Open Collective as the fiscal host. I would also receive an e-mail and Stripe configuration would be required.

https://docs.opencollective.com/help/collectives/github-sponsors

**Comment by NotMoni** [comment]
OHHHH ok. :(

**Comment by xxczaki** [comment]
@node-fetch/core I've set up IssueHunt for the repository and applied for a bounty for two issues (#342 and #210). I sent all of you an invitation link (to your email addresses).

**Comment by Richienb** [comment]
@xxczaki We got accepted but we need to fill in some information to confirm it https://github.com/sponsors/node-fetch/signup

**Comment by Richienb** [comment]
@xxczaki ↑↑↑

**Comment by jimmywarting** [comment]
yea.
