### ISSUE TITLE
Update (c) Copyright year 

### ISSUE THREAD

**Issue by NotMoni** [node-fetch/node-fetch#812]
**Shouldn't we update the year?**

![image](https://user-images.githubusercontent.com/40552237/82559938-7287c700-9b3e-11ea-87a2-b9b6deb9b52f.png)

**Comment by Kharanshu31** [comment]
i will do it but where are the starting files

**Comment by NotMoni** [comment]
in the repo ?

**Comment by Kharanshu31** [comment]
How to run the code in my machine?

**Comment by NotMoni** [comment]
In a web browser, navigate to https://nodejs.org/en/download/. Click the Windows Installer button to download the latest default version. At the time this article was written, version 10.16.0-x64 was the latest version. The Node.js installer includes the NPM package manager.

**Comment by NotMoni** [comment]
1. Once the installer finishes downloading, launch it. Open the download link in your browser and click the file. Or, browse to the location where you have saved the file and double-click it to launch.

2. The system will ask if you want to run the software – click Run.

3. You will be welcomed to the Node.js Setup Wizard – click Next.

4. On the next screen, review the license agreement. Click Next if you agree to the terms and install the software.

5. The installer will prompt you for the installation location. Leave the default location, unless you have a specific need to install it somewhere else – then click Next.

6. The wizard will let you select components to include or remove from the installation. Again, unless you have a specific need, accept the defaults by clicking Next.

7. Finally, click the Install button to run the installer. When it finishes, click Finish.

**Comment by NotMoni** [comment]
That's how you install NodeJS and then run node-fetch

**Comment by NotMoni** [comment]
Thanks

**Comment by Bonepoppa1** [comment]
https://github.com/node-fetch/node-fetch/issues/812#issue-622471844

**Comment by Bonepoppa1** [comment]
> **Shouldn't we update the year?**
> 
> ![image](https://user-images.githubusercontent.com/40552237/82559938-7287c700-9b3e-11ea-87a2-b9b6deb9b52f.png) 2020

**Comment by Richienb** [comment]
We did.

**Comment by NotMoni** [comment]
ok
