### ISSUE TITLE
Bug: Differences in package installation locations of devDependencies based on package manager

### ISSUE THREAD

**Issue by Richienb** [node-fetch/node-fetch#830]
**Reproduction**

Steps to reproduce the behaviour:

1. Run `yarn`
2. Run `yarn test`

Since yarn installs binaries like c8 to a different directory than npm, it can't find the absolutely declared directories in the `test` script.

**Expected behaviour**

The binary directories shouldn't be absolutely declared but detecting them or using esm would affect coverage. We should either switch back to nyc or use Node.js v13.2.0 for testing which has esm module support enabled by default.

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | [`a6a933fa5a`](https://github.com/node-fetch/node-fetch/tree/a6a933fa5a1fd673bba332e20628a44245fecdce)
| node             | 12.14.1
| npm              | 6.13.4
| yarn             | 1.19.1
| Operating System | Windows 10 v1903

**Comment by xxczaki** [comment]
Using Node.js v13.2.0 or even later sounds good to me.

**Comment by xxczaki** [comment]
Actually, is that something we should care about? We do not use yarn nor we ever declared compatibility with it.

Sure, it would be awesome if people could use it when developing new features, but if that means we would need to make some weird workarounds, I don't think it's worth it.

**Comment by tinovyatkin** [comment]
@Richienb there are also PnP mode in Yarn@2 that doesn't create `node_modules` at all and `pnpm` package manager if you are seeking complete intimacy with all possible managers. But I agree with @xxczaki - we don't use Yarn at this project neither declare any compatibility with a non-default manager and this issue affects only developers participating in this module - so, we just can set team rules and relax.

**Comment by NotMoni** [comment]
Agree 100% w/t @tinovyatkin 🦄
