### ISSUE TITLE
Bug: Build artifact at Beta 6 is different from `npm run build`

### ISSUE THREAD

**Issue by tinovyatkin** [node-fetch/node-fetch#836]
```js
// `npm run build` output dist/index.cjs

'use strict';

exports = module.exports = fetch;

function fetch(url, options_) { 
// ...
}
```

vs

```js
// published 3.0.beta-6 dist/index.cjs
'use strict';

exports = module.exports = fetch;

const fetch = (url, options_) => {
// ..
}
//
```

Not sure if there is an extra pre-publishing step performed, but as a result `beta.6` is completely broken.

**Comment by tinovyatkin** [comment]
That was this commit: https://github.com/node-fetch/node-fetch/commit/fa627f4b0cc60570037c2fc8db88b1771ae185b4#diff-1fdf421c05c1140f6d71444ea2b27638R32

@xxczaki we need to roll back this change and re-publish.
I'll create a test for compiled commonjs output to prevent that in the future.

PS: Hate XO by the way, 43 dependencies!

**Comment by tinovyatkin** [comment]
That was a huge PR, changing across 12 files and merged after just one approval - we should set policy on that...

**Comment by xxczaki** [comment]
@tinovyatkin Sorry for that, I wasn't aware that the new Rollup setup needs a specific export order. Shall we release the fix as `3.0.0-beta.7` or something like `3.0.0-beta.6-fiximport`?

**Comment by xxczaki** [comment]
@tinovyatkin Actually, in terms of the PR policy - I saw some repositories having a Github Action, which automatically assigns an organization team based on the files, which the PR modifies. Maybe we could try and set up something here.

**Comment by xxczaki** [comment]
Fix: https://github.com/node-fetch/node-fetch/commit/079b11e2577f0cb0b1f1e6e0e42dc6079f4cd2f9

**Comment by xxczaki** [comment]
Released [`v3.0.0-beta.6-exportfix`](https://github.com/node-fetch/node-fetch/releases/tag/v3.0.0-beta.6-exportfix) and deprecated `3.0.0-beta.6`. I will leave this issue open for further discussion regarding the PR policy and tests.

**Comment by tinovyatkin** [comment]
@xxczaki the issue wasn't related to Rollup - it can export as an arrow function. The problem was that by changing from a `function` to `const` you break the hoisting, so, `fetch` becomes undefined on top of the file.

**Comment by tinovyatkin** [comment]
> I saw some repositories having a Github Action, which automatically assigns an organization team based on the files, which the PR modifies. Maybe we could try and set up something like this here.

That can be done with https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners, no Action needed

**Comment by xxczaki** [comment]
Closing this in favor of https://github.com/node-fetch/node-fetch/issues/837
