### ISSUE TITLE
Feature request: require 2 reviews for approvals

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#837]
I think things have been moving a bit too quickly and some stuff merged too fast. What would you say about protecting it a bit more?

https://github.blog/2018-03-23-require-multiple-reviewers/

I propose this settings. but it can only be done by @bitinn 

- [x] Require pull request reviews before merging (2-3 ppl)
- [x] Dismiss stale pull request approvals when new commits are pushed
- [x] Include administrators

**Comment by xxczaki** [comment]
We could also use the CODEOWNERS file, as suggested in #836.

**Comment by Richienb** [comment]
Added review requirement!

**Comment by tinovyatkin** [comment]
@Richienb is it 3 or 2 reviewers required now? I believe 3 reviewers requirement will slow too much or the project will need to hire way more reviewers with write access (but again, a non-competent or non-attentive reviewer can hurt even more).

**Comment by Richienb** [comment]
We'll see how it goes. Right now, 3 seems like a good amount.

**Comment by jimmywarting** [comment]
Yeah, lets see how 3 works out first

**Comment by LinusU** [comment]
I have subscribed to all repos under `node-fetch/*` so should be able to provide reviews in a timely fashion ☺️

**Comment by NotMoni** [comment]
Same here 🦄
