### ISSUE TITLE
Apply for Discord Open Source

### ISSUE THREAD

**Issue by NotMoni** [node-fetch/node-fetch#840]
https://discord.com/open-source

We can get a vanity link, such as `discord.gg/nodefetch` or `discord.gg/fetch`.

It can benefit the server also. 
The server also need some cleaning up btw.

**Comment by Richienb** [comment]
What cleanup do you suggest? Also, how do we get verified?

**Comment by NotMoni** [comment]
Over here. https://github.com/discord/discord-open-source
For the server, we can add more roles, post-release on Discord stuff like that
a help channel.
a feature request channel and stuff like that.

**Comment by Richienb** [comment]
@NotMoni We already have a help channel and the main chat is used for feature requests. As for roles, what do you suggest?

**Comment by xxczaki** [comment]
As far as I can tell node-fetch qualifies with all the [acceptance criteria](https://github.com/discord/discord-open-source#acceptance-criteria). Shall I make a PR to add us to the list?

If so, I would need a logo with [the correct dimensions](https://github.com/discord/discord-open-source#adding-your-project) (cc @Richienb, I think you made the current one :smile:).

**Comment by NotMoni** [comment]
Logo looks awesome.

**Comment by NotMoni** [comment]
> @NotMoni We already have a help channel and the main chat is used for feature requests. As for roles, what do you suggest?

Oh ok then. I think we can close this once we get verified.

**Comment by NotMoni** [comment]
I know for a fact discord would approve, because they use node-fetch as one of the dependencies.

![Screen Shot 2020-05-29 at 5 14 31 PM](https://user-images.githubusercontent.com/40552237/83306049-dd38a280-a1cf-11ea-8a07-3f7fce6882e8.png)

**Comment by Richienb** [comment]
Discord icon svg:

```svg
<svg width="72" height="72" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><defs><clipPath id="b"><use xlink:href="#a" clip-rule="evenodd"/></clipPath><path id="a" d="M0 0h72v72H0z"/></defs><g clip-path="url(#b)" fill="#FFF"><use xlink:href="#a" fill-opacity="0"/><path d="M37.075 53.805h-.7l-17.15-16.1c-1.7-1.6-4.05-4.65-4.05-4.65s.5 3.75.5 6.2v14.25h-6.55v-34.3h.7l17.15 16.1c1.65 1.55 4 4.65 4 4.65s-.45-3.85-.45-6.2v-14.25h6.55v34.3zm14.1-.3h-7v-34h21.9v6.15h-14.9v11.25h13.55v6.25h-13.55v10.35z"/></g></svg>
```

Invite code: `Zxbndcm`

**Comment by Richienb** [comment]
https://github.com/discord/discord-open-source/pull/240

**Comment by CyberiumShadow** [comment]
Just want to note that getting added to the list of open source projects on Discord doesn't grant the vanity link benefits.

You need to contact discord via this email address to become a Verified server opensource@discord.com
