### ISSUE TITLE
Question: how to debug hang in node-fetch? (likely environmental issue)

### ISSUE THREAD

**Issue by JudahGabriel** [node-fetch/node-fetch#860]
On my Windows 10 dev box, Node 12.17.0, I'm seeing the following code hang:

```js
let result = await fetch("https://sadchonks.com/kitteh-512.png"); // success, 200
let buffer = await result.buffer(); // This hangs, never finishes. No errors, no result. Just hang.
```

I'm trying to figure out why this hangs. Stepping into the debugger, I reach into [consumeBody](https://github.com/node-fetch/node-fetch/blob/master/src/body.js#L152) function, but neither `body.on('error', ...)` nor `body.on('data', ...)` never fires:

![image](https://user-images.githubusercontent.com/312936/83808569-db585e80-a669-11ea-9b5f-2a0f1a82d4a5.png)

I've also tried de-asyncing my code by using .then(...) chains without async. Still no dice; it hangs on the same call to `.buffer()`.

Any suggestions for debugging this hang?

**Comment by NotMoni** [comment]
@JudahGabriel I am unable to reproduce the issue. 
![Screen Shot 2020-06-04 at 4 53 53 PM](https://user-images.githubusercontent.com/40552237/83809139-f9cb5380-a683-11ea-949c-8365dfffb48f.png)

**Comment by NotMoni** [comment]
Could you provide us with your NodeJS and node-fetch version?

**Comment by JudahGabriel** [comment]
Yep, suspect it's an environment issue. Just hoping for some way to debug/fix it. :-)

Node 12.17.0
node-fetch 2.6.0

**Comment by JudahGabriel** [comment]
Definitely is an environment-specific issue; I tried on my laptop and it works fine. Same code on my desktop hangs. 

Maybe a node reinstall is in order. Closing this.

**Comment by pilotofbalance** [comment]
able to reproduce by fetching images in loop, buffer is hitting maximum size and just hanging.

**Comment by goldalworming** [comment]
It still happens and happen accidently. It's so hard to reproduce and try catch is not work to handle this.

t's bugged in long run system and became unpredicted. anybody have solution?
