### ISSUE TITLE
Bug: Timeout not work even explicitly specified

### ISSUE THREAD

**Issue by HuskyDanny** [node-fetch/node-fetch#885]
**Reproduction**

1.  using node-fetch to make a common http call to a service
2. with timeout set like 10000ms
3. 
4. 

**Expected behavior**
after 10000ms, request should stop and return timeout error

**Additional context**
My case here it just hangs there, and my gracefully exit comes after requests are done, so do we have a reliable way for request timeout? 
I do see people suggesting abortController with signal, is this the standard and reliable way?

Thanks

**Comment by jimmywarting** [comment]
> I do see people suggesting abortController with signal, is this the standard and reliable way?

Yes that is the official way to do it now (even in browser with native fetch). Timeout have been removed in v3 

you can use https://github.com/node-fetch/timeout-signal if you like.
but the deal is that you can control what it should timeout on (request, response or both)
you may also use abortcontroller for other stuff like aborting a request if some external condition applies (like: a client makes a request to a server and expect a response, you need to fetch something, and then the user disconnect/leave the site before it's complete, you no longer need to fetch the rest of the request/response so you can abort it also)
