### ISSUE TITLE
Feature request: data scheme support

### ISSUE THREAD

**Issue by Shestac92** [node-fetch/node-fetch#886]
The browser native `fetch` API supports the data scheme and it's very useful for getting blobs from base64 strings. For example, the following trick is very popular on the client-side:
```
var url = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="

fetch(url)
.then(res => res.blob())
.then(blob => {
    // apply blob to the form-data for example for further requests
});
```

Unfortunately, the current version of the `node-fetch` `2.6.0` supports only HTTP(S) protocols. The same code with using `node-fetch` throws the following error:
```
 TypeError: Only HTTP(S) protocols are supported
```

The same trick will be very useful in NodeJS. For example, it allows avoiding saving the base64 PNG string to the file and reading it back to a stream for further requests.
Below is a real code use-case in NodeJS where the node-fetch with support of data scheme will be very usefull:
```
  nodeFetch(base64PngString)
  .then(res => res.blob())
  .then(blob => {
    // create form 
    const form = new FormData();

    // append blob to the form
    form.append('image', blob);

    // send post request with the PNG image file
    nodeFetch(URL, {
      method: 'post',
      body: form,
      headers: form.getHeaders()
    });
  });
```

**Comment by xxczaki** [comment]
This feature is already supported in the beta version of node-fetch. You can try it under the `next` tag on npm:

```
$ npm install node-fetch@next
```

**Comment by vipulw2011** [comment]
@xxczaki I installed node-fetch@next but I am getting empty blob. What can be the issue ?
`await fetch(data)
                        .then(async (res) => {
                            let blob = await res.blob();
                            console.log("SystemAPI -> _fetch -> blob", blob)
                            return blob
                        })
                        .then(blob => {
                            console.log("SystemAPI -> _fetch -> blob", blob)
                        })`
