### ISSUE TITLE
Feature request: query-string as a parameter to config

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [node-fetch/node-fetch#887]
**Is your feature request related to a problem? Please describe.**
Currently, there's no built-in way of passing an object that can be used as stringified query-string.

I see this has been requested in https://github.com/node-fetch/node-fetch/issues/189, and it's still not implemented.

This is supported by most popular HTTP clients, such as [request](https://github.com/request/request#requestoptions-callback), [axois](https://github.com/axios/axios) and [superagent](https://visionmedia.github.io/superagent/#query-strings).

Is there a specific reason to avoid building this functionality? Are you open to a PR implementing this feature?

**Describe the solution you'd like**
```js
// this would internally call `https://www.my-website.com?userId=12345`
fetch('https://www.my-website.com', { qs: { userId: 12345 } });
```

**Describe alternatives you've considered**
I've seen code adding the query string manually, which is work that can be made much simpler.

**Comment by jimmywarting** [comment]
> Is there a specific reason to avoid building this functionality? Are you open to a PR implementing this feature?

no, It's not part of the official [spec](https://fetch.spec.whatwg.org/)

If you want to see this being implemented, turn to: https://github.com/whatwg/fetch and make a request there.
Best you can do for now is mention in the same thread at my last comment: https://github.com/node-fetch/node-fetch/issues/189#issuecomment-412213145

**Comment by AbdelrahmanHafez** [comment]
Fair enough, thank you.
