### ISSUE TITLE
Bug: "Known Differences" page on npm page doesn't exist. 

### ISSUE THREAD

**Issue by meatnordrink** [node-fetch/node-fetch#897]
**Reproduction**

1. Go to the npm page for `node-fetch`
2. Click on the "Known Differences" link under "Difference from client-side fetch"

**Expected behavior**

Page should load.

**Screenshots**

![image](https://user-images.githubusercontent.com/35735666/87159860-fed97f00-c28f-11ea-8a0c-c10accc0883e.png)

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       |
| node             |
| npm              |
| Operating System |

**Additional context**

**Comment by JefferyHus** [comment]
This is already fixed and will apply to npm once we publish the new version 👍
