### ISSUE TITLE
Question: What is the current version?

### ISSUE THREAD

**Issue by bradisbell** [node-fetch/node-fetch#901]
The version of this packaged published to NPM is 2.6.0, and hasn't been updated in over a year.  https://www.npmjs.com/package/node-fetch

Yet, the README (https://github.com/node-fetch/node-fetch) says the current stable release is 3.x, and says to install with `node install node-fetch`.  If someone does this they'll end up with 2.6.0.

And yet, the branches indicate that v3.x is a beta build.

What is the current package version recommended for production code?

**Comment by xxczaki** [comment]
The README on the `master` branch is for the `3.x` release, which is currently in beta. Even though the latest `2.x` is considered the most stable one, the `3.x` release already includes a lot of bug-fixes and new features. Therefore, I would recommend to use the beta release if you encountered a bug in v2, which does no longer exist in v3 OR the beta includes a feature which you need, that isn't available in current stable version ;)

Hope this helps!
