### ISSUE TITLE
Create blob from a list of chunks instead of one buffer

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#905]
Creating a huge buffer and use it as one blob part isn't such a good idea i think. (memory and arraybuffer size limitation wise)
A blob can contain multiple chunks of smaller buffers.

Now when i think about it... This code isn't perfect:
https://github.com/node-fetch/node-fetch/blob/1fdc218a64f8bc2c85bec0ca59a85973ef5e1f0a/src/body.js#L100-L111

Think we should rather read all the chunks and not concatenate all of it into one buffer. to avoid such ArrayBuffer size limitation.
We should rather do something like:

```js
 		const chunks = [];
 		for await (let chunk of this.body) {
			chunks.push(chunk);
		}
  
 		return new Blob(chunks, { 
 			type: ct 
 		}); 
```
This will directly reflect onto blob.stream() which emits Uint8arrays later on. And it would be best if that wasn't one single huge buffer

We previously used one single Buffer internally in Blobs to handle slicing before... but now it operates on blob parts instead. and the slice work a bit different now, which allows us to slice on a range of multiple parts

_Originally posted by @jimmywarting in https://github.com/node-fetch/node-fetch/issues/893#issuecomment-665692689_

**Comment by jimmywarting** [comment]
Not sure if we should do it exactly like how i suggested. We still must support aborting.

**Comment by JefferyHus** [comment]
From my conversation in #893 I believe that one buffer is still and should be working, from the node.js documentation the limit is Memory related and not like the front end which is strictly limited to a certain size.

**Comment by jimmywarting** [comment]
Still think it would be better to have multiple chunks doe. not 100% sure why it would be better or worse. But i assume when you concat all buffers into one huge one you will allocate twice as much memory (ofc it will be garbage collected later)

**Comment by memartello** [comment]
This is solved? I'm having  this issues in the front end with the limitation of the browser. I can't find where to save the chunk array till my download is completed.
