### ISSUE TITLE
Question: Post request with form data fails after switching from request-promise to node-fetch

### ISSUE THREAD

**Issue by jz222** [node-fetch/node-fetch#906]
Hi, I've replaced `request-promise` with `node-fetch`. Everything works well except for one request, which sends form data to an endpoint that I, unfortunately, can't provide here. This is the code that works with `request-promise`:

```javascript
const options = {
    method: 'POST',
    uri: keys.endpointUrl,
    formData: {
        operations: JSON.stringify(operations),
        map: JSON.stringify(map)
    },
    json: true
};

const response = await request(options);
```

After moving to `node-fetch`, it looks like so:

```javascript
const FormData = require('formdata-node');

const form = new FormData();

form.set('operations', JSON.stringify(operations));
form.set('map', JSON.stringify(map));

const opts = {
    method: 'POST',
    body: form
};

const res = await fetch(keys.endpointUrl, opts);

console.log(res);

const response = res.json();
```

`res` is logged as:

```javascript
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object],
      [Symbol(kCapture)]: false
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: Headers { [Symbol(map)]: [Object: null prototype] }
  }
}
```

I tried to add different headers but unfortunately, it keeps failing. What am I missing?

NodeJS: v12.16.1
node-fetch: 2.6.0

**Comment by jimmywarting** [comment]
Hmm, it would be more helpful to see what headers are being sent to debug this. (both before and after)

I don't see any obvious error from this except part from where you maybe should change this 
```diff
- const response = res.json();
+ const json = await res.json();
```

Try the following and maybe see what you get out of it:
```js
const req = new Request(keys.endpointUrl, opts)
console.log(...req.headers)
console.log(await req.blob())
```

also what node-fetch version are you using?

**Comment by jz222** [comment]
Thanks for getting back to me. Replacing `formdata-node` with `form-data` solved the issue for me. I couldn't track down the issue though, since the provided headers were similar. Closing this. Thank you.
