### ISSUE TITLE
Response Header.get() implementaion is wrong

### ISSUE THREAD

**Issue by giy-debug** [node-fetch/node-fetch#911]
The Response Headers implementation is wrong. The Headers.get function converts arrays to strings. This neither conforms to Map nor the URLSearchParams class definitions. This is a problem when you try to parse the `set-cookie` headers 
```js
/**
  * Return combined header value given name
  *
  * @param   String  name  Header name
  * @return  Mixed
  */
	get(name) {
		name = `${name}`;
		validateName(name);
		const key = find(this[MAP], name);
		if (key === undefined) {
			return null;
		}

		return this[MAP][key].join(', '); //this line is wrong
	}
```
**Expected behavior, if applicable**

Map implementation
```js
const map = new Map();
map.set('set-cookie', ['cookie1','cookie2'])
map.get('set-cookie'); 
// ['cookie1','cookie2']
```

The Headers class looks like a re-implementaion of URLSearchParams class, which is supported natively. You could save yourself a lot of code, and the implementation could match the standard.
```js
const searchParams = new URLSearchParams();
searchParams.append('set-cookie', 'cookie1');
searchParams.append('set-cookie', 'cookie2');
searchParams.get('set-cookie');      //"cookie1"
searchParams.getAll('set-cookie');  //["cookie1", "cookie2"]
```
As you can see `searchParams.get('set-cookie')` doesn't join the values but Headers.getAll doesn't exist in your implementation.

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       |  2.6.0
| node             | 12.18.2
| npm              | 6.14.5
| Operating System | Win10

### From MDN 
https://developer.mozilla.org/de/docs/Web/API/Headers

##### Obsolete methods
**Headers.getAll()**
Used to return an array of all the values of a header within a Headers object with a given name; this method has now been deleted from the spec, and **Headers.get() now returns all values of a given name** instead of just the first one

**Comment by jimmywarting** [comment]
Did you forgot to read the part of where it says: "Obsolete"?

Used to return an array of all the values of a header within a Headers object with a given name; **this method has now been deleted from the spec**, and Headers.get() now returns all values of a given name instead of just the first one.

**Comment by jimmywarting** [comment]
https://github.com/node-fetch/node-fetch/issues/251#issuecomment-428143940

**Comment by giy-debug** [comment]
But the implode is still wrong... And it also says **Headers.get() now returns all values of a given name**

**Comment by jimmywarting** [comment]
> To get a name name from a header list list, run these steps:
> 
> 1. If list does not contain name, then return null.
> 2. Return the values of all headers in list whose name is a byte-case-insensitive match for name, **separated from each other by 0x2C 0x20**, in order.

https://fetch.spec.whatwg.org/#terminology-headers

0x2C === comma
0x20 === space

Browser behavior: https://jsfiddle.net/zL04o17w/

**Comment by jimmywarting** [comment]
This might be relevant for ya: https://github.com/whatwg/fetch/issues/973
