### ISSUE TITLE
Feature request: support response.buffer('base64')

### ISSUE THREAD

**Issue by caub** [node-fetch/node-fetch#923]
**Is your feature request related to a problem? Please describe.**

AWS Lambda serverless can't return raw binary data, so we need to respond with base64-encoded data, this looks like:
```js
const pdfBuffer = await fetch(lambdaUrl, opts)
  .then(r => r.text())
  .then(text => Buffer.from(text, 'base64'));

// fs.writeFileSync('test.pdf', pdfBuffer); // for debug
```
This doesn't work:
```js
const pdfBuffer = await fetch(lambdaUrl, opts)
  .then(r => r.buffer());
```

**Describe the solution you'd like**

It'd be great to support a more concise way:
```js
const pdfBuffer = await fetch(lambdaUrl, opts)
  .then(r => r.buffer('base64'));
```

**Describe alternatives you've considered**

I considered something ugly like (supported in v3)
```js
const pdfBuffer = await fetch(lambdaUrl, opts)
  .then(r => fetch(`data:application/pdf;base64,${await r.text()}`))
  .then(r => r.buffer());
```

We could also add a feature request on what-wg fetch Response#arrayBuffer

**Additional context**

**Comment by jimmywarting** [comment]
Don't wish to put in more none speced feature into node-fetch.

I don't know if `content-transfer-encoding: base64` is a thing and if browser supports it or not. my assumption is that it don't.
but if it where then we could automatically decode it.

A better option would be to not use base64 in the first place. It's a waste of bandwidth and data processing
Maybe https://github.com/maciejtreder/serverless-apigw-binary could be an option for you?

**Comment by caub** [comment]
@jimmywarting thanks, actually, specifying `Accept: 'application/pdf'` header fixed it, I can just use `.then(r => r.buffer());` then
