### ISSUE TITLE
Bug: body.pipe is not a function

### ISSUE THREAD

**Issue by TimoZikeli** [node-fetch/node-fetch#930]
**Reproduction**

I am using node-fetch version 2.6.1 the following way:

```
const nFetch = require("node-fetch");
nFetch(url, options).then(response => {
    response.body.pipe(fs.createWriteStream("test.png"));
});
```
However, I am getting the following error: `response.body.pipe is not a function`. Apparently, the body object is of type [ReadableStream](https://developer.mozilla.org/de/docs/Web/API/ReadableStream) but not a NodeJS readable stream.
**Expected behavior**
I expect the `pipe` function to exist, as specified in the example

**Screenshots**

<img width="355" alt="ReadableStream" src="https://user-images.githubusercontent.com/18309528/92465123-72cfcf00-f1ce-11ea-8740-d6762be9227f.png">

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | 2.6.1
| node             | 14.9.0
| npm              | 6.14.8
| Operating System | macOS 10.15.5
| electron | 10.1.1

**Additional context**

I also tried to use node-fetch version 3, but since I am using electron, I am encountering [this bug](https://github.com/node-fetch/node-fetch/issues/917).

Thanks for your help!

**Comment by jasonswearingen** [comment]
and yet, there is a bug the other way, where ```body``` ends up being a node ```PassThrough``` stream where we expect it to be a ```ReadableStream```  (the ```ky``` package expects this)

see:   https://github.com/sindresorhus/ky-universal/issues/25

Please let me know if you need another issue posted, I thought I'd just append to this, as a 'fix' would impact all.
