### ISSUE TITLE
Being tournament organizer, sometime we need to correct board/game we have created. We are able to create board/game for 2 players base on their OAuth. Please add an update/delete method to correct those board if needed (limited to the boards that we created only):

### ISSUE THREAD

**Issue by eoyx12** [node-fetch/node-fetch#931]
Being tournament organizer, sometime we need to correct board/game we have created. We are able to create board/game for 2 players base on their OAuth. Please add an update/delete method to correct those board if needed (limited to the boards that we created only):
- delete/cancel the board. even if players are playing in it.
- update time control on the board

regards

Chacha

__Originally posted by @chadejava in https://github.com/lichess-org/api/issues/37__

**Comment by Richienb** [comment]
`node-fetch` only provides an API to interface with currently existing APIs.
