### ISSUE TITLE
cookie jar

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#94]
Maybe could be useful. what do you think? request uses it

https://www.npmjs.com/package/tough-cookie

**Comment by bitinn** [comment]
While I agree this is likely a solid implementation of server-side cookie jar, I am currently leaning towards allowing extraction of headers during redirection, which should allow extraction of cookie headers, then you can parse or store them or pass them to the next request as you may see fit.

It's more elaborate than `request`'s solution, but it allows us to not depends on any single cookie implementation.

See #8 item 2 and 3.

**Comment by jimmywarting** [comment]
You gave me an idea there...

It would be grate If we could extend node-fetch in some way with our own small module (like a cookie jar module or a cache module) (more or less like express, koa or connect `use` method) but in a way that reflects how browsers [service worker fetch event](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent) works

If we had a fetchEvent then we could mock data using [respondWith](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/respondWith). It would hook into all request being made (even all redirects). And we could build our own cookie jar

heck we could even modify all post data before it ever get sent (i think)

**Comment by bitinn** [comment]
Fetch Event is really intended for Service Worker, we don't currently support that on the server side (for the face that you do have full control of your server).

Another approach would be to add a custom flag that ignores Fetch Spec, ie. people have argue for a `nofollow` option where it won't reject the fetch promise, but just don't follow redirect and returns the headers (which is useful if you POST and expect a redirect and set-cookie headers)

**Comment by jimmywarting** [comment]
Anyway, I found this npm [fetch-cookie](https://www.npmjs.com/package/fetch-cookie) that solves my use case. However I still think it would be cool to have a fetchEvent that modules like fetch-cookie can hook into instead having to decorate it like he did

It could be used for authentication strategies in all request for a rest-api
If you were to use node-fetch as a proxy then it would be easy to just add cors headers to all response
if you want to decode/encode a different content-type (say [googles Protocol Buffers](https://developers.google.com/protocol-buffers/) `application/protobuf`) then it could be as easily as to just hook it into a fetchEvent
You could write your own network logger using fetchEvent instead of having to do it everywhere in the code
You could write your own cache mechanism that caches stuff and you would only have to write it once

think:
```
const fetch = require("node-fetch")
const fetchCache = require("fetch-cache")
const fetchCookie = require("fetch-cookie")({expire: '1Day'})
const fetchCompress = require("fetch-compress")
const fetchJpegTranscode = require("fetch-jpeg-transcode")

// this would be applied for all request being made
// super useful if you don't want to make it everywhere else in the code
fetch.on('fetch', fetchCookie)
fetch.on('fetch', fetchJpegTranscode)
fetch.on('fetch', fetchCache)

fetch('/login') // saves a cookie
fetch('/images/profile/hash.jpg') // would be transcoded to another format
fetch('/images/profile/hash.jpg') // would load from cache and wouldn't need transcode
fetch('/logout') // clears the cookie
```

**Comment by bitinn** [comment]
Interesting, thx for pointing `fetch-cookie` out, though I am not sure how it manage to fix the *redirect and set-cookie* problem (maybe it doesn't).

I agree Fetch Event is useful in your example, I guess it can be a future feature, though it relates to service worker spec more and quite a task to implement properly in node.js

**Comment by jimmywarting** [comment]
Once you get the Fetch Event implement done right then this would become super useful and we could expect to see more sub modules wish would make node-fetch more popular

`res.json()` could be an example of that
Guessing it would look something like this:
```
// fetch-json.js
var fetch = require('node-fetch')

module.export(evt => {
	evt.request.json = () =>
		fetch(evt.request).then(body => JSON.parse(body))
}
```
This may seem useless but it shows you how it could work and how you would go by implementing `.arrayBuffer()` for those who want node-fetch to support it

**Comment by bitinn** [comment]
I will leave this as *wontfix* because we don't intend to add a default cookie jar and existing solutions are good enough:

- https://github.com/valeriangalliat/fetch-cookie
- https://github.com/jonnyburger/real-isomorphic-fetch
- https://www.npmjs.com/package/fetch-cookie-es5

**Comment by developer239** [comment]
@bitinn 

https://www.npmjs.com/package/fetch-cookie-es5 and https://github.com/valeriangalliat/fetch-cookie does not work with `node-fetch@2` anymore.

**Comment by TimothyGu** [comment]
@developer239 You should probably file issues at those repos instead :)

**Comment by FabianTe** [comment]
I am currently working on resolving those issues with `node-fetch`. Please try using this package and post issues when having any :)

**Comment by developer239** [comment]
@FabianTe I believe I ended up using https://github.com/visionmedia/superagent because it is universal and did all the things I needed it to do.
