### ISSUE TITLE
السؤال: 

### ISSUE THREAD

**Issue by Kapp1** [node-fetch/node-fetch#940]
**Example Code**

```js
```

**Expected behavior, if applicable**

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       |
| node             |
| npm              |
| Operating System |

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by xxczaki** [comment]
Please create a new issue and remember to fill an issue template and provide a title in English.
