### ISSUE TITLE
Bug: Denial of Service when using npm

### ISSUE THREAD

**Issue by kockok** [node-fetch/node-fetch#942]
**Reproduction**

1. run `npm audit`
2. cannot be fixed by running `npm audit fix`

**Expected behavior**

no vulnerabilities

**Screenshots**

![Screenshot 2020-09-14 at 2 02 15 PM](https://user-images.githubusercontent.com/232541/93049264-3ea75300-f693-11ea-8ffa-6b0a561a6120.png)

**Your Environment**

| software         | version
| ---------------- | -------
| node-fetch       | latest
| node             | latest
| npm              | latest
| Operating System | latest macOs

**Comment by Richienb** [comment]
@kockok We already fixed that vulnerability. It is up to the packages depending on node-fetch to update to the newer version.
