### ISSUE TITLE
Bug: Link to error handling on NPMJS is broken

### ISSUE THREAD

**Issue by w3bdesign** [node-fetch/node-fetch#951]
**Reproduction**

1. Go to https://www.npmjs.com/package/node-fetch#handling-client-and-server-errors 
2. Click on the `error handling document` link
3. See that it links to the wrong URL

**Expected behavior**

The link should work. 

It should link to `https://github.com/node-fetch/node-fetch/blob/master/docs/ERROR-HANDLING.md`

**Screenshots**

![image](https://user-images.githubusercontent.com/45217974/93270295-20d01000-f7b1-11ea-8965-0292e3e715a8.png)

**Comment by Richienb** [comment]
This is no longer the case in the current HEAD.
