### ISSUE TITLE
temporarily disable issue template?

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/node-fetch#962]
I'm thinking maybe temporarily disable all github issue templates to avoid spam
You can't submit a issue without a body or title...

what do you think?

have no idea where the spam comes from

**Comment by Richienb** [comment]
Yeah that's probably a good idea

**Comment by d-shaun** [comment]
I think the "spam" came from people coming across the Dependabot alert (`GHSA-w7rc-rwvf-8q5r`), which has, on the "For more information" section, this direct link to open a new issue in this repo with template: `https://github.com/node-fetch/node-fetch/issues/new?assignees=&labels=question&template=support-or-usage.md&title=Question%3A+`.

**Comment by xxczaki** [comment]
@d-shaun Some spam might come from it, although:

a) clicking this link does not automatically create an issue;
b) the link points to the "Question" template and some spam issues were from the "Bug report" template.
