### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by saint-justin** [node-fetch/node-fetch#974]
**Is your feature request related to a problem? Please describe.**

The current NPM page is outdated compared to the current GitHub repo .readme file (specifically in use of promises).

**Describe the solution you'd like**

Update NPM page to reflect the current .readme in the repo.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by saint-justin** [comment]
Is the npm page's front-end is stored somewhere in the repo and I just can't find it, let me know where and I can make a pull request based off a fork.

**Comment by tekwiz** [comment]
@saint-justin NPM uses the README file from inside the latest stable package (2.6.1 as of 11/28), so it is up-to-date with what you get when you `npm install node-fetch`.  The master branch currently represents v3, which is in beta, but a support branch for 2.x does exist if you would like to make an update for that: https://github.com/node-fetch/node-fetch/tree/2.x
