### ISSUE TITLE
How to retrieve the final URL after redirects

### ISSUE THREAD

**Issue by j-a-h-i-r** [node-fetch/node-fetch#978]
I'm trying to GET an URL that has 1 level redirection with a 302 status code. When I console.log the response object, I see the redirected URL printed. But how do I extract the redirected URL?

**Example Code**

```js
let url  = `https://fiftytwo-store-dev.myshopify.com/cart/35477584904359:1`;

let response = await fetch(cartCheckoutURL, {
   method: 'GET',
});
console.log('response', response);
/** The part where the redirected URL is visible,
[Symbol(Response internals)]: {
    url: 'https://fiftytwo-store-dev.myshopify.com/44064604327/checkouts/0e0df47812b3b75973cbb13cf30d6c2a',
    status: 200,
    statusText: 'OK',        
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 1
  }
*/
```

As you can see, the actual redirected URL is being printed on the console. How do I retrieve that from the response object?

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       | ^2.6.0

**Comment by jimmywarting** [comment]
try `console.log(response.url)`

**Comment by j-a-h-i-r** [comment]
That worked!

**Comment by sofian-ysf** [comment]
Hey, I’m struggling to implement this myself. How are you getting this code to run when a certain page loads. My front end is built using ReactJs.
