### ISSUE TITLE
Question: how do i update node-fetch???? 

### ISSUE THREAD

**Issue by arturogarciagarcia** [node-fetch/node-fetch#982]
**Example Code**

```js
```

**Expected behavior, if applicable**

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       |
| node             |
| npm              |
| Operating System |

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by RocktimSaikia** [comment]
Use `npm install <packagename>@latest` to upgrade to the latest major version of any package not only node-fetch

**Comment by Richienb** [comment]
You could also change the version in the package.json to a newer one and rerun `npm install` .
