### ISSUE TITLE
Question: i have too many transfer funding in my wallet maybe all of them is block and some is ballance lock... casn i  unlock them ???

### ISSUE THREAD

**Issue by abbaskiko** [node-fetch/node-fetch#996]
**Example Code**

```js
```

**Expected behavior, if applicable**

### Your Environment

| software         | version
| ---------------- | -------
| node-fetch       |
| node             |
| npm              |
| Operating System |

**Additional context/Screenshots**

Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by abbaskiko** [comment]
ok

**Comment by Richienb** [comment]
@abbaskiko What's your question?

**Comment by abbaskiko** [comment]
answer me thanks

**Comment by Richienb** [comment]
You are currently asking this question in the node-fetch repository. node-fetch is an npm package that ponyfills browser window.fetch. Perhaps you're looking for https://github.com/trustwallet/wallet-core?

**Comment by abbaskiko** [comment]
that is exactly of bug
i try this before

**Comment by Richienb** [comment]
@abbaskiko To open an issue on that repo, go to https://github.com/trustwallet/wallet-core/issues/new/choose
